prompt: kannst du diese datei interpretieren: "ORC_Full_SpeedGuide_TRUE_GRIT_27.12.2025.pdf"


---

Gemini: Ja, ich kann diese Datei interpretieren. Es handelt sich um einen **ORC Speed Guide** (Offshore Racing Congress) für das Jahr 2025.

Hier ist eine Zusammenfassung der wichtigsten Daten und Parameter für dein Boot:

### 1. Bootsdaten

*  **Name:** TRUE GRIT
*  **Segelnummer:** GER 7447
*  **Bootstyp:** JPK 10.80
*  **Segelkonfigurationen in der Datei:**
*  **Headsail (Vorsegel):**  
*  **Asymmetric on Centerline (Gennaker):**  
*  **Symmetric (Spinnaker):**  

### 2. Was die Tabellen zeigen

Die Datei enthält Polardiagramm-Daten (Leistungstabellen), die vorhersagen, wie schnell das Boot bei verschiedenen Windgeschwindigkeiten (TWS) und Windwinkeln (TWA) segeln sollte.

Die Spalten bedeuten im Detail:

*  **TWS (True Wind Speed):** Wahre Windgeschwindigkeit (z. B. 6, 8, 10, 12, 14, 16, 20, 24 Knoten).


*   **TWA (True Wind Angle):** Wahrer Windeinfallswinkel (z. B. 52°, 60°, 90°, 150°).
* **BTV (Boat Target Velocity):** Deine Zielgeschwindigkeit durchs Wasser. Das ist der wichtigste Wert für den Steuermann/Trimmer.
* **VMG (Velocity Made Good):** Die gutgemachte Geschwindigkeit direkt nach Luv (gegen den Wind) oder Lee (mit dem Wind).
* **AWS / AWA:** Scheinbarer Wind (Speed und Angle).
*  **Heel:** Die optimale Krängung (z. B. 23.5° bei 12 kn Wind).
* **Reef & Flat:** Indikatoren, wann gerefft werden muss (Wert < 1.00) oder das Segel flach getrimmt werden muss.

### 3. Beispiel-Analyse (Leistungsdaten)

Basierend auf den Tabellen kann man sehen, wo die "Sweet Spots" des Bootes liegen.

**Am Wind (Upwind VMG):**
* Bei **10 Knoten Wind** liegt der optimale Winkel (TWA) bei ca. **39.0°** mit einer Zielgeschwindigkeit (BTV) von **6.25 kn**.
* Bei **14 Knoten Wind** solltest du etwa **38.0°** steuern für **6.55 kn** Speed.
**Vor dem Wind (Downwind):**
* Hier unterscheidet die Datei zwischen den verschiedenen Spi-Typen (Symmetric vs. Asymmetric).
* Beispiel **Asymmetric (Gennaker) bei 14 kn Wind**:
* Bei 135° TWA: **9.00 kn** Speed.
* Tiefster VMG Winkel (bestes Ablaufen): Ca. **159.2° TWA** bei **7.73 kn** Speed.

**Symmetric (Spinnaker) bei 12 kn Wind**:

* Bei 150° TWA: **7.35 kn** Speed.
* Optimaler VMG Winkel (tiefer): **157.9°** mit **7.01 kn** Speed.

### Zusammenfassung für den Einsatz an Bord

Diese Datei ist essenziell, um Polartabellen für deinen Bordcomputer (Expedition, Adrena, etc.) zu erstellen oder um laminierte **"Target-Cards"** für das Cockpit zu drucken.

prompt: *ich habe dir die VPP-Dokumentation hochgeladen. bist du dazu imstande, aus daraus und aus dem speed guide für mein boot eine art reverse engineering zu machen, mit dem ich berechnen könnte, welche einfluss eine um 2sqm kleinere jib haben würde? überlege dir eine ja/nein-Antwort und erläutere mir dann die gründe für deine entscheidung*


---

gemini: **Nein**, im streng wissenschaftlichen Sinne bin ich nicht dazu imstande, ein komplettes "Reverse Engineering" des VPPs durchzuführen, um die *exakten* neuen Polardaten (Geschwindigkeiten) für eine kleinere Jib zu berechnen.

**Aber: Ja**, ich kann dir basierend auf den vorliegenden Daten und der VPP-Logik eine **sehr genaue Abschätzung** geben, welche Auswirkungen die Verkleinerung haben wird.

Hier ist die Erläuterung meiner Entscheidung und die Analyse:

### 1. Warum "Nein" zur exakten Berechnung?

Ein VPP (Velocity Prediction Program) ist ein Gleichungslöser, der zwei Hauptkräfte gegeneinander aufwiegt:

* **Aerodynamik (Segel):** Vortrieb & Krängung (das haben wir durch die Segelfläche).
* **Hydrodynamik (Rumpf):** Widerstand & Aufrichtendes Moment (das fehlt uns).

Um die *neue* Geschwindigkeit exakt zu berechnen, bräuchte ich die **Widerstandskurve** deines Rumpfes (wie viel Kraft kostet es, das Boot von 6.0 auf 6.1 Knoten zu beschleunigen?). Diese Kurve steckt tief in den Rumpfdaten (Offset-File) und ist nicht in der PDF-Dokumentation enthalten. Ohne sie kann ich nicht sagen, ob 5% weniger Segelkraft zu 1% oder 3% Geschwindigkeitsverlust führen.

### 2. Warum "Ja" zur fundierten Abschätzung?

Der **Speed Guide** selbst liefert uns den Schlüssel zur Antwort, und zwar durch die Spalte **"Reef"**.

Das VPP simuliert nämlich bereits eine Verkleinerung der Segel, sobald das Boot überpowert ist. Wir können also schauen, wann das VPP *freiwillig* auf die Fläche deiner geplanten kleineren Jib reduziert.

**Die Analyse für deine Jib (-2 m²):**

* **Aktuelle Fläche:**
* **Neue Fläche:** ca.
* **Verhältnis:** Die neue Jib hat ca. **93,7%** der Fläche der alten ().

Ich schaue nun in deinen Speed Guide, wann der **Reef-Faktor** auf ca. **0.93 - 0.94** fällt:

#### Szenario A: Mittel- bis Starkwind (ab 14 kn TWS)

In deiner Tabelle bei **14 Knoten Wind** (Am Wind, 38° TWA) steht: **Reef:** **0.93**



**Das bedeutet:** Bei 14 Knoten simuliert das VPP bereits jetzt, dass du mit einer Segelfläche von ca. **29,5 m²** () am effizientesten unterwegs bist (optimale Krängung).

* **Einfluss der kleineren Jib:** **Null bis Positiv.**
* Du wärst mit der kleineren Jib bei 14 Knoten *genauso schnell* wie in der Tabelle vorhergesagt, da das Boot die extra Fläche der großen Jib ohnehin "wegreffen" oder flachziehen müsste (was Widerstand erzeugt).
* Die kleinere Jib steht dabei vermutlich sogar besser (weniger Profilverzug) als eine gereffte/gekillte große Genua.



#### Szenario B: Leichtwind (6 - 12 kn TWS)

Hier steht der **Reef-Faktor** konstant auf **1.00**. Das Boot giert nach jedem Quadratmeter Fläche.

* **Einfluss der kleineren Jib:** **Geschwindigkeitsverlust.**
* Da Aerodynamische Kraft grob proportional zur Fläche ist, verlierst du ca. 6% Vortriebskraft.
* Da der Wasserwiderstand bei Verdrängerfahrt quadratisch zur Geschwindigkeit wächst, ist der Geschwindigkeitsverlust ungefähr die Wurzel aus der Kraftänderung.
* **Schätzung:** Du wirst im Bereich 6-10 Knoten ca. **2% bis 3% an Bootspeed** verlieren (grob 0.1 bis 0.15 Knoten).



### Fazit für deine Entscheidung

Wenn du die 2qm kleinere Jib in Betracht ziehst:

1. **Ab 13-14 Knoten Wind** ist sie das **perfekte Segel** für dein Boot (entspricht genau der VPP-Vorgabe).
2. **Unter 10 Knoten Wind** wirst du einen spürbaren Nachteil haben.

Ist dein Revier eher windreich oder suchst du eine "Heavy Weather Jib" (J3/J3.5)? Dann ist das absolut sinnvoll. Als Allround-Segel für Leichtwindreviere ("Bodensee") wäre sie zu klein.

prompt: *ich würde gerne die im vollständigen speed guide dargestellten polarkurven mit einem python script plotten und a) auf meinem bildschirm ausgeben und b) als dxf auf meinem Plotter. schau dir die unterlagen an und gib mir eine ja/nein-antwort, ob du entsprechende software herstellen kannst. begründe anschließend deine antwort. sollte die antwort ja sein, beschreibe, wie du die aufgabe umsetzen willst. erzeuge zunächst keinen code.*

---

gemini:

**Ja**, ich kann entsprechende Software (ein Python-Script) für dich erstellen.

**Begründung:**

1. **Datenbasis:** Die von dir hochgeladene HTML-Datei ("ORC SpeedGuide") enthält die benötigten Leistungsdaten deines Bootes (Polardiagramm-Daten) in strukturierter Form (Tabellen und SVG-Grafiken). Diese Daten – spezifisch die Wahre Windgeschwindigkeit (TWS), der Wahre Windwinkel (TWA) und die Bootsgeschwindigkeit (BTV/BSP) – lassen sich maschinell auslesen.
2. **Technische Machbarkeit:** Python verfügt über spezialisierte Bibliotheken für alle drei Teilschritte:
* Datenextraktion (`pandas`, `BeautifulSoup` oder `Regex`).
* Grafische Darstellung am Bildschirm (`matplotlib`).
* CAD-Export (`ezdxf`).



**Geplante Umsetzung:**

Ich würde das Skript in drei logische Module unterteilen:

1. **Daten-Import (Parser):**
* Das Skript liest die HTML-Datei ein.
* Es sucht nach den Datentabellen, die die Geschwindigkeiten für verschiedene Windstärken (6, 8, 10, 12, 14, 16, 20, 24 kts) enthalten.
* Die Werte für TWA (Winkel) und BTV (Bootsgeschwindigkeit) werden bereinigt (Entfernen von Einheiten wie "kts" oder "°") und in eine strukturierte Tabelle (Dataframe) geladen.


2. **Bildschirm-Ausgabe (Plotter):**
* Verwendung der Bibliothek `matplotlib`.
* Erstellung eines polaren Koordinatensystems.
* Umrechnung der Windwinkel von Grad in Bogenmaß (da Python mathematisch in Radians rechnet).
* Zeichnen der Kurven für jede Windstärke in unterschiedlichen Farben.
* Hinzufügen einer Legende und Beschriftung.


3. **DXF-Export (CAD-Schnittstelle):**
* Verwendung der Bibliothek `ezdxf`.
* Erstellen einer neuen DXF-Zeichnung.
* Umrechnung der Polarkoordinaten (Winkel + Geschwindigkeit) in kartesische X/Y-Koordinaten (da DXF-Plotter kartesisch arbeiten).
* Generierung von `SPLINE`- oder `POLYLINE`-Objekten für jede Windkurve.
* Speichern der Datei als `.dxf` (kompatibel mit gängigen Plottern und Navigationssoftware).

prompt: ich habe weitere anforderungen.
1) ich möchte die Daten des Speed Guide in ein strukturiertes, digitales  Datenmodell überführen. Wir haben ja bereits über die reef, flat und kängungswerte gesprochen. Diese parameter sind ja wichtige bestandteile der jeweiligen kurven. die in diesem  datenmodell formatierten Daten möchte ich dann persitent machen. dazu möchte ich json benutzen.
2) ich möchte keine "standardplots" sondern die plots sollen parametriert werden:

    a) beliebige windstärke (werte zwischen den standardwerten)

    b) unterschiedliche downwindsegel (a3/a5, A2) etc.
    
    c) geänderte segelfläche (29sqm-Fock oder gereffte J2).
    
    Aufgrund der anforderung 1) schlage ich vor, wir zerlegen die software in 2 unabhängige module:  zunächst sammeln und strukturieren wir die daten, dann geben wir sie in eine datei aus. das plotmodul liest dann diese datei und erzeugt die plots.
    
was hältst du von diesem konzept? beschreibe, wie du vorgehen willst. erzeuhe KEINEN Code.

Letzter Hinweis: die umsetzung erfolgt in Kombination von Google-Colab-Notebooks und doogle drive, muss aber auch auf einem lokalen pc (Chromebook, Windows) laufen mit oder ohne zugriff auf google drive.*

---

gemini: Das ist ein **ausgezeichnetes und sehr professionelles Software-Konzept**. Die Trennung in **Datenerfassung (Backend)** und **Datenverarbeitung/Visualisierung (Frontend)** folgt dem bewährten "Separation of Concerns"-Prinzip.

Das macht das System wartbar, erweiterbar und ermöglicht es dir später, auch andere Module (z.B. ein Routing-Tool) auf dieselbe JSON-Datenbasis aufzusetzen.

Hier ist mein detaillierter Plan zur Umsetzung deiner Anforderungen:

### Teil 1: Die Daten-Architektur (JSON-Modell)

Das Herzstück wird das JSON-Schema sein. Es darf keine flache Liste sein, sondern muss die physikalischen Abhängigkeiten abbilden.

**Geplante Struktur der JSON-Datei (`true_grit_polar.json`):**

* **Meta-Daten:** Bootsname, Segelnummer, generelles Setup.
* **Sail Inventory:** Eine Liste der Segel mit ID, Typ (Jib, Asym, Sym) und Fläche (aus dem PDF/HTML geparst).
* **Performance Data:** Hier speichern wir die "Raw Data" aus dem Speed Guide, aber dimensional strukturiert:
* Ebene 1: **Segel-Konfiguration** (z.B. "Jib", "Asym_116", "Sym_115").
* Ebene 2: **TWS** (Wahre Windgeschwindigkeit: 6, 8, ... 24).
* Ebene 3: **TWA** (Wahrer Windwinkel).
* Ebene 4: **Werte-Objekt** `{ "bsp": 6.25, "vmg": 4.85, "heel": 23.0, "reef": 1.00, "flat": 0.96 }`.



*Warum JSON?* Es ist menschenlesbar, wird von Python nativ unterstützt (`dict`) und lässt sich leicht mit anderen Anwendungen austauschen.

### Teil 2: Modul 1 – Der "Extractor" (Datenerfassung)

Dieses Modul läuft nur einmal (oder wenn du einen neuen Speed Guide bekommst).

1. **Input:** Das Skript liest die HTML-Datei ein.
2. **Parsing-Logik:**
* Es identifiziert die Tabellen für die verschiedenen Segel (nicht nur die Haupttabelle, sondern auch die spezifischen Tabellen für Asym/Sym, falls vorhanden).
* Es extrahiert nicht nur Speed, sondern zwingend auch **Reef**, **Flat** und **Heel**, da wir diese für deine Simulation (Anforderung 2c) brauchen.


3. **Persistenz:** Das Ergebnis wird als validierte JSON-Datei gespeichert.
4. **Environment-Weiche:** Das Skript prüft: "Bin ich in Colab?" -> Speichere in Google Drive. "Bin ich lokal?" -> Speichere im lokalen Verzeichnis.

### Teil 3: Modul 2 – Der "VPP Calculator & Plotter"

Dieses Modul ist das eigentliche Werkzeug, mit dem du arbeitest. Es lädt das JSON und führt Berechnungen *vor* dem Plotten durch.

**A) Die VPP-Engine (Calculation Layer)**
Hier setzen wir deine parametrisierten Anforderungen um:

1. **Interpolation (Beliebige Windstärke):** Wenn du 13 kn Wind anforderst, interpoliert das Skript linear (oder per Spline) zwischen den Datensätzen von 12 kn und 14 kn für alle Parameter (Speed, Heel, Reef).
2. **Downwind-Selektor:** Das Skript bietet dir eine Auswahl der im JSON gefundenen Vorwind-Segel an. Du kannst entscheiden: "Zeige mir die Kurve für den A2 (tief) vs. A3 (hoch)".
3. **Segelflächen-Simulation (Der "Reverse Engineering"-Algorithmus):**
* Hier implementieren wir die Logik, die wir vorhin besprochen haben.
* *Input:* Du gibst an: "Simuliere Jib mit 29.5 m²".
* *Logik:* Das Skript prüft den `reef`-Wert im JSON.
* Ist `reef` < 1.00 (z.B. 0.93 bei 14kn): Das Boot ist überpowert. Die kleinere Jib (93% Fläche) liefert die gleiche Leistung -> **Kein Speedverlust**.
* Ist `reef` = 1.00 (z.B. 8kn): Das Boot braucht Power. Die kleinere Jib liefert weniger Vortrieb -> **Speed wird rechnerisch reduziert** (basierend auf dem Verhältnis der Quadratwurzel der Flächenänderung).





**B) Der Plotter (Presentation Layer)**

* **Bildschirm:** Matplotlib zeichnet die *berechneten/interpolierten* Kurven.
* **DXF-Export:** Die berechneten Kurven werden in `ezdxf` Objekte umgewandelt. Wichtig hierbei: Wir können die *interpolierten* Kurven exportieren. Du kannst dir also eine DXF-Kurve exakt für "13.5 Knoten Wind mit der kleinen Fock" generieren lassen, um sie auf den Plotter zu laden.

### Teil 4: Die Umgebung (Colab & Lokal)

Um die Anforderung der Portabilität zu erfüllen, werde ich eine kleine Hilfsfunktion ("Boilerplate") an den Anfang beider Skripte stellen:

```python
# Konzept-Code (Pseudo)
def setup_environment():
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        return "/content/drive/MyDrive/Sailing/TrueGrit/"
    except ImportError:
        import os
        return os.getcwd() # oder ein fixer lokaler Pfad

```

Damit läuft der Code ohne Änderung sowohl in der Cloud als auch auf deinem Windows-Laptop.

**Bist du mit diesem Vorgehen einverstanden?** Wenn ja, würde ich als nächsten Schritt das **Modul 1 (Extractor)** entwickeln, um die JSON-Basis zu schaffen.

prompt: *nein, warte noch. ich habe hier (ORC_TrueGrit_7447_27.12.2025.dxt) die aktuelle Inventarliste für das Boot. benutze diese für die Segel und die übrigen technischen Daten. Kannst du die datei lesen? was könnte man noch mit den daten machen? warte mit dem code.*

---

gemini: Ja, ich kann diese Datei (`ORC_TrueGrit_7447_27.12.2025.dxt`) lesen und interpretieren.

Das ist die **"Design Data Exchange"**-Datei (oder das native ORC-Datenformat). Sie ist die "DNA" deines Messbriefs. Während der Speed Guide nur das *Ergebnis* der VPP-Berechnung (den Output) zeigt, enthält diese Datei den *Input* – also die exakte Physik deines Bootes.

### Was ich aus dieser Datei extrahieren kann (für unser JSON-Modell):

Anstatt generischer Platzhalter können wir nun **harte Fakten** in dein Datenmodell speisen:

1. **Das exakte Rigg (Rigging):**
*  (Länge des Bugspriets),  (Höhe des Spi-Falls).
* Das erlaubt uns, Segelflächen nicht nur abzulesen, sondern geometrisch ins Verhältnis zum Boot zu setzen.


2. **Die exakte Segel-Garderobe (Sails Inventory):**
* Die Datei listet jedes vermessene Segel einzeln auf (z.B. *Headsail 1*, *Headsail 2*, *Asym 1*, *Asym 2*).
* **Crucial Data:** Wir sehen nicht nur die Fläche (), sondern die Geometrie:
* **JL, LPG (Vorliek, Unterliek-Lot):** Unterscheidet eine J1 von einer J3.
* **SLU, SLE, SFL, AMG (Spi-Maße):** Damit können wir unterscheiden, welches deiner Asym-Segel ein "Runner" (A2/A4 - bauchig, breite Schultern) und welches ein "Reacher" (A3/A5 - flacher, schmaler) ist.




3. **Stabilität (Stability):**
* Die Datei enthält die Ergebnisse des Krängungstests (Inclining Test).
* Wir kennen damit das **Aufrichtende Moment (Righting Moment - RM)** bei verschiedenen Krängungswinkeln.


### Was man mit diesen Daten noch machen könnte (Mehrwert):

Da wir nun die "DNA" des Bootes haben, können wir weit über das reine Plotten von Kurven hinausgehen. Hier sind drei konkrete Vorschläge für Erweiterungen deines Tools:

#### 1. Intelligente Segel-Zuordnung ("Sail Chart Mapping")

Der Speed Guide gibt oft nur generische Kurven aus (z.B. "Asymmetric"). Mit der DXT-Datei können wir eine Logik bauen, die deine konkreten Segel auf diese Kurven mappt.

* *Beispiel:* Wir berechnen das Verhältnis von Mittelbreite zu Unterliek () deiner Spis.
* *Nutzen:* Das Tool kann dir im Plotter automatisch vorschlagen: *"Bei 120° TWA ist laut Geometrie dein **A3 (Code 0)** das effizienteste Segel, ab 145° TWA passt dein **A2** besser."* Wir machen aus abstrakten Polaren konkrete Segel-Empfehlungen.

#### 2. Präzise "Reef"-Simulation (Physik statt Raten)

Für deine Anforderung, eine 29qm Fock zu simulieren:

* Wir nutzen das **Righting Moment (RM)** aus der DXT-Datei.
* Wir berechnen das **Krängungsmoment (Heeling Moment)** der neuen Segelfläche basierend auf den Rigg-Daten ().
* *Nutzen:* Wir können mathematisch exakter bestimmen, bei wie viel Wind die 29qm Fock dieselbe Krängung erzeugt wie die 31qm Fock bei "Reef 0.93". Das macht dein "Reverse Engineering" deutlich präziser als nur über den Daumen zu peilen.

#### 3. Visuelles Rigg-Overlay im DXF

Da du die Daten auf einen Plotter (Navigationssystem) exportieren willst:

* Wir können aus den Rigg-Maßen () eine vereinfachte Draufsicht oder Seitenansicht des Segelplans als DXF-Layer erzeugen.
* *Nutzen:* Du siehst auf dem Plotter nicht nur die Polarkurve, sondern hast eine visuelle Referenz der Segeldimensionen proportional zum Boot.

### Einfluss auf das Konzept

Ich werde das Konzept für **Modul 1 (Extractor)** anpassen:

* Es liest jetzt **beide** Dateien:
1. `HTML` (für die Polardaten/Geschwindigkeiten).
2. `DXT` (für die Segel-Geometrie und Rigg-Daten).


* Das JSON-Modell wird erweitert: Das `Sail Inventory` wird nicht mehr manuell geschätzt, sondern **automatisch und exakt** aus der DXT-Datei befüllt.

**Soll ich mit diesem erweiterten Ansatz (Fusion aus HTML-Speed-Daten und DXT-Boots-Geometrie) beginnen?**

prompt: *ja. wir fangen an mit dem json - datenmodell.*

gemini: Das ist der richtige erste Schritt. Ein sauberes Datenmodell ("Digital Twin") ist die Basis für alles Weitere.

Hier ist der Entwurf für das **JSON-Datenmodell**, das die Informationen aus beiden Quellen (HTML Speed Guide & DXT Datei) fusioniert. Es ist so strukturiert, dass es sowohl die **statische Physik** (für deine Simulationen) als auch die **dynamische Leistung** (für die Plots) abbildet.

### Das JSON-Schema: `true_grit_data.json`

Ich habe das Modell in drei Hauptbereiche unterteilt: `meta`, `rig_and_sails` (aus DXT) und `polars` (aus Speed Guide).

```json
{
  "meta": {
    "boat_name": "TRUE GRIT",
    "sail_number": "GER 7447",
    "type": "JPK 10.80",
    "gph": 595.5,
    "source_date": "2025-12-27",
    "file_version": "1.0"
  },
  
  "rig_configuration": {
    "comment": "Extracted from DXT file for physics calculations",
    "p": 14.10,
    "e": 4.85,
    "i": 14.05,
    "j": 4.20,
    "spl": 4.20,
    "tps": 5.80,
    "mtw": 180.0,
    "rm_default": 135.5
  },

  "sail_inventory": [
    {
      "id": "HEAD_MAIN",
      "orc_code": "Headsail",
      "name": "Jib Light/Medium",
      "area": 31.68,
      "measurements": { "jl": 14.2, "lpg": 4.45, "jh": 0.0 },
      "is_rated_max": true
    },
    {
      "id": "SYM_MAX",
      "orc_code": "Symmetric",
      "name": "S2",
      "area": 115.00,
      "measurements": { "slu": 14.5, "sle": 14.5, "sfl": 7.8, "shw": 8.1 }
    },
    {
      "id": "ASYM_MAX",
      "orc_code": "Asymmetric",
      "name": "A2",
      "area": 116.03,
      "measurements": { "slu": 15.8, "sle": 14.2, "sfl": 8.5, "shw": 8.3 },
      "tack_point": "TPS"
    }
    // Hier können wir später manuell deine 29qm Jib oder andere Segel einfügen
  ],

  "polars": {
    "comment": "Performance data parsed from ORC Speed Guide HTML",
    "configurations": {
      
      "optimal": {
        "description": "Best Course / VMG performance (Composite)",
        "data": [
          {
            "tws": 6,
            "beat_angle": 42.3,
            "beat_vmg": 3.58,
            "run_angle": 145.0,
            "run_vmg": 4.10,
            "curve": [
              { "twa": 52, "bsp": 5.40, "heel": 5.2, "reef": 1.00, "flat": 1.00 },
              { "twa": 60, "bsp": 5.65, "heel": 5.8, "reef": 1.00, "flat": 1.00 },
              // ... weitere Winkel ...
              { "twa": 150, "bsp": 4.43, "heel": 2.8, "reef": 1.00, "flat": 1.00 }
            ]
          },
          // ... weitere Windstärken (8, 10, 12...) ...
          {
            "tws": 14,
            "beat_angle": 38.0,
            "beat_vmg": 5.16,
            "curve": [
              { "twa": 38, "bsp": 6.55, "heel": 22.1, "reef": 0.93, "flat": 0.75 },
              { "twa": 90, "bsp": 7.97, "heel": 17.1, "reef": 1.00, "flat": 1.00 }
            ]
          }
        ]
      },

      "asymmetric": {
        "description": "Specific Asymmetric on Centerline curve",
        "data": [
           // Struktur analog zu 'optimal', aber spezifisch für Gennaker-Tabelle
        ]
      },

      "symmetric": {
        "description": "Specific Symmetric curve",
        "data": [
           // Struktur analog zu 'optimal', aber spezifisch für Spi-Tabelle
        ]
      }
    }
  }
}

```

### Warum dieses Modell? (Begründung der Struktur)

1. **`rig_configuration`**:
* Um deine **29qm-Jib-Simulation** (Anforderung 2c) zu berechnen, brauche ich das Rigg (). Nur so kann ich das Krängungsmoment der neuen Fläche ins Verhältnis zum "Reef"-Faktor () setzen.
* `spl` (Spinnaker Pole) vs. `tps` (Tack Point Sprit): Wichtig für die Unterscheidung deiner Downwind-Optionen (Anforderung 2b).


2. **`sail_inventory`**:
* Hier speichern wir die *echten* Segel.
* **Erweiterbarkeit:** Wenn du eine 29qm Jib kaufst, fügen wir hier einfach ein neues Objekt `{ "id": "J_HEAVY", "area": 29.0 ... }` hinzu. Der Plotter kann dann darauf zugreifen.
* **Measurements:** `shw` (Mittelbreite) und `sfl` (Unterliek) verraten uns, ob es ein Runner oder Reacher ist.


3. **`polars` -> `curve` Objekt**:
* Hier sind die entscheidenden Parameter `reef` und `flat` direkt am Datenpunkt (`tws`/`twa`) gespeichert.
* Das ermöglicht dem Plotter später die Logik: *"Wenn TWS=14 und User wählt kleine Jib, schaue auf `reef`. Ist `reef` < 1.0? -> Zeige volle Speed. Ist `reef` = 1.0? -> Reduziere Speed."*



### Nächster Schritt

Ich werde nun den Python-Code (**Modul 1: Extractor**) schreiben, der:

1. Die DXT-Datei parst und `meta`, `rig` und `inventory` befüllt.
2. Die HTML-Datei parst und die komplexen Tabellen in die `polars`-Struktur überführt.
3. Das fertige JSON speichert.

Soll ich den Code generieren?

prompt: *ok, mach das. ich habe hier eine ergänzung. du hast für mich die klasse "drivehandler" geschrieben. benutze sie. sofern es notwendig ist, erweitere sie.*

---

gemini: Das ist eine sehr gute Ergänzung. Die Klasse `DriveHandler` ist sauber strukturiert und löst das Pfad-Problem zwischen Colab und lokalen PCs elegant. Ich werde sie 1:1 übernehmen und in den Extractor integrieren.

Hier ist der **komplette Code für Modul 1 (Extractor)**.

**Was dieser Code macht:**

1. Er bindet deine `DriveHandler`-Klasse ein.
2. Er nutzt `DriveHandler`, um die `.dxt` und `.html` Dateien zu öffnen (egal ob lokal oder in Drive).
3. Er parst die **DXT-Datei**, um Rigg-Daten () und die exakte Segelliste zu extrahieren.
4. Er parst die **HTML-Datei** (Speed Guide). Da Speed Guides oft sehr unterschiedlich formatiert sind, habe ich einen robusten Ansatz gewählt, der nach Tabellen sucht, die "TWA" und "BTV" enthalten, und versucht, auch "Heel", "Reef" und "Flat" zu finden.
5. Er speichert das Ergebnis als `true_grit_data.json`.

prompt: *jetzt machen wir die gegenprobe. erstelle eine neue, komplett getrennte routine, welche die JSON Datei wieder einlist. benutze wieder den DriveHandler, die formulare für die Dateien und den Pfad. entwirf eine Tabelle für die Schiffsdaten und die Segel. die Polar-Tabellen gibt zunächst numerisch aus, später vielleicht als plot. Entwirf erst dann code, wenn ich es freigebe. beschreibe, wie du vorgehen willst*

---

gemini: Das ist der absolut richtige Weg. Bevor wir mit Plots oder Simulationen beginnen, müssen wir sicherstellen, dass die "Quelle der Wahrheit" (das JSON) technisch sauber ist und inhaltlich genau das enthält, was wir erwarten.

Hier ist mein Konzept für **Modul 2: Der Inspektor (JSON Reader)**.

### Das Konzept

Ich werde eine Python-Routine schreiben, die völlig unabhängig vom Extractor ist. Sie verlässt sich nur auf die gespeicherte JSON-Datei.

**1. Infrastruktur & Setup**

* Ich nutze wieder die Klasse `DriveHandler`, um die JSON-Datei zu laden.
* Ich nutze **Pandas**, um die Daten für die Ausgabe schön zu formatieren. Pandas DataFrames sind in Colab das Mittel der Wahl für saubere, interaktive Tabellen.

**2. Tabelle 1: Schiffs- & Riggdaten (Das "Stammdatenblatt")**

* Ich führe die Daten aus `meta` (Name, GPH, Typ) und `rig_configuration` zusammen.
* *Herausforderung:* Die Rigg-Daten sind im JSON jetzt komplexe Objekte (`{value: 13.7, unit: "m", ...}`).
* *Lösung:* Die Routine wird diese Objekte "flachklopfen". Die Tabelle wird Spalten haben wie: *Attribut* (z.B. "P"), *Wert* (13.7), *Einheit* (m) und *Beschreibung* (Mainsail hoist). Das ergibt eine sehr gut lesbare technische Übersicht.

**3. Tabelle 2: Das Segel-Inventar**

* Ich iteriere durch die Liste `sail_inventory`.
* Ich erstelle eine Übersichtstabelle mit den Spalten:
* **Interner ID** (`HEAD_1`)
* **Typ** (`HEAD`)
* **ORC ID** (`#55940` - wichtig für den Cross-Check)
* **Name** ("Jib Light...")
* **Fläche** (in m²)
* **Genutzt?** (Ja/Nein - basierend auf `used_in_polars`)


* *Detail:* Die vielen Einzelmaße (JL, LPG...) lasse ich in der Übersicht weg, um die Tabelle lesbar zu halten, kann sie aber auf Wunsch für ein einzelnes Segel anzeigen.

**4. Tabelle 3: Die Polardaten (Numerische Matrix)**

* Das JSON speichert Kurven hierarchisch (`TWS` -> Liste von Punkten). Das ist gut für Computer, aber schlecht für menschliche Leser.
* *Lösung:* Ich werde die Daten "pivotisieren". Ich rechne die JSON-Struktur zurück in eine klassische **Matrix-Ansicht**:
* **Zeilen:** TWA (Winkel)
* **Spalten:** TWS (Windgeschwindigkeiten: 6, 8, 10...)
* **Werte:** BSP (Bootsgeschwindigkeit)


* Für jede Konfiguration (Optimal, Asymmetric, Symmetric) wird untereinander eine eigene Matrix ausgegeben. Das entspricht optisch fast genau dem ursprünglichen PDF-Ausdruck und erlaubt dir eine sofortige Prüfung der Zahlenwerte.

### Vorgehensweise

1. Ich kopiere die `DriveHandler` Klasse (damit Modul 2 autark läuft).
2. Ich implementiere die Lade-Logik mit Pandas.
3. Ich erzeuge die drei beschriebenen Ausgaben nacheinander.

Bist du mit diesem Konzept einverstanden? Dann generiere ich den Code.

In [ ]:
# @title Modul 1: ORC Data Extractor (Version 11 - inkl. AWA/AWS)
import sys
import os
import json
import re
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

# --- DRIVE HANDLER CLASS ---
class DriveHandler:
    COLAB_ROOT = '/content/drive'

    def __init__(self, directory=None, filename=None):
        self.filepath = None
        self._mounted = False
        self.file_handle = None
        if directory is not None and filename is not None:
            self.set_full_path(directory, filename)

    def _is_colab(self):
        return 'google.colab' in sys.modules

    def _mount_drive_if_needed(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                print("Google Colab erkannt. Mounte Drive...")
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True

    def set_full_path(self, directory, filename):
        if self._is_colab():
            self._mount_drive_if_needed()
            base = os.path.join(self.COLAB_ROOT, 'MyDrive')
            self.filepath = os.path.join(base, directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath

    def exists(self):
        return self.filepath is not None and os.path.exists(self.filepath)

    def open_read(self, encoding='utf-8', errors='ignore'):
        if not self.exists():
            raise FileNotFoundError(f"Datei nicht gefunden: {self.filepath}")
        self.file_handle = open(self.filepath, 'r', encoding=encoding, errors=errors)
        return self.file_handle

    def open_write(self, encoding='utf-8'):
        if not self.filepath:
            raise ValueError("Kein Pfad gesetzt.")
        directory = os.path.dirname(self.filepath)
        if directory and not os.path.exists(directory):
            os.makedirs(directory, exist_ok=True)
        self.file_handle = open(self.filepath, 'w', encoding=encoding)
        return self.file_handle

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.file_handle:
            self.file_handle.close()
        return False

# --- EXTRACTOR LOGIC ---

class OrcExtractor:
    def __init__(self):
        self.data = {
            "meta": {},
            "data_section": {},
            "user_section": {},
            "rig_configuration": {},
            "sail_inventory": [],
            "polars": {}
        }
        self._sail_map_by_orc_id = {}

    def _get_field_val(self, element, fieldname, default=None):
        if element is None: return default
        for child in element.iter():
            if child.tag.upper().endswith("FIELD"):
                if child.get("fieldname") == fieldname:
                    return child.get("value")
        return default

    def _extract_simple_section(self, root, tag_name):
        section_data = {}
        found_elem = None
        for elem in root.iter():
            if elem.tag.upper().endswith(tag_name.upper()):
                found_elem = elem
                break

        if found_elem is not None:
            for child in found_elem:
                clean_tag = child.tag.split('}')[-1] if '}' in child.tag else child.tag
                val = child.text.strip() if child.text else ""
                section_data[clean_tag] = val
        return section_data

    def parse_dxt(self, file_handle):
        print("Parsing DXT File (Greedy Mode + Metadata)...")
        try:
            tree = ET.parse(file_handle)
            root = tree.getroot()

            self.data["data_section"] = self._extract_simple_section(root, "DATA")
            self.data["user_section"] = self._extract_simple_section(root, "USER")

            inp = None
            for elem in root.iter():
                if elem.tag.upper().endswith("INPUT"):
                    inp = elem
                    break

            if inp is None:
                print("FEHLER: Kein INPUT Tag im XML gefunden.")
                return

            # 1. Meta Data
            self.data["meta"] = {
                "boat_name": self._get_field_val(inp, "YachtName", "Unknown"),
                "sail_number": self._get_field_val(inp, "SailNo", "Unknown"),
                "type": self._get_field_val(inp, "Class", "JPK 10.80"),
                "gph": float(self._get_field_val(inp, "GPH", "0") or 0.0)
            }

            # 2. Rig Configuration
            def rig_val(key, desc, unit="m"):
                val_str = self._get_field_val(inp, key, "0")
                return {
                    "value": float(val_str) if val_str else 0.0,
                    "unit": unit,
                    "description": desc
                }

            self.data["rig_configuration"] = {
                "p": rig_val("P", "Mainsail hoist"),
                "e": rig_val("E", "Mainsail outer point distance"),
                "i": rig_val("IG", "Height of foretriangle (IG used as I)"),
                "j": rig_val("J", "Base of foretriangle"),
                "spl": rig_val("SPL", "Spinnaker Pole Length"),
                "tps": rig_val("TPS", "Tack Point Sprit"),
                "isp": rig_val("ISP", "Height of spinnaker hoist"),
                "rm_default": rig_val("RMCe", "Righting Moment (Default)", "kgm")
            }

            # 3. Sail Inventory
            inventory = []
            sails_container = None
            for elem in inp.iter():
                if elem.tag.upper().endswith("SAILS"):
                    sails_container = elem
                    break

            if sails_container is not None:
                type_map = {
                    "headsail": "HEAD", "jib": "HEAD",
                    "main": "MAIN", "mainsail": "MAIN",
                    "sym_spin": "SYM", "symmetric": "SYM",
                    "asym_spin": "ASYM", "asymmetric": "ASYM"
                }

                for sail_elem in sails_container:
                    if not sail_elem.tag.upper().endswith("SAIL"): continue

                    raw_code = sail_elem.get("SailCode", "").lower()
                    my_type = type_map.get(raw_code, "OTHER")

                    for record in sail_elem:
                        if not record.tag.upper().endswith("RECORD"): continue

                        raw_attributes = {}
                        for child in record:
                            if child.tag.upper().endswith("FIELD"):
                                fname = child.get("fieldname")
                                fval = child.get("value")
                                if fname:
                                    raw_attributes[fname] = fval

                        area = float(raw_attributes.get("SailArea", 0) or raw_attributes.get("Area", 0))
                        orc_id = raw_attributes.get("SailId", "")

                        name = raw_attributes.get("CopiedFrom", "")
                        if not name: name = raw_attributes.get("Comment", raw_code)

                        internal_id = f"{my_type}_{len(inventory)+1}"

                        sail_entry = {
                            "internal_id": internal_id,
                            "orc_sail_id": orc_id,
                            "type": my_type,
                            "name": name,
                            "area": area,
                            "used_in_polars": False,
                            "attributes": raw_attributes,
                            "measurements": {}
                        }

                        for m in ["JL", "LPG", "SLU", "SLE", "SFL", "SHW", "SMG", "JH", "MGT", "MGU", "MGM", "MGL"]:
                            if m in raw_attributes and raw_attributes[m]:
                                try:
                                    key = m.lower()
                                    if key == "smg": key = "shw"
                                    sail_entry["measurements"][key] = float(raw_attributes[m])
                                except: pass

                        inventory.append(sail_entry)
                        if orc_id:
                            self._sail_map_by_orc_id[orc_id] = internal_id

            self.data["sail_inventory"] = inventory

            print(f" -> {len(inventory)} Segel im Inventar gefunden:")
            print(f"    {'ID':<10} | {'Type':<6} | {'Area':<6} | Name")
            print("    " + "-"*60)
            for s in inventory:
                print(f"    {s['internal_id']:<10} | {s['type']:<6} | {s['area']:<6.1f} | {s['name']}")
            print("    " + "-"*60)

        except Exception as e:
            print(f"DXT Parsing Fehler: {e}")

    def parse_html_speed_guide(self, file_handle):
        print("Parsing HTML Speed Guide (Container Mode)...")
        soup = BeautifulSoup(file_handle, 'html.parser')

        containers = soup.find_all("div", class_="polarcontainer")
        print(f" -> {len(containers)} Polar-Container gefunden.")

        polar_configs = {}

        for container in containers:
            title_div = container.find("div", class_="polarcontainer-title")
            full_title_text = title_div.get_text(" ", strip=True) if title_div else "Unknown"

            config_id = "other"
            is_composite = False

            if "Best Performance" in full_title_text or "Optimal" in full_title_text:
                config_id = "optimal"
                is_composite = True
            elif "Asymmetric" in full_title_text:
                config_id = "asymmetric"
            elif "Symmetric" in full_title_text:
                config_id = "symmetric"
            elif "Headsail" in full_title_text:
                config_id = "headsail"

            base_id = config_id
            counter = 1
            while config_id in polar_configs:
                config_id = f"{base_id}_{counter}"
                counter += 1

            linked_sail_id = None
            id_match = re.search(r"#(\d+)", full_title_text)

            if id_match:
                found_orc_id = f"#{id_match.group(1)}"
                if found_orc_id in self._sail_map_by_orc_id:
                    linked_sail_id = self._sail_map_by_orc_id[found_orc_id]
                    for s in self.data["sail_inventory"]:
                        if s["internal_id"] == linked_sail_id:
                            s["used_in_polars"] = True
                            break
                else:
                    print(f"    WARNUNG: HTML referenziert {found_orc_id}, aber ID ist nicht im DXT.")

            tables = container.find_all("table", class_="polartable")
            extracted_data = []

            for table in tables:
                caption = table.find("caption")
                if not caption: continue
                tws_match = re.search(r'TWS\s*=\s*(\d+)', caption.get_text())
                if not tws_match: continue
                tws = int(tws_match.group(1))

                rows = table.find_all("tr")
                if not rows: continue

                header_cells = rows[0].find_all("th")
                col_map = {}
                for idx, th in enumerate(header_cells):
                    col_map[th.get_text().strip().upper()] = idx

                points_for_tws = []
                for row in rows[1:]:
                    cells = row.find_all("td")
                    if not cells: continue
                    try:
                        # Helper mit Fallback
                        def get_val(name, default_idx):
                            idx = col_map.get(name, default_idx)
                            if idx < len(cells):
                                txt = cells[idx].get_text().strip()
                                return float(re.sub(r"[^\d\.]", "", txt))
                            return 0.0

                        twa = get_val("TWA", 0)
                        bsp = get_val("BTV", 1)
                        # Neue Felder:
                        vmg = get_val("VMG", 2)
                        aws = get_val("AWS", 3)
                        awa = get_val("AWA", 4)

                        heel = get_val("HEEL", 5)
                        reef = get_val("REEF", 6)
                        flat = get_val("FLAT", 7)

                        points_for_tws.append({
                            "twa": twa,
                            "bsp": bsp,
                            "vmg": vmg,
                            "aws": aws,
                            "awa": awa,
                            "heel": heel,
                            "reef": reef,
                            "flat": flat
                        })
                    except ValueError: continue

                if points_for_tws:
                    extracted_data.append({"tws": tws, "curve": points_for_tws})

            if extracted_data:
                polar_configs[config_id] = {
                    "description": full_title_text,
                    "is_composite": is_composite,
                    "linked_sail_internal_id": linked_sail_id,
                    "data": extracted_data
                }

                link_msg = ""
                if linked_sail_id:
                    s_name = "Unknown"
                    for s in self.data["sail_inventory"]:
                        if s["internal_id"] == linked_sail_id:
                            s_name = s["name"]
                            break
                    link_msg = f" -> Verknüpft mit {linked_sail_id} ({s_name})"

                print(f"    -> Konfig '{config_id}': {len(extracted_data)} Wind-Kurven.{link_msg}")

        self.data["polars"]["configurations"] = polar_configs

# --- MAIN EXECUTION ---

def main(data_dir, file_basename, output_filename):
    dxt_file = f"{file_basename}.dxt"
    html_file = f"{file_basename}.html"

    print(f"Arbeite mit Stamm: '{file_basename}'")
    extractor = OrcExtractor()

    # 1. DXT
    dxt_handler = DriveHandler(directory=data_dir, filename=dxt_file)
    if dxt_handler.exists():
        print(f"Lese DXT: {dxt_file}")
        with dxt_handler as dh: extractor.parse_dxt(dh.open_read())
    else:
        print(f"FEHLER: DXT Datei nicht gefunden: {dxt_handler.filepath}")
        sys.exit(1)

    # 2. HTML
    html_handler = DriveHandler(directory=data_dir, filename=html_file)
    if html_handler.exists():
        print(f"Lese HTML: {html_file}")
        with html_handler as dh: extractor.parse_html_speed_guide(dh.open_read())
    else:
        print(f"FEHLER: HTML Datei nicht gefunden: {html_handler.filepath}")
        sys.exit(1)

    # 3. JSON Output
    json_handler = DriveHandler(directory=data_dir, filename=output_filename)
    print(f"Speichere JSON nach: {json_handler.set_full_path(data_dir, output_filename)}")
    with json_handler as dh:
        f = dh.open_write()
        json.dump(extractor.data, f, indent=2)

    print("Fertig!")

if __name__ == "__main__":
    DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
    FILE_BASENAME = "ORC SpeedGuide TRUE GRIT 27.12.2025" # @param {type:"string"}
    OUTPUT_FILENAME = "ORC SpeedGuide TRUE GRIT 27.12.2025.json" # @param {type:"string"}

    main(DATA_DIR, FILE_BASENAME, OUTPUT_FILENAME)

Arbeite mit Stamm: 'ORC SpeedGuide TRUE GRIT 27.12.2025'
Lese DXT: ORC SpeedGuide TRUE GRIT 27.12.2025.dxt
Parsing DXT File (Greedy Mode + Metadata)...
 -> 11 Segel im Inventar gefunden:
    ID         | Type   | Area   | Name
    ------------------------------------------------------------
    MAIN_1     | MAIN   | 38.0   | destroyed
    MAIN_2     | MAIN   | 37.0   | 27.02.2019 Main Black 37.02sqm
    MAIN_3     | MAIN   | 37.0   | 25.03.2020 Main White Hvy 36.98sqm
    HEAD_4     | HEAD   | 31.7   | 24.03.2017 Blk-J1-NoZip-31.68sqm
    HEAD_5     | HEAD   | 29.3   | 27.4.2019 Blk-J2-Zip:1.25-29.34 sqm
    HEAD_6     | HEAD   | 27.6   | 25.03.2020 Hvy-J3-Zip:1.06-27.58sqm
    SYM_7      | SYM    | 88.8   | 18.03.2017 - White - 88.85sqm
    SYM_8      | SYM    | 114.7  | 26.04.2019 Blue - 114.66sqm
    SYM_9      | SYM    | 115.0  | 24.03.2020 Blue - 115.00sqm
    ASYM_10    | ASYM   | 116.0  | 20.11.2025 A2 - 116.03sqm
    ASYM_11    | ASYM   | 87.3   | 24.03.2020 A3-5 Red - 87.25sqm
    ------------------------------------------------------------
Lese HTML: ORC SpeedGuide TRUE GRIT 27.12.2025.html
Parsing HTML Speed Guide (Container Mode)...
 -> 5 Polar-Container gefunden.
    -> Konfig 'optimal': 8 Wind-Kurven.
    -> Konfig 'headsail': 8 Wind-Kurven. -> Verknüpft mit HEAD_4 (24.03.2017 Blk-J1-NoZip-31.68sqm)
    -> Konfig 'asymmetric': 8 Wind-Kurven. -> Verknüpft mit ASYM_10 (20.11.2025 A2 - 116.03sqm)
    -> Konfig 'asymmetric_1': 8 Wind-Kurven. -> Verknüpft mit ASYM_10 (20.11.2025 A2 - 116.03sqm)
    -> Konfig 'symmetric': 8 Wind-Kurven. -> Verknüpft mit SYM_9 (24.03.2020 Blue - 115.00sqm)
Speichere JSON nach: /content/drive/MyDrive/Segeln/ORC_Vermessung/ORC SpeedGuide TRUE GRIT 27.12.2025.json
Fertig!

In [ ]:
# @title Modul 2: Der Inspektor (Version 3 - Extended AWA/AWS)
import sys
import os
import json
import pandas as pd
from IPython.display import display, Markdown

# --- DRIVE HANDLER CLASS ---
class DriveHandler:
    COLAB_ROOT = '/content/drive'

    def __init__(self, directory=None, filename=None):
        self.filepath = None
        self._mounted = False
        self.file_handle = None
        if directory is not None and filename is not None:
            self.set_full_path(directory, filename)

    def _is_colab(self):
        return 'google.colab' in sys.modules

    def _mount_drive_if_needed(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                print("Google Colab erkannt. Mounte Drive...")
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True

    def set_full_path(self, directory, filename):
        if self._is_colab():
            self._mount_drive_if_needed()
            base = os.path.join(self.COLAB_ROOT, 'MyDrive')
            self.filepath = os.path.join(base, directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath

    def exists(self):
        return self.filepath is not None and os.path.exists(self.filepath)

    def open_read(self, encoding='utf-8', errors='ignore'):
        if not self.exists():
            raise FileNotFoundError(f"Datei nicht gefunden: {self.filepath}")
        self.file_handle = open(self.filepath, 'r', encoding=encoding, errors=errors)
        return self.file_handle

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.file_handle:
            self.file_handle.close()
        return False

# --- INSPECTOR LOGIC ---

class OrcInspector:
    def __init__(self, json_data):
        self.data = json_data

    def show_header(self, text):
        print("\n" + "="*80)
        print(f" {text.upper()}")
        print("="*80)

    def report_meta_and_rig(self):
        self.show_header("1. Schiffs- & Riggdaten")

        # Meta
        meta = self.data.get("meta", {})
        print(f"BOOTSNAME:   {meta.get('boat_name', '-')}")
        print(f"SEGELNUMMER: {meta.get('sail_number', '-')}")
        print(f"TYP:         {meta.get('type', '-')}")
        print(f"GPH:         {meta.get('gph', '-')}")

        # User / Data Section Check
        dsec = self.data.get("data_section", {})
        usec = self.data.get("user_section", {})
        if dsec: print(f"DXT DATE:    {dsec.get('dxtDate', '-')}")
        if usec: print(f"OWNER:       {usec.get('Fullname', '-')}")

        print("-" * 40)

        # Rigg Tabelle
        rig = self.data.get("rig_configuration", {})
        rig_rows = []

        for key, info in rig.items():
            if isinstance(info, dict):
                rig_rows.append({
                    "Parameter": key.upper(),
                    "Wert": info.get("value"),
                    "Einheit": info.get("unit"),
                    "Beschreibung": info.get("description")
                })
            else:
                rig_rows.append({
                    "Parameter": key.upper(),
                    "Wert": info,
                    "Einheit": "?",
                    "Beschreibung": "-"
                })

        if rig_rows:
            df_rig = pd.DataFrame(rig_rows)
            display(df_rig.style.hide(axis='index').format({"Wert": "{:.3f}"}))
        else:
            print("Keine Riggdaten gefunden.")

    def report_inventory(self):
        self.show_header("2. Segel-Inventar")

        inventory = self.data.get("sail_inventory", [])
        if not inventory:
            print("Keine Segel im Inventar.")
            return

        inv_rows = []
        for sail in inventory:
            # Checken ob Attributes da sind (Greedy Mode)
            attrs = sail.get("attributes", {})
            material = attrs.get("MaterialCode", "-")

            inv_rows.append({
                "Intern ID": sail.get("internal_id"),
                "Typ": sail.get("type"),
                "Fläche": sail.get("area"),
                "Name/Kommentar": sail.get("name"),
                "ORC ID": sail.get("orc_sail_id"),
                "Material": material,
                "Genutzt?": "JA" if sail.get("used_in_polars") else "nein"
            })

        df_inv = pd.DataFrame(inv_rows)
        display(df_inv)

    def report_polars(self):
        self.show_header("3. Polardiagramme (Check)")

        polars = self.data.get("polars", {}).get("configurations", {})

        if not polars:
            print("Keine Polardaten vorhanden.")
            return

        for config_id, config in polars.items():
            desc = config.get("description", config_id)
            is_composite = config.get("is_composite", False)
            linked = config.get("linked_sail_internal_id", "-")

            print(f"\n---> Konfiguration: {desc} (ID: {config_id})")
            if is_composite:
                print("     [Composite / Hüllkurve]")
            if linked and linked != "-":
                print(f"     [Verknüpftes Segel: {linked}]")

            curve_data = config.get("data", [])

            # Alle Punkte sammeln
            flat_points = []
            available_tws = set()

            for item in curve_data:
                tws = item["tws"]
                available_tws.add(tws)
                for pt in item["curve"]:
                    flat_points.append({
                        "TWA": pt.get("twa"),
                        "TWS": tws,
                        "BSP": pt.get("bsp"),
                        "AWA": pt.get("awa"), # Neu
                        "AWS": pt.get("aws"), # Neu
                        "VMG": pt.get("vmg"), # Neu
                        "HEEL": pt.get("heel")
                    })

            if flat_points:
                df = pd.DataFrame(flat_points)

                # 1. Die klassische Matrix (nur Speed)
                print("\n   >> Matrix: Bootsgeschwindigkeit (BSP)")
                matrix = df.pivot(index="TWA", columns="TWS", values="BSP")
                display(matrix.style.format("{:.2f}").background_gradient(cmap="Blues", axis=None))

                # 2. Detail-Check für EINE Windstärke (um AWA/AWS zu prüfen)
                # Wir nehmen 10 kn oder die erste verfügbare
                check_tws = 10 if 10 in available_tws else list(available_tws)[0]
                print(f"\n   >> Detail-Check (Neue Felder) für TWS = {check_tws} kn:")

                df_check = df[df["TWS"] == check_tws].copy()
                # Wir zeigen nur relevante Spalten
                cols_to_show = ["TWA", "BSP", "AWA", "AWS", "VMG", "HEEL"]
                # Filtere Spalten die auch wirklich da sind
                cols_final = [c for c in cols_to_show if c in df_check.columns]

                display(df_check[cols_final].sort_values("TWA").style.format("{:.2f}").hide(axis='index'))

            else:
                print("     Keine Datenpunkte.")

# --- MAIN EXECUTION ---

def main(data_dir, json_filename):
    print(f"Lade Daten aus: {json_filename} ...")

    handler = DriveHandler(directory=data_dir, filename=json_filename)
    if not handler.exists():
        print(f"FEHLER: Datei nicht gefunden: {handler.filepath}")
        return

    try:
        with handler as h:
            with h.open_read() as f:
                json_data = json.load(f)
    except Exception as e:
        print(f"FEHLER beim Lesen des JSON: {e}")
        return

    inspector = OrcInspector(json_data)

    inspector.report_meta_and_rig()
    inspector.report_inventory()
    inspector.report_polars()

    print("\nInspektion abgeschlossen.")

if __name__ == "__main__":
    DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
    JSON_FILENAME = "ORC SpeedGuide TRUE GRIT 27.12.2025.json" # @param {type:"string"}

    main(DATA_DIR, JSON_FILENAME)

In [ ]:
# @title Modul 3: Der Plotter (Version 6 - Structured Headers)
import sys
import os
import json
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from scipy.interpolate import make_interp_spline

# --- DRIVE HANDLER ---
class DriveHandler:
    COLAB_ROOT = '/content/drive'

    def __init__(self, directory=None, filename=None):
        self.filepath = None
        self._mounted = False
        if directory and filename:
            self.set_full_path(directory, filename)

    def _is_colab(self):
        return 'google.colab' in sys.modules

    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True

    def set_full_path(self, directory, filename):
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath

    def exists(self): return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

# --- HELPER FUNCTIONS ---

def clean_text(text):
    if not text: return ""
    return " ".join(text.split())

def smooth_curve(angles, speeds, num_points=200):
    if len(angles) < 4: return np.radians(angles), speeds
    sorted_pairs = sorted(zip(angles, speeds))
    x = np.array([p[0] for p in sorted_pairs])
    y = np.array([p[1] for p in sorted_pairs])
    x_new = np.linspace(x.min(), x.max(), num_points)
    try:
        spl = make_interp_spline(x, y, k=3)
        y_new = spl(x_new)
        y_new = np.maximum(y_new, 0)
        return np.radians(x_new), y_new
    except:
        return np.radians(x), y

def generate_structured_header(config_data, meta_data, sail_inventory):
    """
    Erstellt 3 saubere Zeilen basierend auf strukturierten Daten.
    """
    # --- ZEILE 1: Schiffsdaten (Meta) ---
    bname = meta_data.get("boat_name", "")
    snum = meta_data.get("sail_number", "")
    btype = meta_data.get("type", "")
    # Fallback, falls Meta leer (z.B. aus description parsen)
    if not btype:
        line1 = clean_text(config_data.get("description", ""))
    else:
        line1 = f"{bname} {snum} {btype}"

    # --- ZEILE 2 & 3: Segeldaten ---
    linked_id = config_data.get("linked_sail_internal_id")
    line2 = ""
    line3 = ""

    if linked_id:
        sail = None
        for s in sail_inventory:
            if s["internal_id"] == linked_id:
                sail = s
                break

        if sail:
            # Zeile 2: Maße (ohne Area, nur Geometrie)
            m = sail.get("measurements", {})
            meas_parts = []
            # Reihenfolge der Ausgabe
            keys = ["slu", "sle", "shw", "sfl", "jl", "lpg", "jh", "spl", "tps"]
            for k in keys:
                if k in m and m[k] > 0:
                    meas_parts.append(f"{k.upper()} {m[k]}")
            line2 = "  ".join(meas_parts)

            # Zeile 3: Name, Typ, Area, ID
            s_name = clean_text(sail.get("name", ""))
            s_area = sail.get("area", 0)
            s_id = sail.get("orc_sail_id", "")

            # Typ schön machen
            raw_type = sail.get("type", "")
            type_map = {"SYM": "Symmetric", "ASYM": "Asymmetric", "HEAD": "Headsail", "MAIN": "Mainsail"}
            type_str = type_map.get(raw_type, raw_type)

            # Zusammenbauen: "Symmetric (A2), Area 116.0 m² (ID: #123)"
            line3 = f"{type_str}"
            if s_name and s_name not in type_str:
                line3 += f" {s_name}"

            if s_area > 0:
                line3 += f", Area {s_area:.1f} m²"

            if s_id:
                line3 += f" (ID: {s_id})"
    else:
        # Falls Composite (Best Performance)
        line3 = "Composite / Hüllkurve (Best Performance)"

    return line1, line2, line3

# --- PLOTTER LOGIC ---

def plot_orc_pro_split(config_data, meta_data, sail_inventory):

    curves = config_data.get("data", [])
    if not curves: return

    curves.sort(key=lambda x: x["tws"])
    tws_values = [c["tws"] for c in curves]

    # Layout Setup
    fig = plt.figure(figsize=(14, 9))
    plt.subplots_adjust(top=0.84, wspace=0.15) # Platz für Header

    ax_left = fig.add_subplot(121, projection='polar')
    ax_right = fig.add_subplot(122, projection='polar')

    # --- ACHSEN ---
    # Links
    ax_left.set_theta_zero_location("N")
    ax_left.set_theta_direction(1)
    ax_left.set_thetamin(0)
    ax_left.set_thetamax(180)
    ax_left.set_title("AWA (Apparent)", fontweight='bold', size=11, pad=15, color='#333333')

    # Rechts
    ax_right.set_theta_zero_location("N")
    ax_right.set_theta_direction(-1)
    ax_right.set_thetamin(0)
    ax_right.set_thetamax(180)
    ax_right.set_title("TWA (True)", fontweight='bold', size=11, pad=15, color='#333333')

    # Grid
    ticks_deg = np.arange(0, 181, 15)
    ticks_rad = np.radians(ticks_deg)
    for ax in [ax_left, ax_right]:
        ax.set_xticks(ticks_rad)
        ax.tick_params(axis='x', labelsize=9, colors='#555555')
        ax.grid(color='#AAAAAA', linestyle=':', linewidth=0.5)

    # --- PLOTTING ---
    colors = cm.jet(np.linspace(0, 1, len(curves)))
    max_speed_global = 0

    for idx, curve_entry in enumerate(curves):
        c = colors[idx]
        tws_label = f"{curve_entry['tws']} kn"
        points = curve_entry["curve"]

        # AWA
        awa_raw = sorted([p for p in points if p.get("awa") is not None], key=lambda x: x["awa"])
        if awa_raw:
            rads, speeds = smooth_curve([p["awa"] for p in awa_raw], [p["bsp"] for p in awa_raw])
            ax_left.plot(rads, speeds, color=c, linewidth=2.0)
            max_speed_global = max(max_speed_global, max(speeds) if len(speeds)>0 else 0)

        # TWA
        twa_raw = sorted([p for p in points if p.get("twa") is not None], key=lambda x: x["twa"])
        if twa_raw:
            rads, speeds = smooth_curve([p["twa"] for p in twa_raw], [p["bsp"] for p in twa_raw])
            ax_right.plot(rads, speeds, color=c, linewidth=2.0, label=tws_label)
            max_speed_global = max(max_speed_global, max(speeds) if len(speeds)>0 else 0)

    # Limits
    limit = np.ceil(max_speed_global)
    ax_left.set_ylim(0, limit)
    ax_right.set_ylim(0, limit)
    ax_left.set_rlabel_position(135)
    ax_right.set_rlabel_position(45)

    # --- HEADER (NEU) ---
    line1, line2, line3 = generate_structured_header(config_data, meta_data, sail_inventory)

    # Zeile 1: Fett, Schwarz (Schiffsdaten)
    fig.text(0.5, 0.96, line1, ha='center', va='center', fontsize=13, fontweight='bold', color='black')

    # Zeile 2: Grau, Maße (SLU ... SLE ...)
    if line2:
        fig.text(0.5, 0.93, line2, ha='center', va='center', fontsize=11, color='#444444')

    # Zeile 3: Kursiv, Typ, Area, ID
    fig.text(0.5, 0.90, line3, ha='center', va='center', fontsize=10, style='italic', color='#666666')

    # Legende
    handles, labels = ax_right.get_legend_handles_labels()
    fig.legend(handles, labels, loc='lower center', ncol=len(labels), title="TWS (kn)",
               bbox_to_anchor=(0.5, 0.03), frameon=False, fontsize=10)

    plt.show()

# --- MAIN ---

def main(data_dir, json_filename):
    print(f"Lade Daten für Plots: {json_filename} ...")
    h = DriveHandler(data_dir, json_filename)
    if not h.exists():
        print("Datei nicht gefunden.")
        return

    with h as handler:
        with handler.open_read() as f:
            data = json.load(f)

    polars = data.get("polars", {}).get("configurations", {})
    sail_inv = data.get("sail_inventory", [])
    meta = data.get("meta", {})

    print(f"Erzeuge Profi-Plots für {len(polars)} Konfigurationen...")

    for key, config in polars.items():
        if config.get("data"):
            plot_orc_pro_split(config, meta, sail_inv)

    print("Fertig.")

if __name__ == "__main__":
    DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
    JSON_FILENAME = "ORC SpeedGuide TRUE GRIT 27.12.2025.json" # @param {type:"string"}

    main(DATA_DIR, JSON_FILENAME)

Ich komme zurück auf Deinen Vorschlag: "Was man mit diesen Daten noch machen könnte (Mehrwert):
Da wir nun die "DNA" des Bootes haben, können wir weit über das reine Plotten von Kurven hinausgehen. Hier sind drei konkrete Vorschläge für Erweiterungen deines Tools:
1. Intelligente Segel-Zuordnung ("Sail Chart Mapping")
Der Speed Guide gibt oft nur generische Kurven aus (z.B. "Asymmetric"). Mit der DXT-Datei können wir eine Logik bauen, die deine konkreten Segel auf diese Kurven mappt.
Beispiel: Wir berechnen das Verhältnis von Mittelbreite zu Unterliek ($AMG/SFL$) deiner Spis.
Nutzen: Das Tool kann dir im Plotter automatisch vorschlagen: "Bei 120° TWA ist laut Geometrie dein A3 (Code 0) das effizienteste Segel, ab 145° TWA passt dein A2 besser." Wir machen aus abstrakten Polaren konkrete Segel-Empfehlungen.
2. Präzise "Reef"-Simulation (Physik statt Raten)
Für deine Anforderung, eine 29qm Fock zu simulieren:
Wir nutzen das Righting Moment (RM) aus der DXT-Datei.
Wir berechnen das Krängungsmoment (Heeling Moment) der neuen Segelfläche basierend auf den Rigg-Daten ($I, J$).
Nutzen: Wir können mathematisch exakter bestimmen, bei wie viel Wind die 29qm Fock dieselbe Krängung erzeugt wie die 31qm Fock bei "Reef 0.93". Das macht dein "Reverse Engineering" deutlich präziser als nur über den Daumen zu peilen.
3. Visuelles Rigg-Overlay im DXF
Da du die Daten auf einen Plotter (Navigationssystem) exportieren willst:
Wir können aus den Rigg-Maßen ($P, E, I, J$) eine vereinfachte Draufsicht oder Seitenansicht des Segelplans als DXF-Layer erzeugen.
Nutzen: Du siehst auf dem Plotter nicht nur die Polarkurve, sondern hast eine visuelle Referenz der Segeldimensionen proportional zum Boot." Erläutete im Detail, wie Du vorgehen willst. Erzeuge keinen Code.

Das ist der richtige Ansatz. Bevor wir Code schreiben, müssen wir die **physikalische und logische Architektur** definieren. Wir wollen ja nicht einfach Daten kopieren, sondern sie *interpretieren*.

Hier ist mein detailliertes Konzept für die drei Erweiterungsstufen:

---

### 1. Intelligente Segel-Zuordnung ("Sail Chart Mapping")

**Das Problem:**
Die ORC-Polaren (Speed Guide) sind oft abstrakt ("Asymmetric"). Dein Inventar (DXT) ist konkret (z.B. "A2", "Code 0", "Jib Light"). Wir müssen die Brücke schlagen: *Welches konkrete Segel aus dem Inventar ist gemeint, wenn die Polare bei 120° TWA Höchstgeschwindigkeit zeigt?*

**Die Datenbasis (JSON):**

* **Polare:** Beste Kurve für "Asymmetric" (Winkel & Speed).
* **Inventar:** Maße der Spinnaker/Gennaker (`SLU`, `SLE`, `SHW`, `SFL`) und die ID.

**Der Algorithmus (Logik):**
Wir kategorisieren jedes Vorwindsegel im Inventar anhand seiner Geometrie. Der entscheidende Indikator ist das **Verhältnis von Mittelbreite zu Unterliek** ():

1. **Code 0 / Reacher (A3/A5):** Verhältnis ca. 55–75%. Diese Segel sind flach und für spitze Winkel (80°–130° TWA).
2. **Allround / Runner (A2/A4):** Verhältnis > 85–90%. Diese Segel sind bauchig und "projizieren" maximal nach Luv, also für tiefe Winkel (130°–170° TWA).
3. **Vorsegel (Jibs):** Wir unterteilen nach Fläche. Die größte Genua (Light) deckt 0–10 kn TWS ab, die kleinere (Heavy/Medium) übernimmt darüber.

**Das Vorgehen:**

* Wir scannen das Inventar und berechnen für jeden Spi das Verhältnis.
* Wir weisen jedem Segel einen **Winkel-Korridor** (TWA Range) und eine **Wind-Range** (TWS) zu (basierend auf Erfahrungswerten oder ORC-Standards).
* **Das Mapping:** Wenn wir den Plot erstellen, prüfen wir für jeden Punkt der Polarkurve: "Wir sind bei 140° TWA. Welches Segel im Inventar hat diesen Korridor?"
* **Ergebnis:** Statt einer einfachen Linie im Plot wird die Linie farblich codiert oder beschriftet: "Bis 135°: A3 (Code 0) benutzen -> Ab 135°: A2 setzen".

---

### 2. Präzise "Reef"-Simulation (Physik statt Raten)

**Das Problem:**
Du hast eine Polare für eine 31m² Fock, willst aber wissen, wie sich das Boot mit der 29m² Fock verhält. ORC simuliert "Reef" oft pauschal durch Reduktion der Hebelarme und Fläche. Wir machen das exakter über das **Aufrichtende Moment (Righting Moment - RM)**.

**Die Datenbasis (JSON):**

* `rm_default`: Das aufrichtende Moment des Bootes (z.B. bei 1 Grad oder als Kurve).
* Segelflächen:  (31m²) und  (29m²).
* Riggdaten:  (um den Angriffspunkt des Windes, den "Center of Effort" CE, zu schätzen).

**Der Algorithmus (Logik):**
Ein Segelboot krängt, wenn das Krängungsmoment () das Aufrichtende Moment () übersteigt.


1. **Hebelarm-Schätzung:** Da die neue Fock kleiner ist, wandert der Druckpunkt (CE) etwas nach unten. Wir approximieren die Höhe des Druckpunkts als ca.  der Vorliekslänge ( oder ).
2. **Momenten-Bilanz:**
Wir suchen die Windgeschwindigkeit , bei der die *kleine* Fock genau dasselbe Krängungsmoment erzeugt wie die *große* Fock bei  (dem Punkt, an dem du reffen müsstest).
3. **Die Formel:**
Da der Winddruck im Quadrat zur Windgeschwindigkeit steigt (), gilt vereinfacht:



*(Unter der Annahme, dass der Hebelarm ähnlich bleibt, was bei einem Wechsel von Genua auf Fock meist eine konservative Annahme ist).*

**Das Vorgehen:**

* Wir nehmen die Polarkurve der großen Fock.
* Wir "strecken" die TWS-Achse für die neue Fock. Das heißt: Die Performance, die die große Fock bei 15 Knoten bringt (bevor sie zu viel Krängung erzeugt), bringt die kleine Fock vielleicht erst bei 16,5 Knoten.
* **Ergebnis:** Eine neue Polartabelle, in der die Geschwindigkeiten der großen Fock zu höheren Windgeschwindigkeiten "verschoben" werden, korrigiert um den leichten Performance-Verlust durch weniger Fläche bei wenig Wind.

---

### 3. Visuelles Rigg-Overlay im DXF/SVG

**Das Problem:**
Zahlen () sind abstrakt. Auf dem Kartenplotter willst du sehen: "Wie weit reicht mein Spibaum (SPL) im Vergleich zum Rüssel (TPS)? Passt der Winkel?"

**Die Datenbasis (JSON):**

* `rig_configuration`: .

**Der Algorithmus (Logik):**
Wir definieren ein lokales Koordinatensystem. Der Nullpunkt  ist die Vorderkante des Mastes auf Deckshöhe.

1. **Draufsicht (Deck Plan):**
* Mast:
* Vorstag-Pütting (Forestay):
* Großsegel-Schothorn (Main Clew):
* Rüssel-Spitze (Bowsprit):
* Spibaum-Radius (Pole): Ein Kreisbogen um  mit Radius .


2. **Seitenansicht (Sail Plan) - optional:**
* Masthöhe:
* Spifall-Höhe:
* Vorsegeldreieck: Verbindung von  zu .



**Das Vorgehen:**

* Wir nutzen eine Python-Bibliothek (z.B. `matplotlib` für Preview oder `ezdxf` für echten Export).
* Wir zeichnen diese Punkte als Linien und Polygone.
* Wir generieren Layer: Ein Layer "Deck", ein Layer "Segel".

**Ergebnis:**
Eine DXF-Datei oder ein Plot im Notebook, der dir maßstabsgetreu zeigt:

* Wie viel länger ist der Rüssel () im Vergleich zum -Maß?
* Wie steht der Spibaum () im Verhältnis zum Rüssel? Das hilft extrem bei der Entscheidung "Symmetrisch vs. Asymmetrisch fahren".

---

**Mein Vorschlag für den nächsten Schritt:**

Soll ich mit **Punkt 1 (Intelligente Segel-Zuordnung)** beginnen? Das liefert den unmittelbarsten visuellen Mehrwert für deine bestehenden Plots ("Welches Segel fahre ich wann?"). Danach können wir die komplexere Physik (Punkt 2) angehen.

Vorab weitere Informationen zu den Jibs. Die Jib #60273 hat einen zweiten Anschlagpunkt für den segelhals. damit kann das vorliek um 1,25m verkürzt werden. Das Schothorn wandert auch um 1.25m nach oben.  Das Unterliek wird eingerollt. Die Fock mit der Nummer #62013 hat das gleiche System, hier kann das Vorliek um 1.06m verkürzt werden. Beschreibe nun, wie Du Punkt 1 umsetzen willst. Beziehe die beiden beschriebenen Segel und die Reffmaße in Deine Überlegungen mit ein. erzeuge keinen code.

Das ist eine extrem wertvolle Information. Dieses System (oft als "Reff-Focks" oder "Slab-Reefing Headsails" bezeichnet) ist taktisch entscheidend, da es den Wechsel auf ein kleineres Segel (Change) erspart und stattdessen eine schnelle Anpassung (Mode Shift) erlaubt.

Hier ist mein detailliertes Konzept, wie wir **Punkt 1 (Intelligente Segel-Zuordnung)** unter Berücksichtigung dieser speziellen Jibs umsetzen:

### Das Konzept: "Virtual Sail Inventory" & "Crossover-Logik"

Wir werden nicht nur die existierenden Datensätze mappen, sondern das Inventar intelligent "klonen".

#### Schritt 1: Erstellung virtueller Segel ("Ghost Sails")

Da Deine Jibs zwei physische Zustände haben, muss der Algorithmus sie wie **vier** verschiedene Segel behandeln. Wir berechnen die Eigenschaften der gerefften Zustände mathematisch, bevor wir ans Mappen gehen.

* **Jib #60273 (Basis):** Wir haben die volle Fläche und das volle Vorliek ().
* **Jib #60273 (Reff 1 - Virtuell):**
* Neues Vorliek .
* Neue Fläche : Wir approximieren die neue Fläche geometrisch. Da  (die Breite) beim Einrollen des Unterlieks oft annähernd gleich bleibt (oder sich das Profil nur unten verjüngt), skalieren wir die Fläche proportional zum Vorliek: .
* *Kennung im System:* "Jib #60273 (Reff)"


* **Jib #62013:** Das gleiche Verfahren mit .

#### Schritt 2: Die Entscheidungs-Matrix (Mapping-Logik)

Wir bauen eine Entscheidungslogik, die für jeden Punkt auf der Polarkurve (TWS & TWA) das beste Segel aus dem (nun erweiterten) Inventar wählt.

**A. Für Vorwind-Segel (Spis/Gennaker/Code 0)**
Hier bleibt die Logik geometrisch, wie vorher angedacht:

* Wir berechnen für alle Asyms/Syms im Inventar die "Bauchigkeit": Quotient aus  (Mittelbreite zu Unterliek).
* **Regel:**
* Quotient < 60-75%: **Reacher/Code 0** (für spitze Winkel, TWA 80°-120°).
* Quotient > 85%: **Runner/VMG-Spi** (für tiefe Winkel, TWA 135°-170°).


* Das Tool prüft den TWA der Polare und weist den passenden Spi zu.

**B. Für Amwind-Segel (Deine Jibs)**
Hier wird es spannend. Wir nutzen die **`REEF`**-Spalte aus Deiner Polartabelle (die wir ja jetzt im JSON haben).

* Der ORC Speed Guide gibt in der Spalte `REEF` einen Faktor an (z.B. `1.0` = volle Fläche, `0.9` = Fläche auf 90% reduzieren).
* **Der Abgleich:**
1. Wir berechnen den "Reff-Faktor" Deiner echten Segel:
* Faktor Jib #60273 Reff = .


2. Wir scannen die Polardaten.
3. **Szenario:** Bei 20 kn Wind sagt ORC: `REEF = 0.88` (benötigte Fläche 88%).
4. **Logik:** Das Tool schaut: "Habe ich ein Segel, das ca. 88% der maximalen Vorsegelfläche hat?" -> Ja, die gereffte Jib #60273.
5. **Empfehlung:** Das Tool markiert diesen Windbereich explizit mit "Jib #60273 (Reff)".



#### Schritt 3: Die Visualisierung (Crossover Chart)

Anstatt den Polarplot nur bunt zu machen, fügen wir eine neue Informationsebene hinzu:

1. **Im Polar-Plot (Hover/Text):**
Wenn wir die TWS-Kurven zeichnen, ändern wir den Linienstil oder fügen Labels hinzu, wenn ein Segelwechsel ansteht.
* Beispiel: Die 14kn-Kurve ist durchgezogen (Full Jib). Die 20kn-Kurve ist gestrichelt (Reff Jib).


2. **Neues Diagramm "Sail Crossover Chart":**
Das ist der eigentliche Mehrwert. Ein Balkendiagramm oder eine Matrix:
* **X-Achse:** TWS (Windgeschwindigkeit).
* **Y-Achse:** TWA (Windwinkel).
* **Inhalt:** Farbige Kacheln, die sagen: "In diesem Bereich: Jib #60273 Reff benutzen".



### Zusammenfassung des Vorgehens

1. Ich erweitere **Modul 1 (Extractor)** oder erstelle eine Hilfsfunktion in Modul 3, um die "virtuellen Reff-Segel" zu berechnen und temporär dem Inventar hinzuzufügen.
2. Ich implementiere die **Geometrie-Logik** für die Spis ().
3. Ich implementiere die **Reff-Logik** für die Jibs (Vergleich ORC `REEF`-Wert vs. Realer Flächenverlust durch Verkürzung).
4. Ich erzeuge einen **neuen Plot-Typen**: Das "Sail Chart", das Dir sagt, was Du wann hochziehen sollst.

Bist Du damit einverstanden? Dann würde ich als erstes die Logik zur Generierung der virtuellen Segel und die Crossover-Logik implementieren.

Ich möchte Modul 1 bis auf weiteres nicht anfassen. Erstelle eine Hilfsfunktion und fang an, zu coden

Verstanden. Wir lassen Modul 1 unberührt (die Datenbasis im JSON steht ja) und bauen eine **Logik-Schicht** dazwischen.

Hier ist der neue Code für eine Klasse namens `SailStrategist`.

Diese Klasse macht genau das, was wir besprochen haben:

1. Sie nimmt das Inventar entgegen.
2. Sie **erzeugt virtuelle Segel** für deine beiden speziellen Jibs (Reff-Zustand).
3. Sie **klassifiziert Spinnaker** anhand ihrer Geometrie ().
4. Sie bietet eine Funktion `get_recommendation()`, die für jeden Windpunkt das passende Segel ausspuckt.

Kopiere diesen Code in eine neue Zelle. Er ist modular aufgebaut und kann später einfach in den Plotter integriert werden.


### Erklärung zur Logik

1. **Virtuelle Segel:**
Ich habe die IDs `#60273` und `#62013` hartcodiert (da sie spezifisch für dein Boot sind) und erstelle Kopien mit angepasster Fläche und Vorliek. Diese werden als `HEAD_REEF` markiert.
2. **Spi-Klassifizierung:**
Ich berechne `SHW / SFL`.
* Ist das Segel "schlank" (< 75%), ist es ein **Reacher** (für spitze Kurse).
* Ist es "bauchig" (> 75%), ist es ein **Runner** (für tiefe Kurse).


3. **Die Empfehlungs-Engine (`get_recommendation`):**
* **Am Wind:** Sie prüft den `reef_factor` aus der Polartabelle.
* Ist `reef` nahe 1.0 -> Volle Fock.
* Ist `reef` kleiner (z.B. 0.88) -> Sie sucht das Segel, dessen Fläche am ehesten 88% entspricht. Das wird dann deine virtuelle Reff-Fock sein.


* **Vor Wind:** Sie prüft den Winkel (TWA).
* < 130° -> Suche Reacher.
* > 130° -> Suche Runner.


* Starkwind (>22kn) -> Nimm den kleinsten verfügbaren Spi der passenden Klasse (Heavy).





Führe diesen Code bitte einmal aus (du musst ihn natürlich mit Daten füttern, z.B. indem du am Ende `test_sail_mapping(data)` aufrufst, nachdem du das JSON geladen hast).

Klappt die Erzeugung der virtuellen Segel wie gewünscht?

In [ ]:
# @title Modul Test: Sail Strategist (Logik-Test mit echten Daten)
import sys
import os
import json
import copy

# --- 1. DRIVE HANDLER (Kopie zum Laden der Datei) ---
class DriveHandler:
    COLAB_ROOT = '/content/drive'

    def __init__(self, directory=None, filename=None):
        self.filepath = None
        self._mounted = False
        if directory and filename:
            self.set_full_path(directory, filename)

    def _is_colab(self):
        return 'google.colab' in sys.modules

    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True

    def set_full_path(self, directory, filename):
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath

    def exists(self): return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

# --- 2. SAIL STRATEGIST (Die neue Logik) ---
class SailStrategist:
    def __init__(self, sail_inventory):
        # Wir arbeiten auf einer Kopie
        self.inventory = copy.deepcopy(sail_inventory)
        self.max_jib_area = 0

        # Initialisierung
        self._analyze_inventory()
        self._generate_virtual_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        """Findet Basiswerte wie maximale Vorsegelfläche."""
        for s in self.inventory:
            if s.get("type") == "HEAD":
                curr_area = s.get("area", 0)
                if curr_area > self.max_jib_area:
                    self.max_jib_area = curr_area

    def _generate_virtual_reefs(self):
        """Erstellt virtuelle 'Reff-Versionen'."""
        # Konfiguration: {ORC_ID: Vorliekskürzung_in_Metern}
        reff_config = {
            "#60273": 1.25,
            "#62013": 1.06
        }

        new_sails = []
        print(f"   [Strategist] Prüfe auf Reff-Optionen für IDs: {list(reff_config.keys())}...")

        for s in self.inventory:
            orc_id = s.get("orc_sail_id")

            if orc_id in reff_config:
                reduction = reff_config[orc_id]

                # Originalmaße holen
                measurements = s.get("measurements", {})
                jl = measurements.get("jl", 0)
                if jl == 0:
                    jl = float(s.get("attributes", {}).get("JIBLUFF", 0))

                if jl > 0:
                    new_jl = jl - reduction
                    ratio = new_jl / jl

                    old_area = s.get("area", 0)
                    new_area = old_area * ratio

                    # Erstelle das virtuelle Segel
                    virtual_sail = copy.deepcopy(s)
                    virtual_sail["internal_id"] = f"{s['internal_id']}_REEF"
                    virtual_sail["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    virtual_sail["area"] = new_area
                    virtual_sail["is_virtual"] = True
                    virtual_sail["measurements"]["jl"] = new_jl
                    virtual_sail["strategy_type"] = "HEAD_REEF"

                    new_sails.append(virtual_sail)
                    print(f"   [Strategist] -> Virtuelles Segel erstellt: {virtual_sail['name']} ({new_area:.1f} m²)")

        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        """Klassifiziert Vorwindsegel in REACHER und RUNNER."""
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = m.get("shw", 0)
                sfl = m.get("sfl", 0)

                if shw == 0: shw = float(s.get("attributes", {}).get("SMG", 0))
                if sfl == 0: sfl = float(s.get("attributes", {}).get("SFL", 0))

                if sfl > 0:
                    ratio = shw / sfl
                    s["shape_ratio"] = ratio
                    # Regel: < 75% -> Reacher, > 75% -> Runner
                    if ratio < 0.75:
                        s["strategy_type"] = "REACHER"
                    else:
                        s["strategy_type"] = "RUNNER"
                else:
                    s["strategy_type"] = "UNKNOWN_SPI"

    def get_recommendation(self, twa, tws, reef_factor=1.0, config_type="optimal"):
        """Entscheidet, welches Segel passt."""

        # UPWIND / HEADSAIL
        if abs(twa) < 60 or "headsail" in config_type.lower():
            target_area = self.max_jib_area * reef_factor

            best_sail = None
            min_diff = float('inf')

            candidates = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]

            for s in candidates:
                diff = abs(s.get("area", 0) - target_area)
                if diff < min_diff:
                    min_diff = diff
                    best_sail = s

            # Entscheidung: Reff oder Voll?
            if best_sail:
                # Toleranz: Wenn fast voll (z.B. > 98%), bevorzuge das echte Segel
                if reef_factor > 0.98 and not best_sail.get("is_virtual"):
                     return best_sail
                return best_sail

        # DOWNWIND / SPI
        elif abs(twa) > 60:
            needed_type = "RUNNER" if abs(twa) > 130 else "REACHER"
            candidates = [s for s in self.inventory if s.get("strategy_type") == needed_type]

            if not candidates:
                candidates = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"]]

            # Sortiere nach Fläche (Groß vor Klein)
            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                # Simpler Heavy-Weather Switch bei > 22kn
                if tws > 22 and len(candidates) > 1:
                    return candidates[-1]
                return candidates[0]

        return None

# --- 3. MAIN EXECUTION (Verbindet alles) ---
def main(data_dir, json_filename):
    print(f"1. Lade JSON Daten: {json_filename} ...")
    h = DriveHandler(data_dir, json_filename)

    if not h.exists():
        print("FEHLER: Datei nicht gefunden.")
        return

    with h as handler:
        with handler.open_read() as f:
            json_data = json.load(f)

    print("   -> Daten geladen.")

    # Inventar holen
    inventory = json_data.get("sail_inventory", [])

    # Strategist starten
    print("\n2. Initialisiere Sail Strategist...")
    strategist = SailStrategist(inventory)

    # Ausgabe der Klassifizierung
    print("\n3. Klassifizierungs-Ergebnis:")
    print("-" * 80)
    print(f"{'SEGEL NAME':<40} | {'TYP':<10} | {'STRATEGIE':<10} | RATIO")
    print("-" * 80)

    for s in strategist.inventory:
        st = s.get("strategy_type", "-")
        ratio = s.get("shape_ratio", 0)
        ratio_str = f"{ratio:.2f}" if ratio > 0 else "-"
        virt = " [VIRT]" if s.get("is_virtual") else ""

        # Nur interessante Segel drucken
        if st != "-":
            print(f"{s.get('name')[:38]:<40} | {s.get('type'):<10} | {st:<10} | {ratio_str} {virt}")

    # Test Szenarien
    print("\n4. Empfehlungs-Check (Simulation):")
    print("-" * 80)
    scenarios = [
        {"tws": 10, "twa": 40, "reef": 1.0, "desc": "Leichtwind Kreuz"},
        {"tws": 25, "twa": 42, "reef": 0.85, "desc": "Starkwind Kreuz (Reff!)"},
        {"tws": 12, "twa": 100, "reef": 1.0, "desc": "Halbwind (Code 0?)"},
        {"tws": 15, "twa": 160, "reef": 1.0, "desc": "Vorwind tief (Runner)"}
    ]

    for scen in scenarios:
        rec = strategist.get_recommendation(scen["twa"], scen["tws"], scen["reef"])
        s_name = rec.get("name") if rec else "---"
        print(f"Szenario: {scen['desc']:<25} -> Nimm: {s_name}")

if __name__ == "__main__":
    DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
    JSON_FILENAME = "ORC SpeedGuide TRUE GRIT 27.12.2025.json" # @param {type:"string"}

    main(DATA_DIR, JSON_FILENAME)

1. Lade JSON Daten: ORC SpeedGuide TRUE GRIT 27.12.2025.json ...
   -> Daten geladen.

2. Initialisiere Sail Strategist...
   [Strategist] Prüfe auf Reff-Optionen für IDs: ['#60273', '#62013']...
   [Strategist] -> Virtuelles Segel erstellt: 27.4.2019 Blk-J2-Zip:1.25-29.34 sqm (Reff -1.25m) (26.7 m²)
   [Strategist] -> Virtuelles Segel erstellt: 25.03.2020 Hvy-J3-Zip:1.06-27.58sqm (Reff -1.06m) (25.0 m²)

3. Klassifizierungs-Ergebnis:
--------------------------------------------------------------------------------
SEGEL NAME                               | TYP        | STRATEGIE  | RATIO
--------------------------------------------------------------------------------
18.03.2017 - White - 88.85sqm            | SYM        | UNKNOWN_SPI | -
26.04.2019 Blue - 114.66sqm              | SYM        | UNKNOWN_SPI | -
24.03.2020 Blue - 115.00sqm              | SYM        | UNKNOWN_SPI | -
20.11.2025 A2 - 116.03sqm                | ASYM       | UNKNOWN_SPI | -
24.03.2020 A3-5 Red - 87.25sqm           | ASYM       | UNKNOWN_SPI | -
27.4.2019 Blk-J2-Zip:1.25-29.34 sqm (R   | HEAD       | HEAD_REEF  | -  [VIRT]
25.03.2020 Hvy-J3-Zip:1.06-27.58sqm (R   | HEAD       | HEAD_REEF  | -  [VIRT]

4. Empfehlungs-Check (Simulation):
--------------------------------------------------------------------------------
Szenario: Leichtwind Kreuz          -> Nimm: 24.03.2017 Blk-J1-NoZip-31.68sqm
Szenario: Starkwind Kreuz (Reff!)   -> Nimm: 27.4.2019 Blk-J2-Zip:1.25-29.34 sqm (Reff -1.25m)
Szenario: Halbwind (Code 0?)        -> Nimm: 20.11.2025 A2 - 116.03sqm
Szenario: Vorwind tief (Runner)     -> Nimm: 20.11.2025 A2 - 116.03sqm

hier sind die segeldaten als json. ich bin noch bei den überlegungen, wie man die verkürzung des vorlieks modellieren sollte.

Based on the provided JSON data and your initial thoughts on sail modeling, specifically regarding the virtual reefing of jibs, here is a detailed breakdown of how to approach the "Intelligent Sail Mapping" (Sail Chart Mapping) and precise reef simulation.

### 1. Modeling Virtual Jibs (Reef Simulation)

The core idea is to treat the reefed state of a jib as a distinct "virtual sail." This allows the mapping algorithm to select it just like any physical sail.

* **Logic:** When a jib is reefed (shortening the luff), its area decreases, and its center of effort shifts.
* **New Luff Length ():**  (e.g., ).
* **New Area ():** A proportional reduction is a robust approximation. Assuming the shape (LPG) remains largely constant or scales linearly:


* *Refinement:* If the foot is rolled significantly, the area reduction might be slightly non-linear, but for a mapping tool, linear scaling based on luff length is usually sufficient and conservative.


* **Identifier:** Create a new internal ID, e.g., `HEAD_5_REEF`.


* **Application to Your Jibs:**
* **Jib #60273 (`HEAD_5`):**
* Original Area: ~29.34 m²
* Reduction: 1.25 m
* Original JL: 13.65 m (from attributes `JIBLUFF`)
* Reefed Area


* **Jib #62013 (`HEAD_6`):**
* Original Area: ~27.58 m²
* Reduction: 1.06 m
* Original JL: 11.51 m (from attributes `JIBLUFF`)
* Reefed Area





### 2. Spinnaker Classification Logic ()

To automate the suggestion between an A2 (Runner) and an A3 (Reacher), we use the aspect ratio of the spinnaker.

* **Data Extraction:**
* Get `SHW` (or `SMG`/`AMG`) and `SFL` (or `SF`/`ASF`) from the JSON `measurements` or `attributes`.


* **Calculation:** .
* **Thresholds (Standard ORC/Design Guidance):**
* **Reacher (Code 0/A3):** Ratio < 75% (0.75). These sails are flatter and meant for tighter angles (reaching).
* **Runner (A2/A4):** Ratio ≥ 75% (often > 85-90%). These sails are fuller and meant for deep downwind angles.


* **Application to Your Spinnakers:**
* **`ASYM_10` (#180387):** `AMG` 8.67 / `ASF` 8.67 = **1.0 (100%)**. -> **Definite Runner**.
* **`ASYM_11` (#62037):** `AMG` 6.7 / `ASF` 7.62 = **0.88 (88%)**. -> **This is interesting. It's technically a runner by strict definition, but significantly flatter than the A2**. It acts as a "hybrid" or heavy-air runner/reacher. The tool might classify this as a "Reacher" relative to the A2 if we adjust the threshold or simply compare the two.
* **`SYM_9` (#62068):** `SMG` 8.96 / `SF` 8.25 = **1.08**. -> **Runner** (Symmetric spinnakers are almost always runners).



### 3. The Mapping Algorithm (The "Strategist")

This is the logic flow for the `SailStrategist` class:

1. **Input:** Current Wind Conditions () and the Target Polar Point (Target Speed, Reef Factor from JSON).
2. **Step 1: Determine Mode (Upwind vs. Downwind)**
* If  or Polar Config is "Headsail" -> **Upwind Mode**.
* If  -> **Downwind Mode**.


3. **Step 2: Upwind Selection (Headsail Matching)**
* Look at the `reef` value in the polar data for that TWS.
* If `reef` : Recommend the largest Jib (`HEAD_4` or `HEAD_5`).
* If `reef` : Calculate the "Ideal Area": .


* **Compare:** Find the sail (physical or virtual) whose area is closest to this Ideal Area.
* *Example:* If TWS 20kn calls for `reef` 0.85 (implied area ~27m²), the algorithm sees `HEAD_5_REEF` (~26.6m²) is a better match than `HEAD_4` (31.7m²).




4. **Step 3: Downwind Selection (Spinnaker Matching)**
* Check TWA.
* If : Prefer **Reacher** class sails.
* If : Prefer **Runner** class sails.
* *Tie-breaker:* If multiple sails fit the class, check TWS.
* Light wind (< 10kn): Largest area.
* Heavy wind (> 20kn): Smaller area or heavier material (if available in attributes).





### 4. Implementation Plan

This logic will be encapsulated in the Python `SailStrategist` class. It essentially acts as a filter:
`Polar Point -> Requirements (Area, Shape) -> Inventory Scan -> Best Match`.

This approach moves beyond simple data visualization to actionable tactical advice, directly answering "What sail should I have up right now?" based on the physics of your specific boat and inventory.

Hier ist die detaillierte Erläuterung des Algorithmus `get_recommendation` aus der Klasse `SailStrategist`.

Der Algorithmus fungiert als **Entscheidungsbaum**, der basierend auf der aktuellen Situation (Wind & Winkel) und den Vorgaben aus der ORC-Polare das beste Segel aus deinem (erweiterten) Inventar auswählt.

### 1. Die Inputs (Eingabewerte)

Die Funktion wird mit folgenden Parametern aufgerufen:

* **`twa` (True Wind Angle):** Der wahre Windwinkel (z.B. 40° für Kreuz, 150° für Vorwind).
* **`tws` (True Wind Speed):** Die wahre Windgeschwindigkeit in Knoten.
* **`reef_factor` (optional):** Ein Wert aus der ORC-Polartabelle (Spalte `REEF`).
* `1.0` bedeutet: Volle Segelfläche nutzen.
* `0.90` bedeutet: Die Fläche sollte auf 90% reduziert werden (Reffen).


* **`config_type` (optional):** Kontext, um z.B. explizit nur Vorsegel zu suchen (z.B. "headsail").

---

### 2. Der Ablauf (Wie er die Empfehlung findet)

Der Algorithmus unterscheidet strikt zwischen zwei Modi: **Upwind (Am Wind)** und **Downwind (Vor Wind)**.

#### A. Upwind-Modus (Jib-Auswahl)

*Wann aktiv?* Wenn `twa < 60°` ist oder der `config_type` "headsail" enthält.

1. **Ziel-Fläche berechnen:**
Er nimmt deine maximal verfügbare Vorsegelfläche (aus dem Inventar ermittelt, z.B. 31,68 m²) und multipliziert sie mit dem `reef_factor`.
* *Beispiel:* 31,68 m² * 0,90 (Reff-Faktor) = **28,51 m² Ziel-Fläche**.


2. **Kandidaten filtern:**
Er betrachtet alle Segel vom Typ `HEAD` (deine normalen Focks) UND `HEAD_REEF` (die virtuellen Reff-Segel, die wir vorher generiert haben).
3. **Bestes Match suchen:**
Er vergleicht die Flächen aller Kandidaten mit der Ziel-Fläche. Das Segel mit der geringsten Abweichung gewinnt.
* *Im Beispiel:* Deine virtuelle "Reff-Fock #60273" hat ca. 26,6 m². Deine volle "Jib #4" hat 31,7 m². Die Reff-Fock ist näher an den geforderten 28,5 m² -> **Empfehlung: Reff-Fock.**


4. **Realitäts-Check (Toleranz):**
Wenn der ORC-Reff-Faktor fast 1 ist (z.B. > 0.98), zwingt der Algorithmus die Auswahl auf ein *echtes* Segel. Das verhindert, dass er wegen minimaler mathematischer Abweichungen grundlos ein virtuelles Reff-Segel vorschlägt.

#### B. Downwind-Modus (Spi-Auswahl)

*Wann aktiv?* Wenn `twa >= 60°` ist.

1. **Typ-Bestimmung (Form):**
Er schaut auf den Winkel (`twa`):
* **`twa > 130°` (Tief):** Er sucht nach einem **RUNNER**. (Das sind Spis, die wir vorher als "bauchig" klassifiziert haben, Ratio > 0.75).
* **`twa <= 130°` (Spitz):** Er sucht nach einem **REACHER**. (Das sind flache Spis/Code 0, Ratio < 0.75).


2. **Kandidaten wählen:**
Er holt alle Spis aus dem Inventar, die diesen `strategy_type` haben.
* *Fallback:* Findet er keinen passenden Typ (z.B. kein Reacher im Inventar), nimmt er *alle* verfügbaren Spis als Reserve.


3. **Größen-Wahl (Heavy Weather Logic):**
Die Kandidaten werden nach Größe sortiert (größtes zuerst).
* **Normalwind (< 22 kn):** Er empfiehlt den **größten** passenden Spi (maximale Power).
* **Starkwind (> 22 kn):** Wenn mehr als ein Spi zur Wahl steht, empfiehlt er den **kleinsten** (bzw. zweitgrößten) Spi, um das Material zu schonen und Kontrollverlust zu vermeiden.



### Zusammenfassung

Der Algorithmus übersetzt die abstrakten ORC-Zahlen ("Fahre 90% Fläche") und geometrischen Regeln ("Ab 130 Grad braucht man einen Runner") in konkrete Inventar-IDs: **"Nimm jetzt die Jib #60273 im Reff-Zustand"** oder **"Nimm den A2 Runner"**.

ich hätte das gerne anders. für mich stellt sich das problem so: ich habe einen vorgegebenen kurs. TWD und TWS geben mir meine Sensoren. Frage an mich: welches Segel soll ich nehmen, OHNE in die Tabellen schauen zu müssen. darüber hinaus würde ich gerne wissen wollen, welche krängung das vpp vorhersagt und wie ich die segel trimmen muss, damit ich top-speed erreiche.

Das ist ein entscheidender Perspektivwechsel: Weg von der nachträglichen Analyse (Was wäre theoretisch möglich gewesen?) hin zur taktischen Entscheidungshilfe in Echtzeit (Was mache ich jetzt?).

Das ist genau der Punkt, an dem VPP-Daten ihren wahren Wert zeigen. Hier ist das Konzept für *Modul 4: Der Taktische Berater*.

Das Skript arbeitet nun wie ein Bordcomputer:

* Eingabe (Sensoren-Simulation):

Du gibst Kompasskurs (HDG), Windrichtung (TWD) und Windstärke (TWS) ein.

Das Tool berechnet daraus sofort den TWA (Wahren Windwinkel), also woher der Wind relativ zum Bug kommt.

Der VPP-Lookup (Der "Blick in die Tabelle" für dich):

Da du nicht in Tabellen schauen willst, macht das Tool das mathematisch.

Es sucht im JSON die "Optimal"-Kurve (Best Performance).

Es interpoliert exakt für deine Windstärke. (Wenn du 13 kn Wind hast, mittelt es zwischen den Daten von 12 kn und 14 kn).

Die Ausgabe (Actionable Intelligence):

Segel-Empfehlung: Es nutzt die Logik aus dem SailStrategist (inklusive deiner Reff-Focks), um dir das eine, richtige Segel zu nennen.

Trim-Ziele: Es sagt dir, welche Krängung (Heel) das Boot haben sollte. Wenn du weniger hast, bist du zu langsam. Wenn du mehr hast, musst du depowern.

Depower-Check: Es zeigt dir die Parameter Reef (Fläche reduzieren) und Flat (Profil flach ziehen). Wenn FLAT < 1.0 ist, heißt das: "Achterstag dicht, Unterliek dicht, Traveler runter!"

in der ersten version des beraters hattest du eine eingabe-maske vorgesehen. die hätte ich gerne wieder. Dann: die Segelempfehlung hätte ich gerne deutlich ausführlicher. Welche Segel sind 100% (je für Job und Main), welche werte schlägt das vpp vor (reef, flat und heel) , welches segel soll ich nehmen, soll ich es reffen, wie stark (beim Main, 1. und 2. Reff) . Hinweis: mein Main hat 2 Reffs. beim ersten Reff geh davon aus, dass das vorliek um 1.40 verkürzt wird, bei 2. Reff  wird es um 2.8m verkürzt. da ich die genauen maße nicht habe, mach diese werte konfigurierbar

In [ ]:
# @title Modul 4: Der Taktische Berater (Version 10 - Interpolation Fix)
import sys
import os
import json
import copy
import numpy as np

# --- 1. INFRASTRUKTUR ---
class DriveHandler:
    COLAB_ROOT = '/content/drive'
    def __init__(self, directory=None, filename=None):
        self.filepath = None
        self._mounted = False
        if directory and filename: self.set_full_path(directory, filename)
    def _is_colab(self): return 'google.colab' in sys.modules
    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True
    def set_full_path(self, directory, filename):
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath
    def exists(self): return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

# --- 2. VPP ENGINE (KORRIGIERT) ---
class VppTacticalEngine:
    def __init__(self, polars_data):
        self.polars = polars_data
        self.debug_bounds = None # Speicher für Debug-Info

    def _interpolate_curve(self, curve_data, tws, twa):
        if not curve_data: return None

        # Sortiere Kurven nach Windstärke
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])

        # Finde untere und obere Schranke (BUG FIX)
        # 1. Alle Kurven <= TWS sammeln
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        # 2. Alle Kurven >= TWS sammeln
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]

        # Wähle die richtigen Grenzen
        if not lower_candidates:
            lower = sorted_curves[0] # Wind ist kleiner als kleinste Kurve
        else:
            lower = lower_candidates[-1] # Nimm die HÖCHSTE der unteren (z.B. 12 bei 13)

        if not upper_candidates:
            upper = sorted_curves[-1] # Wind ist größer als größte Kurve
        else:
            upper = upper_candidates[0] # Nimm die NIEDRIGSTE der oberen (z.B. 14 bei 13)

        # Debug Info speichern (nur für Optimal Curve interessant)
        self.debug_bounds = (lower["tws"], upper["tws"])

        # Interpolations-Faktor (0..1)
        if lower["tws"] == upper["tws"]:
            tws_fac = 0
        else:
            tws_fac = (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        # TWA Interpolation
        def get_vals_at_twa(curve_points, t_twa):
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res

        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))

        # Werte mischen
        final = {}
        for k in vals_low:
            final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac

        return final

    def get_targets(self, tws, twa):
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws, twa):
        speeds = {}
        # Headsail
        h_data = self.polars.get("headsail", {}).get("data", [])
        h_res = self._interpolate_curve(h_data, tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0
        # Asym
        a_data = self.polars.get("asymmetric", {}).get("data", [])
        if not a_data: a_data = self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0
        # Sym
        s_data = self.polars.get("symmetric", {}).get("data", [])
        s_res = self._interpolate_curve(s_data, tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0
        return speeds

# --- 3. LOGIK (SailStrategist) ---
class SailStrategist:
    def __init__(self, sail_inventory, rig_config, main_reef_drops):
        self.inventory = copy.deepcopy(sail_inventory)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops
        self.max_jib_area = 0
        self.max_main_area = 0
        self.max_spi_area = 0
        self.active_main = None
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        for s in self.inventory:
            if s.get("type") == "HEAD":
                self.max_jib_area = max(self.max_jib_area, s.get("area", 0))
            if s.get("type") in ["SYM", "ASYM"]:
                self.max_spi_area = max(self.max_spi_area, s.get("area", 0))
            if s.get("type") == "MAIN":
                curr = s.get("area", 0)
                if curr > self.max_main_area: self.max_main_area = curr
                if s.get("attributes", {}).get("Active") == "1": self.active_main = s
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)

                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed = reduction * (lpg + width_at_cut) / 2.0
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = s.get("area", 0) - removed
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        if not self.active_main or self.rig_p == 0: return
        m_area = self.active_main.get("area", 0)
        new_sails = []
        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0
            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa, tws, comparison_speeds, reef_factor):
        abs_twa = abs(twa)
        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False
        if abs_twa > 60 and max_spi_speed > (speed_head + 0.2):
            mode = "DOWNWIND"
            use_spi = True

        # Main Selection
        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]
        target_main = self.max_main_area * reef_factor
        best_main = min(mains, key=lambda m: abs(m.get("area", 0) - target_main))

        best_front = None
        if not use_spi:
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor
            best_front = min(jibs, key=lambda j: abs(j.get("area", 0) - target_jib))
            if reef_factor > 0.98:
                if best_main.get("is_virtual"): best_main = self.active_main
                if best_front.get("is_virtual"):
                    pid = best_front["internal_id"].split("_REEF")[0]
                    best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)
        else:
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"

            candidates = []
            if needed_type == "SYM": candidates = [s for s in self.inventory if s.get("type") == "SYM"]
            else: candidates = [s for s in self.inventory if s.get("strategy_type") == needed_type]
            if not candidates: candidates = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"]]

            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                if tws > 22 and len(candidates) > 1: best_front = candidates[-1]
                else: best_front = candidates[0]

        return {'main': best_main, 'head': best_front, 'mode': mode, 'speed_potential': max_spi_speed if use_spi else speed_head}

# --- 4. OUTPUT ---
def run_tactical_advice(hdg, twd, tws, main_drops, data_dir, json_filename):
    h = DriveHandler(data_dir, json_filename)
    if not h.exists(): return
    with h as handler:
        with handler.open_read() as f: data = json.load(f)

    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    diff = (twd - hdg) % 360
    twa = 360 - diff if diff > 180 else diff
    side = "Backbord-Bug" if diff > 180 else "Steuerbord-Bug"

    targets = engine.get_targets(tws, twa)
    comp_speeds = engine.compare_configurations(tws, twa)

    if not targets: return
    rec = strategist.determine_best_config(twa, tws, comp_speeds, targets['reef'])

    print("\n" + "#"*75)
    print(f"   TAKTIK-COMPUTER: {data['meta']['boat_name'].upper()}")
    print(f"   VPP: {data['data_section']['dxtName']}")
    print("#"*75)

    print(f"\n[1] SITUATION")
    print(f"    TWS: {tws:.1f} kn  |  TWA: {twa:.1f}° ({side})")
    print(f"    (Interpoliert aus VPP-Daten: {engine.debug_bounds[0]} kn - {engine.debug_bounds[1]} kn)")
    print("-" * 75)

    print(f"[2] VPP ZIELVORGABEN (Optimal Curve)")
    print(f"    Target Speed (BSP): {targets['bsp']:.2f} kn")
    print(f"    Target AWA:         {targets['awa']:.1f}°")
    print(f"    Target AWS:         {targets['aws']:.1f} kn")
    print(f"    Target HEEL:        {targets['heel']:.1f}°")
    print(f"    ------------------------------------")
    print(f"    REEF Faktor:        {targets['reef']:.3f}")
    print(f"    FLAT Faktor:        {targets['flat']:.3f}")
    print("-" * 75)

    print(f"[3] SEGEL-ENTSCHEIDUNG (Action)")
    if rec:
        m = rec['main']
        h = rec['head']

        def print_sail_stats(label, sail):
            if not sail:
                print(f"    >>> {label}:  KEIN SEGEL")
                return 0
            name = sail['name']
            curr_area = sail.get('area', 0)
            orig_area = sail.get('parent_area', curr_area)
            if not sail.get('is_virtual') and 'parent_area' not in sail: orig_area = curr_area
            state = "GEREFFT" if sail.get('is_virtual') else "UNGEREFFT"
            print(f"    >>> {label}:  {name}")
            print(f"                Status:    {state}")
            print(f"                Basis:     {orig_area:.2f} m²")
            print(f"                Effektiv:  {curr_area:.2f} m²")
            return curr_area

        area_m = print_sail_stats("MAIN ", m)
        area_h = print_sail_stats("FRONT", h)
        total_eff = area_m + area_h

        print(f"    ------------------------------------")
        print(f"    >>> SUMME:  {total_eff:.2f} m² (Effektive Gesamtfläche)")

        if rec['mode'] == "UPWIND":
            base_area = strategist.max_main_area + strategist.max_jib_area
        else:
            base_area = strategist.max_main_area + strategist.max_spi_area

        vpp_target_area = base_area * targets['reef']
        delta_area = total_eff - vpp_target_area

        fit_msg = "PERFEKT"
        if delta_area > 5: fit_msg = "OVERPOWERED"
        if delta_area < -5: fit_msg = "UNDERPOWERED"

        print(f"\n    [Flächen-Vergleich]")
        print(f"    VPP-Soll ({rec['mode']}): {vpp_target_area:.2f} m²")
        print(f"    Abweichung:         {delta_area:+.2f} m² -> {fit_msg}")

        calc_speed = rec['speed_potential']
        opt_speed = targets['bsp']
        diff_speed = calc_speed - opt_speed

        print(f"\n    [Performance Check]")
        print(f"    Speed Potential: {calc_speed:.2f} kn")
        if diff_speed < -0.1:
            print(f"    => Warnung: {abs(diff_speed):.2f} kn langsamer als Optimum.")
        else:
            print(f"    => Config entspricht Optimum.")

    print("#"*75 + "\n")

# --- 5. EINGABE ---
COURSE_HDG = 45 # @param {type:"number"}
WIND_TWD = 358 # @param {type:"number"}
WIND_TWS = 22 # @param {type:"number"}
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_tactical_advice(COURSE_HDG, WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME)

In [ ]:
# @title Modul 4: Der Taktische Berater (Version 11 - Documented & Typed)
"""
================================================================================
MODUL 4: TAKTISCHER BERATER (Tactical Advisor)
================================================================================

BESCHREIBUNG:
Dieses Modul fungiert als "Bordcomputer". Es simuliert eine Echtzeit-Entscheidungshilfe
basierend auf aktuellen Sensordaten (Wind, Kurs) und den statischen Schiffsdaten (VPP, Rigg).
Es beantwortet die Fragen: "Welches Segel?", "Welches Reff?", "Welcher Trimm?".

FUNKTIONEN:
1. Interpolation: Berechnet exakte VPP-Zielwerte (Speed, Heel) für krumme Windwerte (z.B. 13.5 kn).
2. Segel-Strategie: Wählt die optimale Segelkombination basierend auf VPP-Vorgaben und Geometrie.
3. Reff-Simulation: Berechnet die effektive Fläche gereffter Segel (Trapez-Formel).
4. Performance-Check: Vergleicht das theoretische Potenzial der gewählten Segel mit dem Optimum.

INPUT DATEN (Argumente):
- hdg (float): Kompasskurs des Bootes (Heading, 0-360°).
- twd (float): Wahre Windrichtung (True Wind Direction, 0-360°).
- tws (float): Wahre Windgeschwindigkeit (True Wind Speed in Knoten).
- main_drops (Tuple[float, float]): Die Tiefe der Reffs im Großsegel in Metern (Reff 1, Reff 2).
- json_data (Dict): Das geladene ORC-JSON-File.

DATENSTRUKTUREN (Wichtigste Variablen):
- inventory (List[Dict]): Liste aller Segel. Ein Segel ist ein Dictionary mit Keys:
  {'name': str, 'area': float, 'measurements': Dict, 'strategy_type': str, ...}
- polars (Dict): Die VPP-Daten. Struktur: {'optimal': {'data': [...]}, 'headsail': ...}
- curve_data (List[Dict]): Eine Polarkurve für verschiedene Windstärken (TWS).
- comparison_speeds (Dict[str, float]): Speed-Vergleich {'HEAD': 7.2, 'ASYM': 8.1, ...}

TYPE HINTS:
Wir nutzen das `typing` Modul für statische Code-Analyse und bessere Lesbarkeit.
================================================================================
"""

import sys
import os
import json
import copy
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR ---

class DriveHandler:
    """
    Verwaltet den Zugriff auf Dateien, egal ob lokal oder in Google Colab (Google Drive).
    Nutzt das Context Manager Pattern (with ... as ...).
    """
    COLAB_ROOT = '/content/drive'

    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename:
            self.set_full_path(directory, filename)

    def _is_colab(self) -> bool:
        """Prüft, ob das Skript in einer Google Colab Umgebung läuft."""
        return 'google.colab' in sys.modules

    def _mount(self):
        """Mountet Google Drive nur bei Bedarf und nur einmal."""
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True

    def set_full_path(self, directory: str, filename: str) -> str:
        """Baut den korrekten Pfad zusammen (Colab vs. Lokal)."""
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath

    def exists(self) -> bool:
        return self.filepath and os.path.exists(self.filepath)

    def open_read(self):
        return open(self.filepath, 'r', encoding='utf-8')

    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass


# --- 2. VPP ENGINE (Der Mathematiker) ---

class VppTacticalEngine:
    """
    Verantwortlich für die mathematische Auswertung der Polardiagramme.
    Führt Interpolationen durch, um Werte zwischen den Stützstellen (TWS/TWA) zu finden.
    """
    def __init__(self, polars_data: Dict[str, Any]):
        # polars_data entspricht dem 'configurations' Abschnitt im JSON
        self.polars = polars_data
        self.debug_bounds: Optional[Tuple[float, float]] = None # Zum Debuggen der TWS-Grenzen

    def _interpolate_curve(self, curve_data: List[Dict[str, Any]], tws: float, twa: float) -> Optional[Dict[str, float]]:
        """
        Input ist eine der vom VPP berechneten Datenkurven für die individuellen
        Segelkombinationen. (curve_data) enthält die Parameter
        (BSP, Heel, Reef, Flat...) als Funktion der Windbedingungen (TWS/TWA).
        Die Funktion weiß nicht, ob sie gerade eine Genua, einen Spi oder
        die optimale Hüllgeschwindigkeit interpoliert.

        Kern-Algorithmus: Interpoliert Werte für einen exakten Windpunkt (TWS, TWA).

        Args:
            curve_data: Liste von Polarkurven (pro Windstärke).
            tws: Ziel-Windgeschwindigkeit.
            twa: Ziel-Windwinkel.

        Returns:
            Ein Dictionary mit den interpolierten Werten
            (BSP, Heel, Reef, Flat...) oder None.
            bezogen auf Ziel-Windgeschwindigkeit und -Windwinkel
        """
        if not curve_data: return None

        # 1. Sortieren der Kurven nach Windstärke (TWS)
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])

        # 2. Finden der umgebenden Kurven (Lower & Upper Bound)
        # Beispiel: Bei TWS 13kn suchen wir die 12kn Kurve (lower) und 14kn Kurve (upper)
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]

        # Randbehandlung: Wenn Wind < kleinste Kurve, nimm die kleinste.
        if not lower_candidates:
            lower = sorted_curves[0]
        else:
            lower = lower_candidates[-1] # Die höchste der unteren Kandidaten

        # Randbehandlung: Wenn Wind > größte Kurve, nimm die größte.
        if not upper_candidates:
            upper = sorted_curves[-1]
        else:
            upper = upper_candidates[0] # Die niedrigste der oberen Kandidaten

        # Debug-Info speichern für die Anzeige
        self.debug_bounds = (lower["tws"], upper["tws"])

        # 3. Berechne Interpolations-Faktor für TWS (0.0 bis 1.0)
        if lower["tws"] == upper["tws"]:
            tws_fac = 0.0
        else:
            tws_fac = (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        # Interne Funktion für TWA-Interpolation
        def get_vals_at_twa(curve_points: List[Dict], t_twa: float) -> Dict[str, float]:
            """Nutzt numpy.interp für lineare Interpolation entlang des Winkels."""
            # Alle Winkel dieser Kurve extrahieren
            twas = np.array([p["twa"] for p in curve_points])

            # Die Werte, die uns interessieren
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                # Extrahiere die Y-Werte für diesen Key
                vals = np.array([p.get(k, 0) for p in curve_points])
                # Interpoliere
                res[k] = float(np.interp(t_twa, twas, vals))
            return res

        # 4. Werte für Lower und Upper Curve am TWA berechnen
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))

        # 5. Mischen (Lineare Interpolation zwischen den Windstärken)
        final = {}
        for k in vals_low:
            final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac

        return final

    def get_targets(self, tws: float, twa: float) -> Optional[Dict[str, float]]:
        """
        KONTEXT 1: DAS OPTIMUM (Zielvorgabe)
        Hier füttern wir die Rechenmaschine mit den 'Best Performance' Daten.
        Das VPP hat hier bereits berechnet, was das theoretisch schnellste
        Segel für diesen Punkt ist. Das Ergebnis ist unsere Zielvorgabe
        für Speed und Trimm (Reef/Flat).
        """
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws: float, twa: float) -> Dict[str, float]:
        """
        Vergleicht die theoretische Geschwindigkeit verschiedener
        Segeltypen (Jib vs. Spi). Trifft die strategische Entscheidung
        'Ab wann lohnt sich der Spi?'.
        Wir rufen die Interpolationsmaschine (_interpolate_curve)
        DREIMAL hintereinander auf, jedes Mal mit dem Datensatz
        für ein anderes Segel, um zu sehen, welches Segel nach VPP
        die beste Performance liefern würde.
        """
        speeds = {}

        # 1. Headsail Only Mode
        h_data = self.polars.get("headsail", {}).get("data", [])
        h_res = self._interpolate_curve(h_data, tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0

        # 2. Asymmetric Spinnaker Mode
        a_data = self.polars.get("asymmetric", {}).get("data", [])
        # Fallback auf alternative ID, falls 'asymmetric' leer ist
        if not a_data: a_data = self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0

        # 3. Symmetric Spinnaker Mode
        s_data = self.polars.get("symmetric", {}).get("data", [])
        s_res = self._interpolate_curve(s_data, tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0

        return speeds


# --- 3. LOGIK (SailStrategist - Der Inventar Manager) ---

class SailStrategist:
    """
    Verwaltet das Segelinventar. Erstellt virtuelle Segel (Reffs), klassifiziert Spinnaker
    und trifft die finale Entscheidung, welches Segel gesetzt werden soll.
    """
    def __init__(self, sail_inventory: List[Dict], rig_config: Dict, main_reef_drops: Tuple[float, float]):
        # Kopie des Inventars, damit wir virtuelle Segel hinzufügen können
        # ohne die Rohdaten zu ändern
        self.inventory = copy.deepcopy(sail_inventory)

        # Rigg-Daten: P ist die Vorliekslänge des Großsegels
        # (wichtig für Reff-Berechnung)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops # Tuple (1.66, 4.11)

        # Cache für maximale Flächen (Basis für 100% Berechnung)
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None

        # Initialisierung
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        """Durchsucht das Inventar nach den größten Segeln jeder Kategorie."""
        for s in self.inventory:
            area = s.get("area", 0)

            if s.get("type") == "HEAD":
                self.max_jib_area = max(self.max_jib_area, area)

            if s.get("type") in ["SYM", "ASYM"]:
                self.max_spi_area = max(self.max_spi_area, area)

            if s.get("type") == "MAIN":
                if area > self.max_main_area:
                    self.max_main_area = area
                # Suche das als "Active" markierte Großsegel
                if s.get("attributes", {}).get("Active") == "1":
                    self.active_main = s

        # Fallback: Wenn kein 'Active' Flag, nimm das größte Großsegel
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        """
        Erstellt virtuelle Reff-Versionen für spezifische Focks.
        Berechnet die Fläche geometrisch korrekt (Trapez-Abzug am Unterliek).
        """
        # Konfiguration: {ORC_ID: Verkürzung in Metern}
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []

        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]

                # Maße holen (Versuche diverse Schreibweisen aus JSON)
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)

                if jl > 0 and lpg > 0:
                    # Geometrie: Wir schneiden unten ein Trapez ab.
                    # Die Breite am Schnittpunkt verringert sich proportional zur Höhe.
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    new_area = s.get("area", 0) - removed_area

                    # Virtuelles Segel Objekt bauen
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = new_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0) # Referenz auf Originalfläche
                    new_sails.append(v)

        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        """
        Erstellt virtuelle Reffs für das Großsegel.
        Nutzt die vom User angegebenen Reff-Tiefen (main_reef_drops).
        """
        if not self.active_main or self.rig_p == 0: return

        m_area = self.active_main.get("area", 0)
        new_sails = []

        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue

            # Annahme für Geometrie: Das Unterliek (E) verhält sich proportional zu P
            # um eine Referenzbreite zu haben (da E im JSON oft fehlt).
            # Formel: Breite E_approx = 2 * Fläche / P
            e_approx = 2 * m_area / self.rig_p

            # Breite an der neuen Reff-Höhe
            width_at_cut = e_approx * (1 - (drop / self.rig_p))

            # Abzuziehende Fläche (Trapez unten)
            removed = drop * (e_approx + width_at_cut) / 2.0

            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)

        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        """
        Klassifiziert Spinnaker in REACHER (flach) und RUNNER (bauchig)
        basierend auf dem Verhältnis Mittelbreite (SHW) zu Unterliek (SFL).
        """
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                # Daten holen (mit Fallbacks auf Attributes)
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)

                if sfl > 0:
                    ratio = shw / sfl
                    # Grenzwert 0.75 ist ORC Standard
                    if ratio < 0.75:
                        s["strategy_type"] = "REACHER"
                    else:
                        s["strategy_type"] = "RUNNER"

    def determine_best_config(self, twa: float, tws: float, comparison_speeds: Dict[str, float], reef_factor: float) -> Dict[str, Any]:
        """
        Der zentrale Entscheidungs-Algorithmus.
        1. Entscheidet Upwind vs. Downwind basierend auf VPP Speed Vergleich.
        2. Wählt das beste Großsegel (Reff-Stufe) basierend auf Flächenziel.
        3. Wählt das beste Vorsegel (Fock oder Spi) basierend auf Winkel und Fläche.
        """
        abs_twa = abs(twa)

        # 1. Modus Entscheidung (Upwind vs. Downwind)
        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False

        # Logik: Wenn wir tiefer als 60 Grad fahren UND der Spi signifikant schneller ist (+0.2kn)
        if abs_twa > 60:
            if max_spi_speed > (speed_head + 0.2):
                mode = "DOWNWIND"
                use_spi = True

        # 2. Main Auswahl
        # Wir suchen das Main, das dem reef_factor am besten entspricht.
        # Soll-Fläche = Max Main Area * Reff Faktor
        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]

        target_main = self.max_main_area * reef_factor
        best_main = min(mains, key=lambda m: abs(m.get("area", 0) - target_main))

        # 3. Vorsegel Auswahl
        best_front = None

        if not use_spi:
            # --- HEADSAIL MODUS ---
            # Suche Jibs (Full + Reefs)
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor
            best_front = min(jibs, key=lambda j: abs(j.get("area", 0) - target_jib))

            # Sanity Check: Wenn fast volle Power gefordert ist (>0.98), keine virtuellen Reffs nehmen
            if reef_factor > 0.98:
                if best_main.get("is_virtual"): best_main = self.active_main
                if best_front.get("is_virtual"):
                    # Suche das ungereffte Parent-Segel
                    pid = best_front["internal_id"].split("_REEF")[0]
                    best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)

        else:
            # --- SPI MODUS ---
            # Welcher Spi Typ ist optimal?
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            # Wenn der sym. Spi laut VPP schneller ist, erzwingen wir SYM
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"

            candidates = []
            if needed_type == "SYM":
                 candidates = [s for s in self.inventory if s.get("type") == "SYM"]
            else:
                 candidates = [s for s in self.inventory if s.get("strategy_type") == needed_type]

            # Fallback: Wenn kein passender Typ da ist, nimm irgendeinen Spi
            if not candidates:
                candidates = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"]]

            if candidates:
                # Sortiere nach Größe
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)

                # Heavy Weather Logic: Bei viel Wind (>22kn) nimm den kleineren Spi (falls vorhanden)
                if tws > 22 and len(candidates) > 1:
                    best_front = candidates[-1] # Kleinerer
                else:
                    best_front = candidates[0] # Größter

        return {
            'main': best_main,
            'head': best_front,
            'mode': mode,
            'speed_potential': max_spi_speed if use_spi else speed_head
        }

# --- 4. OUTPUT / DASHBOARD ---

def run_tactical_advice(hdg: float, twd: float, tws: float, main_drops: Tuple[float, float], data_dir: str, json_filename: str):
    """
    Hauptfunktion: Lädt Daten, initiiert Engines und druckt den Bericht.
    """
    h = DriveHandler(data_dir, json_filename)
    if not h.exists():
        print(f"FEHLER: Datei {json_filename} nicht gefunden.")
        return

    with h as handler:
        with handler.open_read() as f: data = json.load(f)

    # Daten entpacken
    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    # Engines starten
    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    # TWA Berechnung (True Wind Angle)
    diff = (twd - hdg) % 360
    twa = 360 - diff if diff > 180 else diff
    side = "Backbord-Bug" if diff > 180 else "Steuerbord-Bug"

    # Daten holen
    targets = engine.get_targets(tws, twa)
    comp_speeds = engine.compare_configurations(tws, twa)

    if not targets:
        print("Keine VPP Daten für diese Bedingungen.")
        return

    # Strategie berechnen
    rec = strategist.determine_best_config(twa, tws, comp_speeds, targets['reef'])

    # --- ANZEIGE START ---
    print("\n" + "#"*75)
    print(f"   TAKTIK-COMPUTER: {data['meta']['boat_name'].upper()}")
    print(f"   VPP-Profil: {data['data_section']['dxtName']}")
    print("#"*75)

    # 1. Situation
    print(f"\n[1] SITUATION")
    print(f"    TWS: {tws:.1f} kn  |  TWA: {twa:.1f}° ({side})")
    if engine.debug_bounds:
        print(f"    (VPP-Interpolation zwischen {engine.debug_bounds[0]:.0f} kn und {engine.debug_bounds[1]:.0f} kn Kurven)")
    print("-" * 75)

    # 2. VPP Targets
    print(f"[2] VPP ZIELVORGABEN (Optimal Curve)")
    print(f"    Target Speed (BSP): {targets['bsp']:.2f} kn")
    print(f"    Target AWA:         {targets['awa']:.1f}°")
    print(f"    Target AWS:         {targets['aws']:.1f} kn")
    print(f"    Target HEEL:        {targets['heel']:.1f}°")
    print(f"    ------------------------------------")
    print(f"    REEF Faktor:        {targets['reef']:.3f} (VPP fordert {targets['reef']*100:.1f}% Fläche)")
    flat_msg = "POWER" if targets['flat'] >= 0.98 else "FLATTEN" if targets['flat'] > 0.9 else "DEPOWER"
    print(f"    FLAT Faktor:        {targets['flat']:.3f} -> {flat_msg}")
    print("-" * 75)

    # 3. Entscheidung & Details
    print(f"[3] SEGEL-ENTSCHEIDUNG (Action)")
    if rec:
        m = rec['main']
        h = rec['head']

        # Helper zum Drucken
        def print_sail_stats(label: str, sail: Optional[Dict]) -> float:
            if not sail:
                print(f"    >>> {label}:  KEIN SEGEL")
                return 0.0

            name = sail['name']
            curr_area = sail.get('area', 0)
            # Finde Basis-Fläche (Ungerefft)
            orig_area = sail.get('parent_area', curr_area)
            if not sail.get('is_virtual') and 'parent_area' not in sail: orig_area = curr_area

            state = "GEREFFT" if sail.get('is_virtual') else "UNGEREFFT"

            print(f"    >>> {label}:  {name}")
            print(f"                Status:    {state}")
            print(f"                Basis:     {orig_area:.2f} m²")
            print(f"                Effektiv:  {curr_area:.2f} m²")
            return curr_area

        area_m = print_sail_stats("MAIN ", m)
        area_h = print_sail_stats("FRONT", h)
        total_eff = area_m + area_h

        print(f"    ------------------------------------")
        print(f"    >>> SUMME:  {total_eff:.2f} m² (Effektive Gesamtfläche)")

        # 4. Soll-Ist Vergleich
        # Basisfläche bestimmen (Upwind vs Downwind Basis)
        if rec['mode'] == "UPWIND":
            base_area = strategist.max_main_area + strategist.max_jib_area
            mode_lbl = "UPWIND (Main + Jib)"
        else:
            base_area = strategist.max_main_area + strategist.max_spi_area
            mode_lbl = "DOWNWIND (Main + Spi)"

        vpp_target_area = base_area * targets['reef']
        delta_area = total_eff - vpp_target_area

        fit_msg = "PERFEKT"
        if delta_area > 5: fit_msg = "OVERPOWERED"
        if delta_area < -5: fit_msg = "UNDERPOWERED"

        print(f"\n    [Flächen-Vergleich]")
        print(f"    Modus:              {mode_lbl}")
        print(f"    VPP-Soll:           {vpp_target_area:.2f} m²")
        print(f"    Abweichung:         {delta_area:+.2f} m² -> {fit_msg}")

        # Speed Check
        calc_speed = rec['speed_potential']
        opt_speed = targets['bsp']
        diff_speed = calc_speed - opt_speed

        print(f"\n    [Performance Check]")
        print(f"    Speed Potential:    {calc_speed:.2f} kn (aus spezifischer Polare)")
        if diff_speed < -0.1:
            print(f"    => Warnung: {abs(diff_speed):.2f} kn langsamer als 'Best Performance' Optimum.")
        elif diff_speed > 0.1:
             print(f"    => Info: Schneller als Optimum ({diff_speed:+.2f} kn).")
        else:
            print(f"    => Config entspricht Optimum.")

    else:
        print("    Keine passende Konfiguration gefunden.")

    print("#"*75 + "\n")

# --- 5. EINGABE-MASKE (User Params) ---

# @markdown ### 1. Kurs & Wetterdaten
COURSE_HDG = 300 # @param {type:"number"}
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 26 # @param {type:"number"}

# @markdown ### 2. Main Reff Konfiguration (Verkürzung Vorliek in Metern)
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### 3. Datei Pfade
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_tactical_advice(COURSE_HDG, WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME)

In [ ]:
# @title Modul 4: Der Taktische Berater (Version 13 - Updated Parameters)
"""
================================================================================
MODUL 4: TAKTISCHER BERATER (Tactical Advisor)
================================================================================

BESCHREIBUNG:
Dieses Modul fungiert als "Bordcomputer". Es simuliert eine Echtzeit-Entscheidungshilfe
basierend auf aktuellen Sensordaten (Wind, Kurs) und den statischen Schiffsdaten (VPP, Rigg).
Es beantwortet die Fragen: "Welches Segel?", "Welches Reff?", "Welcher Trimm?".

FUNKTIONEN:
1. Interpolation: Berechnet exakte VPP-Zielwerte (Speed, Heel) für krumme Windwerte (z.B. 13.5 kn).
2. Segel-Strategie: Wählt die optimale Segelkombination basierend auf VPP-Vorgaben und Geometrie.
3. Reff-Simulation: Berechnet die effektive Fläche gereffter Segel (Trapez-Formel).
4. Performance-Check: Vergleicht das theoretische Potenzial der gewählten Segel mit dem Optimum.

INPUT DATEN (Argumente):
- hdg (float): Kompasskurs des Bootes (Heading, 0-360°).
- twd (float): Wahre Windrichtung (True Wind Direction, 0-360°).
- tws (float): Wahre Windgeschwindigkeit (True Wind Speed in Knoten).
- main_drops (Tuple[float, float]): Die Tiefe der Reffs im Großsegel in Metern (Reff 1, Reff 2).
- json_data (Dict): Das geladene ORC-JSON-File.

DATENSTRUKTUREN (Wichtigste Variablen):
- inventory (List[Dict]): Liste aller Segel. Ein Segel ist ein Dictionary mit Keys:
  {'name': str, 'area': float, 'measurements': Dict, 'strategy_type': str, ...}
- polars (Dict): Die VPP-Daten. Struktur: {'optimal': {'data': [...]}, 'headsail': ...}
- curve_data (List[Dict]): Eine Polarkurve für verschiedene Windstärken (TWS).
- comparison_speeds (Dict[str, float]): Speed-Vergleich {'HEAD': 7.2, 'ASYM': 8.1, ...}

TYPE HINTS:
Wir nutzen das `typing` Modul für statische Code-Analyse und bessere Lesbarkeit.
================================================================================
"""

import sys
import os
import json
import copy
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR ---

class DriveHandler:
    """
    Verwaltet den Zugriff auf Dateien, egal ob lokal oder in Google Colab (Google Drive).
    Nutzt das Context Manager Pattern (with ... as ...).
    """
    COLAB_ROOT = '/content/drive'

    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename:
            self.set_full_path(directory, filename)

    def _is_colab(self) -> bool:
        """Prüft, ob das Skript in einer Google Colab Umgebung läuft."""
        return 'google.colab' in sys.modules

    def _mount(self):
        """Mountet Google Drive nur bei Bedarf und nur einmal."""
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True

    def set_full_path(self, directory: str, filename: str) -> str:
        """Baut den korrekten Pfad zusammen (Colab vs. Lokal)."""
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath

    def exists(self) -> bool:
        return self.filepath and os.path.exists(self.filepath)

    def open_read(self):
        return open(self.filepath, 'r', encoding='utf-8')

    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass


# --- 2. VPP ENGINE (Der Mathematiker) ---

class VppTacticalEngine:
    """
    Verantwortlich für die mathematische Auswertung der Polardiagramme.
    Führt Interpolationen durch, um Werte zwischen den Stützstellen (TWS/TWA) zu finden.
    """
    def __init__(self, polars_data: Dict[str, Any]):
        # polars_data entspricht dem 'configurations' Abschnitt im JSON
        self.polars = polars_data
        self.debug_bounds: Optional[Tuple[float, float]] = None # Zum Debuggen der TWS-Grenzen

    def _interpolate_curve(self, curve_data: List[Dict[str, Any]], tws: float, twa: float) -> Optional[Dict[str, float]]:
        """
        Input ist eine der vom VPP berechneten Datenkurven für die individuellen
        Segelkombinationen. (curve_data) enthält die Parameter
        (BSP, Heel, Reef, Flat...) als Funktion der Windbedingungen (TWS/TWA).
        Die Funktion weiß nicht, ob sie gerade eine Genua, einen Spi oder
        die optimale Hüllgeschwindigkeit interpoliert.

        Kern-Algorithmus: Interpoliert Werte für einen exakten Windpunkt (TWS, TWA).

        Args:
            curve_data: Liste von Polarkurven (pro Windstärke).
            tws: Ziel-Windgeschwindigkeit.
            twa: Ziel-Windwinkel.

        Returns:
            Ein Dictionary mit den interpolierten Werten
            (BSP, Heel, Reef, Flat...) oder None.
            bezogen auf Ziel-Windgeschwindigkeit und -Windwinkel
        """
        if not curve_data: return None

        # 1. Sortieren der Kurven nach Windstärke (TWS)
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])

        # 2. Finden der umgebenden Kurven (Lower & Upper Bound)
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]

        # Randbehandlung
        lower = lower_candidates[-1] if lower_candidates else sorted_curves[0]
        upper = upper_candidates[0] if upper_candidates else sorted_curves[-1]

        # Debug-Info speichern
        self.debug_bounds = (lower["tws"], upper["tws"])

        # 3. Berechne Interpolations-Faktor für TWS (0.0 bis 1.0)
        if lower["tws"] == upper["tws"]:
            tws_fac = 0.0
        else:
            tws_fac = (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        # Interne Funktion für TWA-Interpolation
        def get_vals_at_twa(curve_points: List[Dict], t_twa: float) -> Dict[str, float]:
            """Nutzt numpy.interp für lineare Interpolation entlang des Winkels."""
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res

        # 4. Werte für Lower und Upper Curve am TWA berechnen
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))

        # 5. Mischen (Lineare Interpolation zwischen den Windstärken)
        final = {}
        for k in vals_low:
            final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac

        return final

    def get_targets(self, tws: float, twa: float) -> Optional[Dict[str, float]]:
        """
        KONTEXT 1: DAS OPTIMUM (Zielvorgabe)
        Hier füttern wir die Rechenmaschine mit den 'Best Performance' Daten.
        Das VPP hat hier bereits berechnet, was das theoretisch schnellste
        Segel für diesen Punkt ist. Das Ergebnis ist unsere Zielvorgabe
        für Speed und Trimm (Reef/Flat).
        """
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws: float, twa: float) -> Dict[str, float]:
        """
        Vergleicht die theoretische Geschwindigkeit verschiedener
        Segeltypen (Jib vs. Spi). Trifft die strategische Entscheidung
        'Ab wann lohnt sich der Spi?'.
        Wir rufen die Interpolationsmaschine (_interpolate_curve)
        DREIMAL hintereinander auf, jedes Mal mit dem Datensatz
        für ein anderes Segel, um zu sehen, welches Segel nach VPP
        die beste Performance liefern würde.
        """
        speeds = {}

        # 1. Headsail Only Mode
        h_data = self.polars.get("headsail", {}).get("data", [])
        h_res = self._interpolate_curve(h_data, tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0

        # 2. Asymmetric Spinnaker Mode
        a_data = self.polars.get("asymmetric", {}).get("data", [])
        # Fallback auf alternative ID, falls 'asymmetric' leer ist
        if not a_data: a_data = self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0

        # 3. Symmetric Spinnaker Mode
        s_data = self.polars.get("symmetric", {}).get("data", [])
        s_res = self._interpolate_curve(s_data, tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0

        return speeds


# --- 3. LOGIK (SailStrategist - Der Inventar Manager) ---

class SailStrategist:
    """
    Verwaltet das Segelinventar. Erstellt virtuelle Segel (Reffs), klassifiziert Spinnaker
    und trifft die finale Entscheidung, welches Segel gesetzt werden soll.
    """
    def __init__(self, sail_inventory: List[Dict], rig_config: Dict, main_reef_drops: Tuple[float, float]):
        # Kopie des Inventars, damit wir virtuelle Segel hinzufügen können
        # ohne die Rohdaten zu ändern
        self.inventory = copy.deepcopy(sail_inventory)

        # Rigg-Daten: P ist die Vorliekslänge des Großsegels
        # (wichtig für Reff-Berechnung)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops

        # Cache für maximale Flächen (Basis für 100% Berechnung)
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None

        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._generate_virtual_spi_reefs() # A3 Reff
        self._classify_spinnakers()

    def _analyze_inventory(self):
        """Durchsucht das Inventar nach den größten Segeln jeder Kategorie."""
        for s in self.inventory:
            area = s.get("area", 0)
            if s.get("type") == "HEAD":
                self.max_jib_area = max(self.max_jib_area, area)
            if s.get("type") in ["SYM", "ASYM"]:
                self.max_spi_area = max(self.max_spi_area, area)
            if s.get("type") == "MAIN":
                if area > self.max_main_area:
                    self.max_main_area = area
                if s.get("attributes", {}).get("Active") == "1":
                    self.active_main = s

        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        """
        Erstellt virtuelle Reff-Versionen für spezifische Focks.
        Berechnet die Fläche geometrisch korrekt (Trapez-Abzug am Unterliek).
        """
        # Konfiguration: {ORC_ID: Verkürzung in Metern}
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []

        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)

                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    new_area = s.get("area", 0) - removed_area

                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = new_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        """
        Erstellt virtuelle Reffs für das Großsegel.
        Nutzt die vom User angegebenen Reff-Tiefen (main_reef_drops).
        """
        if not self.active_main or self.rig_p == 0: return

        m_area = self.active_main.get("area", 0)
        new_sails = []

        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue

            # Trapez Näherung
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0

            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)

        self.inventory.extend(new_sails)

    def _generate_virtual_spi_reefs(self):
        """
        Spezifische Reff-Logik für den A3 (#62037).
        Reff-Geometrie: SLU -1.2m, SLE -1.6m.
        Behebt die Endlosschleife, indem neue Segel separat gesammelt werden.
        """
        target_orc_id = "#62037"
        new_sails = [] # WICHTIG: Sammel-Liste, um Endlosschleife zu vermeiden

        for s in self.inventory:
            if s.get("orc_sail_id") == target_orc_id:
                orig_area = s.get("area", 0)
                m = s.get("measurements", {})
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 7.62)

                avg_drop = 1.40
                removed_strip_area = sfl * avg_drop # Rechteck-Näherung unten
                new_area = orig_area - removed_strip_area

                v = copy.deepcopy(s)
                v["internal_id"] += "_REEF"
                v["name"] = "A3 (Reff: SLU-1.2m/SLE-1.6m)"
                v["area"] = new_area
                v["is_virtual"] = True
                v["strategy_type"] = "REACHER"
                v["parent_area"] = orig_area
                new_sails.append(v)

        # Erst nach der Schleife hinzufügen
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        """Klassifiziert Spinnaker in REACHER und RUNNER."""
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa: float, tws: float, comparison_speeds: Dict[str, float], reef_factor: float) -> Dict[str, Any]:
        """
        Der zentrale Entscheidungs-Algorithmus (Global Solver).
        """
        abs_twa = abs(twa)

        # 1. Modus Entscheidung (Upwind vs. Downwind)
        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False

        if abs_twa > 60:
            if max_spi_speed > (speed_head + 0.2):
                mode = "DOWNWIND"
                use_spi = True

        # 2. Main Auswahl
        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]

        target_main = self.max_main_area * reef_factor
        best_main = min(mains, key=lambda m: abs(m.get("area", 0) - target_main))

        # 3. Vorsegel Auswahl
        best_front = None

        if not use_spi:
            # HEADSAIL MODE
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor
            best_front = min(jibs, key=lambda j: abs(j.get("area", 0) - target_jib))

            # Toleranz: Nimm ungerefft, wenn fast voll (98%)
            if reef_factor > 0.98:
                if best_main.get("is_virtual"): best_main = self.active_main
                if best_front.get("is_virtual"):
                    pid = best_front["internal_id"].split("_REEF")[0]
                    best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)
        else:
            # SPI MODE
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"

            candidates = []
            if needed_type == "SYM": candidates = [s for s in self.inventory if s.get("type") == "SYM"]
            else: candidates = [s for s in self.inventory if s.get("strategy_type") == needed_type]

            if not candidates: candidates = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"]]

            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                # Heavy Weather Logic: Bei viel Wind (>20kn) nimm den kleineren Spi
                if tws > 20 and len(candidates) > 1:
                    best_front = candidates[-1]
                else:
                    best_front = candidates[0]

        return {
            'main': best_main,
            'head': best_front,
            'mode': mode,
            'speed_potential': max_spi_speed if use_spi else speed_head
        }

# --- 4. OUTPUT / DASHBOARD ---

def run_tactical_advice(hdg: float, twd: float, tws: float, main_drops: Tuple[float, float], data_dir: str, json_filename: str):
    """
    Hauptfunktion: Lädt Daten, initiiert Engines und druckt den Bericht.
    """
    h = DriveHandler(data_dir, json_filename)
    if not h.exists():
        print(f"FEHLER: Datei {json_filename} nicht gefunden.")
        return

    with h as handler:
        with handler.open_read() as f: data = json.load(f)

    # Daten entpacken
    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    # Engines starten
    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    # TWA Berechnung
    diff = (twd - hdg) % 360
    twa = 360 - diff if diff > 180 else diff
    side = "Backbord-Bug" if diff > 180 else "Steuerbord-Bug"

    # Daten holen
    targets = engine.get_targets(tws, twa)
    comp_speeds = engine.compare_configurations(tws, twa)

    if not targets:
        print("Keine VPP Daten für diese Bedingungen.")
        return

    # Strategie berechnen
    rec = strategist.determine_best_config(twa, tws, comp_speeds, targets['reef'])

    # --- ANZEIGE START ---
    print("\n" + "#"*75)
    print(f"   TAKTIK-COMPUTER: {data['meta']['boat_name'].upper()}")
    print(f"   VPP-Profil: {data['data_section']['dxtName']}")
    print("#"*75)

    # 1. Situation
    print(f"\n[1] SITUATION")
    print(f"    TWS: {tws:.1f} kn  |  TWA: {twa:.1f}° ({side})")
    if engine.debug_bounds:
        print(f"    (Interpolation: {engine.debug_bounds[0]:.0f} kn - {engine.debug_bounds[1]:.0f} kn)")
    print("-" * 75)

    # 2. VPP Targets
    print(f"[2] VPP ZIELVORGABEN (Optimal Curve)")
    print(f"    Target Speed (BSP): {targets['bsp']:.2f} kn")
    print(f"    Target AWA:         {targets['awa']:.1f}°")
    print(f"    Target AWS:         {targets['aws']:.1f} kn")
    print(f"    Target HEEL:        {targets['heel']:.1f}°")
    print(f"    ------------------------------------")
    print(f"    REEF Faktor:        {targets['reef']:.3f} (VPP fordert {targets['reef']*100:.1f}% Fläche)")
    flat_msg = "POWER" if targets['flat'] >= 0.98 else "FLATTEN" if targets['flat'] > 0.9 else "DEPOWER"
    print(f"    FLAT Faktor:        {targets['flat']:.3f} -> {flat_msg}")
    print("-" * 75)

    # 3. Entscheidung & Details
    print(f"[3] SEGEL-ENTSCHEIDUNG (Action)")
    if rec:
        m = rec['main']
        h = rec['head']

        def print_sail_stats(label: str, sail: Optional[Dict]) -> float:
            if not sail:
                print(f"    >>> {label}:  KEIN SEGEL")
                return 0.0
            name = sail['name']
            curr_area = sail.get('area', 0)
            orig_area = sail.get('parent_area', curr_area)
            if not sail.get('is_virtual') and 'parent_area' not in sail: orig_area = curr_area
            state = "GEREFFT" if sail.get('is_virtual') else "UNGEREFFT"
            print(f"    >>> {label}:  {name}")
            print(f"                Status:    {state}")
            print(f"                Basis:     {orig_area:.2f} m²")
            print(f"                Effektiv:  {curr_area:.2f} m²")
            return curr_area

        area_m = print_sail_stats("MAIN ", m)
        area_h = print_sail_stats("FRONT", h)
        total_eff = area_m + area_h

        print(f"    ------------------------------------")
        print(f"    >>> SUMME:  {total_eff:.2f} m² (Effektive Gesamtfläche)")

        # 4. Soll-Ist Vergleich
        # Basisfläche bestimmen (Upwind vs Downwind Basis)
        if rec['mode'] == "UPWIND":
            base_area = strategist.max_main_area + strategist.max_jib_area
            mode_lbl = "UPWIND (Main + Jib)"
        else:
            base_area = strategist.max_main_area + strategist.max_spi_area
            mode_lbl = "DOWNWIND (Main + Spi)"

        vpp_target_area = base_area * targets['reef']
        delta_area = total_eff - vpp_target_area

        fit_msg = "PERFEKT"
        if delta_area > 5: fit_msg = "OVERPOWERED"
        if delta_area < -5: fit_msg = "UNDERPOWERED"

        print(f"\n    [Flächen-Vergleich]")
        print(f"    Modus:              {mode_lbl}")
        print(f"    VPP-Soll:           {vpp_target_area:.2f} m²")
        print(f"    Abweichung:         {delta_area:+.2f} m² -> {fit_msg}")

        # Speed Check
        calc_speed = rec['speed_potential']
        opt_speed = targets['bsp']
        diff_speed = calc_speed - opt_speed

        print(f"\n    [Performance Check]")
        print(f"    Speed Potential:    {calc_speed:.2f} kn (aus spezifischer Polare)")
        if diff_speed < -0.1:
            print(f"    => Warnung: {abs(diff_speed):.2f} kn langsamer als 'Best Performance' Optimum.")
        elif diff_speed > 0.1:
             print(f"    => Info: Schneller als Optimum ({diff_speed:+.2f} kn).")
        else:
            print(f"    => Config entspricht Optimum.")

    else:
        print("    Keine passende Konfiguration gefunden.")

    print("#"*75 + "\n")

# --- 5. EINGABE-MASKE (User Params) ---

# @markdown ### 1. Kurs & Wetterdaten
COURSE_HDG = 300 # @param {type:"number"}
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 26 # @param {type:"number"}

# @markdown ### 2. Main Reff Konfiguration (Verkürzung Vorliek in Metern)
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### 3. Datei Pfade
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_tactical_advice(COURSE_HDG, WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME)

In [ ]:
# @title Modul 5: Der Routen-Optimierer (GPX & Table Mode)
"""
================================================================================
MODUL 5: ROUTEN-OPTIMIERER (Route Optimizer)
================================================================================

BESCHREIBUNG:
Dieses Modul importiert eine GPX-Route, zerlegt sie in einzelne Segmente (Legs),
berechnet für jedes Leg den Kurs (Heading) und den Windeinfallswinkel (TWA)
und ermittelt die optimale Segelkonfiguration.

NEUE FUNKTIONEN:
1. GPX-Parser: Liest <rte> (Routen) aus "Kursdaten.gpx".
2. Geo-Math: Berechnet Distanz (Haversine) und Kurs (Bearing) zwischen Koordinaten.
3. Tabellen-Output: Generiert eine kompakte Übersicht aller Legs mittels Pandas.
4. Dummy-Modus: Erzeugt eine Test-GPX-Datei, falls keine vorhanden ist.

INPUT:
- Statisches Wetter (TWD, TWS).
- GPX-Datei (Wegpunkte).
- Schiffsdaten (JSON).

OUTPUT:
- Pandas DataFrame (Tabelle) mit allen nautischen und taktischen Daten pro Leg.
================================================================================
"""

import sys
import os
import json
import copy
import math
import pandas as pd
import xml.etree.ElementTree as ET
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR & HELPER ---

class DriveHandler:
    """Verwaltet den Dateizugriff."""
    COLAB_ROOT = '/content/drive'
    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename: self.set_full_path(directory, filename)
    def _is_colab(self) -> bool: return 'google.colab' in sys.modules
    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True
    def set_full_path(self, directory: str, filename: str) -> str:
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath
    def exists(self) -> bool: return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

def create_dummy_gpx(directory: str, filename: str):
    """Erzeugt eine Test-Route (Dreieckskurs), falls keine Datei existiert."""
    # Wir simulieren: Start -> Kreuz -> Halbwind -> Vorwind -> Ziel
    gpx_content = """<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GeminiAI">
  <rte>
    <name>Test Dreieck</name>
    <rtept lat="54.4000" lon="10.4000"><name>START</name></rtept>
    <rtept lat="54.4500" lon="10.3500"><name>WP1 (Kreuz)</name></rtept>
    <rtept lat="54.4500" lon="10.5000"><name>WP2 (Reach)</name></rtept>
    <rtept lat="54.4000" lon="10.4000"><name>ZIEL (Run)</name></rtept>
  </rte>
</gpx>"""

    # Pfadhandling
    if 'google.colab' in sys.modules:
        root = '/content/drive/MyDrive'
        path = os.path.join(root, directory, filename)
        # Drive muss gemounted sein (passiert im DriveHandler, hier quick fix)
        if not os.path.exists(root):
             from google.colab import drive
             drive.mount('/content/drive')
    else:
        path = os.path.join(directory, filename)

    # Schreiben
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(gpx_content)
        print(f"INFO: Dummy-GPX erzeugt unter: {path}")
    except Exception as e:
        print(f"WARNUNG: Konnte Dummy-GPX nicht schreiben: {e}")

# --- 2. GEO MATH (Navigation) ---

class GeoMath:
    """Berechnet Distanzen und Kurse auf der Erdkugel."""

    @staticmethod
    def haversine_distance(lat1, lon1, lat2, lon2):
        """Gibt Distanz in Seemeilen (nm) zurück."""
        R = 3440.065 # Erdradius in nm
        phi1, phi2 = math.radians(lat1), math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)

        a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        return R * c

    @staticmethod
    def calculate_bearing(lat1, lon1, lat2, lon2):
        """Gibt den Kurs (Bearing) in Grad (0-360) zurück."""
        y = math.sin(math.radians(lon2-lon1)) * math.cos(math.radians(lat2))
        x = math.cos(math.radians(lat1))*math.sin(math.radians(lat2)) - \
            math.sin(math.radians(lat1))*math.cos(math.radians(lat2))*math.cos(math.radians(lon2-lon1))
        theta = math.atan2(y, x)
        bearing = (math.degrees(theta) + 360) % 360
        return bearing

# --- 3. VPP ENGINE (Version 12) ---

class VppTacticalEngine:
    def __init__(self, polars_data):
        self.polars = polars_data

    def _interpolate_curve(self, curve_data, tws, twa):
        if not curve_data: return None
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]
        lower = lower_candidates[-1] if lower_candidates else sorted_curves[0]
        upper = upper_candidates[0] if upper_candidates else sorted_curves[-1]
        tws_fac = 0.0 if lower["tws"] == upper["tws"] else (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        def get_vals_at_twa(curve_points, t_twa):
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))
        final = {}
        for k in vals_low: final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac
        return final

    def get_targets(self, tws, twa):
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws, twa):
        speeds = {}
        h_res = self._interpolate_curve(self.polars.get("headsail", {}).get("data", []), tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0
        a_data = self.polars.get("asymmetric", {}).get("data", []) or self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0
        s_res = self._interpolate_curve(self.polars.get("symmetric", {}).get("data", []), tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0
        return speeds

# --- 4. LOGIK (SailStrategist Version 12 - Stability Fix) ---

class SailStrategist:
    def __init__(self, sail_inventory, rig_config, main_reef_drops):
        self.inventory = copy.deepcopy(sail_inventory)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._generate_virtual_spi_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        for s in self.inventory:
            area = s.get("area", 0)
            if s.get("type") == "HEAD": self.max_jib_area = max(self.max_jib_area, area)
            if s.get("type") in ["SYM", "ASYM"]: self.max_spi_area = max(self.max_spi_area, area)
            if s.get("type") == "MAIN":
                if area > self.max_main_area: self.max_main_area = area
                if s.get("attributes", {}).get("Active") == "1": self.active_main = s
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)
                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = s.get("area", 0) - removed_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        if not self.active_main or self.rig_p == 0: return
        m_area = self.active_main.get("area", 0)
        new_sails = []
        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0
            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_spi_reefs(self):
        target_orc_id = "#62037"
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") == target_orc_id:
                orig_area = s.get("area", 0)
                m = s.get("measurements", {})
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 7.62)
                avg_drop = 1.40
                removed_strip_area = sfl * avg_drop
                new_area = orig_area - removed_strip_area
                v = copy.deepcopy(s)
                v["internal_id"] += "_REEF"
                v["name"] = "A3 (Reff: SLU-1.2m/SLE-1.6m)"
                v["area"] = new_area
                v["is_virtual"] = True
                v["strategy_type"] = "REACHER"
                v["parent_area"] = orig_area
                new_sails.append(v)
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa, tws, comparison_speeds, reef_factor):
        abs_twa = abs(twa)
        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False
        if abs_twa > 60 and max_spi_speed > (speed_head + 0.2):
            mode = "DOWNWIND"
            use_spi = True

        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]
        target_main = self.max_main_area * reef_factor
        best_main = min(mains, key=lambda m: abs(m.get("area", 0) - target_main))

        best_front = None
        if not use_spi:
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor
            best_front = min(jibs, key=lambda j: abs(j.get("area", 0) - target_jib))
            if reef_factor > 0.98:
                if best_main.get("is_virtual"): best_main = self.active_main
                if best_front.get("is_virtual"):
                    pid = best_front["internal_id"].split("_REEF")[0]
                    best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)
        else:
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"
            candidates = []
            if needed_type == "SYM": candidates = [s for s in self.inventory if s.get("type") == "SYM"]
            else: candidates = [s for s in self.inventory if s.get("strategy_type") == needed_type]
            if not candidates: candidates = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"]]
            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                if tws > 20 and len(candidates) > 1: best_front = candidates[-1]
                else: best_front = candidates[0]

        return {'main': best_main, 'head': best_front, 'mode': mode, 'speed_potential': max_spi_speed if use_spi else speed_head}


# --- 5. EXECUTION & TABLE MODE ---

def run_route_optimization(twd, tws, main_drops, data_dir, json_filename, gpx_filename):
    # 1. Infrastruktur Check
    h_json = DriveHandler(data_dir, json_filename)
    h_gpx = DriveHandler(data_dir, gpx_filename)

    if not h_gpx.exists():
        print("GPX nicht gefunden. Erzeuge Dummy-Route...")
        create_dummy_gpx(data_dir, gpx_filename)
        h_gpx.set_full_path(data_dir, gpx_filename) # Reload path

    if not h_json.exists():
        print(f"CRITICAL: ORC Datei {json_filename} fehlt!")
        return

    # 2. Lade Daten
    with h_json as handler:
        with handler.open_read() as f: data = json.load(f)

    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    # Engines
    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    # 3. Parse GPX
    try:
        with h_gpx as handler:
            tree = ET.parse(handler.filepath)
        root = tree.getroot()
        # Namespace handling can be tricky in GPX, we try simple find first
        ns = {'gpx': 'http://www.topografix.com/GPX/1/1'}
        route_points = root.findall(".//gpx:rtept", ns)
        if not route_points:
            # Fallback ohne Namespace
            route_points = root.findall(".//rtept")

        if len(route_points) < 2:
            print("Zu wenige Wegpunkte in der GPX Datei (mind. 2 benötigt).")
            return

    except Exception as e:
        print(f"GPX Parsing Fehler: {e}")
        return

    # 4. Berechnung der Legs
    results = []

    print(f"Berechne Route für {len(route_points)-1} Segmente...")

    for i in range(len(route_points) - 1):
        p1 = route_points[i]
        p2 = route_points[i+1]

        lat1 = float(p1.get("lat"))
        lon1 = float(p1.get("lon"))
        lat2 = float(p2.get("lat"))
        lon2 = float(p2.get("lon"))

        # Geo Math
        dist = GeoMath.haversine_distance(lat1, lon1, lat2, lon2)
        hdg = GeoMath.calculate_bearing(lat1, lon1, lat2, lon2)

        # Wind Math
        diff = (twd - hdg) % 360
        twa = 360 - diff if diff > 180 else diff
        side = "BB" if diff > 180 else "SB"

        # Tactical Math
        targets = engine.get_targets(tws, twa)
        comp_speeds = engine.compare_configurations(tws, twa)

        if targets:
            rec = strategist.determine_best_config(twa, tws, comp_speeds, targets['reef'])

            # Formatting
            m_sail = rec['main']
            h_sail = rec['head']

            # Short names
            m_name = "None"
            if m_sail:
                if m_sail.get("is_virtual"):
                    m_name = m_sail['name'].replace("MAIN (", "").replace(")", "") # Shorten
                else:
                    m_name = "Full"

            f_name = "None"
            if h_sail:
                f_name = h_sail['name'].split(" ")[0] # First word only for table
                if h_sail.get("is_virtual"): f_name += " (Reff)"

            # Area Calc
            act_area = (m_sail.get('area',0) if m_sail else 0) + (h_sail.get('area',0) if h_sail else 0)

            if rec['mode'] == "UPWIND":
                base = strategist.max_main_area + strategist.max_jib_area
            else:
                base = strategist.max_main_area + strategist.max_spi_area
            tgt_area = base * targets['reef']
            delta = act_area - tgt_area

            # Add to list
            results.append({
                "Leg": i+1,
                "Dist (nm)": round(dist, 2),
                "HDG": round(hdg, 0),
                "TWA": round(twa, 0),
                "Side": side,
                "AWA": round(targets['awa'], 0),
                "AWS": round(targets['aws'], 1),
                "BSP (Tgt)": round(targets['bsp'], 2),
                "Main": m_name,
                "Front": f_name,
                "Area (Ist)": round(act_area, 1),
                "Area (Soll)": round(tgt_area, 1),
                "Delta": round(delta, 1),
                "Trimm": "FLAT" if targets['flat'] < 0.95 else "PWR"
            })

    # 5. Output Pandas
    df = pd.DataFrame(results)

    print("\n" + "="*80)
    print(f" ROUTEN-ANALYSE: {data['meta']['boat_name']}")
    print(f" Wetter: TWD {twd}° | TWS {tws} kn")
    print("="*80)

    # Colab-friendly Display
    try:
        from IPython.display import display
        display(df)
    except:
        print(df.to_string())

# --- 6. USER INPUT ---

# @markdown ### Wetter (Statisch)
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 18 # @param {type:"number"}

# @markdown ### Reff Konfiguration
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### Dateien
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}
GPX_FILENAME = "Kursdaten.gpx" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_route_optimization(WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME, GPX_FILENAME)

GPX nicht gefunden. Erzeuge Dummy-Route...
INFO: Dummy-GPX erzeugt unter: /content/drive/MyDrive/Segeln/ORC_Vermessung/Kursdaten.gpx
Berechne Route für 3 Segmente...

================================================================================
 ROUTEN-ANALYSE: TRUE GRIT
 Wetter: TWD 345° | TWS 18 kn
================================================================================

,Leg,Dist (nm),HDG,TWA,Side,AWA,AWS,BSP (Tgt),Main,Front,Area (Ist),Area (Soll),Delta,Trimm
0,1,3.47,330.0,15.0,SB,26.0,23.2,6.70,Reff 2: -4.11m,25.03.2020 (Reff),41.4,38.3,3.0,FLAT
1,2,5.24,90.0,105.0,BB,76.0,16.5,8.71,Reff 1: -1.66m,A3 (Reff),105.1,129.7,-24.5,FLAT
2,3,4.61,229.0,116.0,SB,85.0,15.1,9.07,Reff 1: -1.66m,A3 (Reff),105.1,132.4,-27.2,FLAT

In [ ]:
# @title Modul 5: Der Routen-Optimierer (Version 14 - VMG Strategy Logic)
"""
================================================================================
MODUL 5: ROUTEN-OPTIMIERER (Route Optimizer) - VMG UPDATE
================================================================================

BESCHREIBUNG:
Dieses Modul importiert eine GPX-Route und berechnet die optimale Strategie.
Es korrigiert nun automatisch "unmögliche" Kurse. Wenn der Kurs zum Wegpunkt
direkt gegen den Wind (oder zu tief vor dem Wind) liegt, wird der optimale
VMG-Winkel (Beat Angle / Gybe Angle) für die Segelwahl angesetzt.

NEUE FUNKTIONEN IN V14:
- VMG-Check: Prüft, ob gekreuzt (Tacking) oder gehalst (Gybing) werden muss.
- Beat/Gybe Lookup: Ermittelt die optimalen Wendewinkel aus den VPP-Daten.
- Output: Markiert Legs als "VMG UP" (Kreuzen) oder "VMG DOWN" (Vorwind-Kreuz).

INPUT:
- Statisches Wetter & GPX-Route.

OUTPUT:
- Tabelle mit realistischen TWA-Werten (z.B. 42° statt 15° beim Kreuzen).
================================================================================
"""

import sys
import os
import json
import copy
import math
import pandas as pd
import xml.etree.ElementTree as ET
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR ---

class DriveHandler:
    """Verwaltet den Dateizugriff."""
    COLAB_ROOT = '/content/drive'
    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename: self.set_full_path(directory, filename)
    def _is_colab(self) -> bool: return 'google.colab' in sys.modules
    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True
    def set_full_path(self, directory: str, filename: str) -> str:
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath
    def exists(self) -> bool: return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

def create_dummy_gpx(directory: str, filename: str):
    """Erzeugt eine Test-Route, falls keine Datei existiert."""
    gpx_content = """<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GeminiAI">
  <rte>
    <name>Test Route</name>
    <rtept lat="54.4000" lon="10.4000"><name>START</name></rtept>
    <rtept lat="54.4500" lon="10.3500"><name>WP1 (Upwind)</name></rtept>
    <rtept lat="54.4500" lon="10.5000"><name>WP2 (Reach)</name></rtept>
    <rtept lat="54.4000" lon="10.4000"><name>ZIEL (Run)</name></rtept>
  </rte>
</gpx>"""
    if 'google.colab' in sys.modules:
        root = '/content/drive/MyDrive'
        path = os.path.join(root, directory, filename)
        if not os.path.exists(root):
             from google.colab import drive
             drive.mount('/content/drive')
    else:
        path = os.path.join(directory, filename)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f: f.write(gpx_content)
        print(f"INFO: Dummy-GPX erzeugt unter: {path}")
    except Exception as e: print(f"WARNUNG: Konnte Dummy-GPX nicht schreiben: {e}")

# --- 2. GEO MATH ---

class GeoMath:
    @staticmethod
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 3440.065 # nm
        phi1, phi2 = math.radians(lat1), math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)
        a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        return R * c

    @staticmethod
    def calculate_bearing(lat1, lon1, lat2, lon2):
        y = math.sin(math.radians(lon2-lon1)) * math.cos(math.radians(lat2))
        x = math.cos(math.radians(lat1))*math.sin(math.radians(lat2)) - \
            math.sin(math.radians(lat1))*math.cos(math.radians(lat2))*math.cos(math.radians(lon2-lon1))
        theta = math.atan2(y, x)
        return (math.degrees(theta) + 360) % 360

# --- 3. VPP ENGINE (VMG Capable) ---

class VppTacticalEngine:
    def __init__(self, polars_data):
        self.polars = polars_data

    def _interpolate_curve(self, curve_data, tws, twa):
        if not curve_data: return None
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]
        lower = lower_candidates[-1] if lower_candidates else sorted_curves[0]
        upper = upper_candidates[0] if upper_candidates else sorted_curves[-1]
        tws_fac = 0.0 if lower["tws"] == upper["tws"] else (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        def get_vals_at_twa(curve_points, t_twa):
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))
        final = {}
        for k in vals_low: final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac
        return final

    def get_vmg_angles(self, tws):
        """
        Ermittelt die optimalen Winkel für Kreuz (Beat) und Vorwind (Gybe).
        Nimmt den kleinsten/größten TWA aus der 'optimal' Kurve als Näherung.
        """
        data = self.polars.get("optimal", {}).get("data", [])
        if not data: return (45.0, 150.0) # Fallback

        # Hole interpolierte Kurve für diesen Wind
        # Wir interpolieren nicht die ganze Kurve, sondern schauen auf die Bounds
        # Einfachheitshalber: Nimm die Kurve, die dem Wind am nächsten ist
        sorted_curves = sorted(data, key=lambda x: abs(x["tws"] - tws))
        best_fit = sorted_curves[0]["curve"]

        # In der Optimal-Kurve ist der erste Eintrag meist der Beat Angle (Upwind VMG)
        # und der letzte Eintrag der Gybe Angle (Downwind VMG), oder wir suchen min/max TWA.
        twas = [p["twa"] for p in best_fit]
        beat_angle = min(twas)
        gybe_angle = max(twas)

        return beat_angle, gybe_angle

    def get_targets(self, tws, twa):
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws, twa):
        speeds = {}
        h_res = self._interpolate_curve(self.polars.get("headsail", {}).get("data", []), tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0
        a_data = self.polars.get("asymmetric", {}).get("data", []) or self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0
        s_res = self._interpolate_curve(self.polars.get("symmetric", {}).get("data", []), tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0
        return speeds

# --- 4. LOGIK (SailStrategist) ---

class SailStrategist:
    def __init__(self, sail_inventory, rig_config, main_reef_drops):
        self.inventory = copy.deepcopy(sail_inventory)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._generate_virtual_spi_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        for s in self.inventory:
            area = s.get("area", 0)
            if s.get("type") == "HEAD": self.max_jib_area = max(self.max_jib_area, area)
            if s.get("type") in ["SYM", "ASYM"]: self.max_spi_area = max(self.max_spi_area, area)
            if s.get("type") == "MAIN":
                if area > self.max_main_area: self.max_main_area = area
                if s.get("attributes", {}).get("Active") == "1": self.active_main = s
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)
                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    new_area = s.get("area", 0) - removed_area
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = new_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        if not self.active_main or self.rig_p == 0: return
        m_area = self.active_main.get("area", 0)
        new_sails = []
        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0
            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_spi_reefs(self):
        target_orc_id = "#62037"
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") == target_orc_id:
                orig_area = s.get("area", 0)
                m = s.get("measurements", {})
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 7.62)
                avg_drop = 1.40
                removed_strip_area = sfl * avg_drop
                new_area = orig_area - removed_strip_area
                v = copy.deepcopy(s)
                v["internal_id"] += "_REEF"
                v["name"] = "A3 (Reff: SLU-1.2m/SLE-1.6m)"
                v["area"] = new_area
                v["is_virtual"] = True
                v["strategy_type"] = "REACHER"
                v["parent_area"] = orig_area
                new_sails.append(v)
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa, tws, comparison_speeds, reef_factor):
        abs_twa = abs(twa)
        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False
        if abs_twa > 60 and max_spi_speed > (speed_head + 0.2):
            mode = "DOWNWIND"
            use_spi = True

        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]
        target_main = self.max_main_area * reef_factor
        best_main = min(mains, key=lambda m: abs(m.get("area", 0) - target_main))

        best_front = None
        if not use_spi:
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor
            best_front = min(jibs, key=lambda j: abs(j.get("area", 0) - target_jib))
            if reef_factor > 0.98:
                if best_main.get("is_virtual"): best_main = self.active_main
                if best_front.get("is_virtual"):
                    pid = best_front["internal_id"].split("_REEF")[0]
                    best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)
        else:
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"
            candidates = []
            if needed_type == "SYM": candidates = [s for s in self.inventory if s.get("type") == "SYM"]
            else: candidates = [s for s in self.inventory if s.get("strategy_type") == needed_type]
            if not candidates: candidates = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"]]
            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                if tws > 20 and len(candidates) > 1: best_front = candidates[-1]
                else: best_front = candidates[0]

        return {'main': best_main, 'head': best_front, 'mode': mode, 'speed_potential': max_spi_speed if use_spi else speed_head}


# --- 5. EXECUTION ---

def run_route_optimization(twd, tws, main_drops, data_dir, json_filename, gpx_filename):
    h_json = DriveHandler(data_dir, json_filename)
    h_gpx = DriveHandler(data_dir, gpx_filename)

    if not h_gpx.exists():
        print("GPX nicht gefunden. Erzeuge Dummy-Route...")
        create_dummy_gpx(data_dir, gpx_filename)
        h_gpx.set_full_path(data_dir, gpx_filename)

    if not h_json.exists():
        print(f"CRITICAL: ORC Datei {json_filename} fehlt!")
        return

    with h_json as handler:
        with handler.open_read() as f: data = json.load(f)

    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    # GPX Parse
    try:
        with h_gpx as handler: tree = ET.parse(handler.filepath)
        root = tree.getroot()
        ns = {'gpx': 'http://www.topografix.com/GPX/1/1'}
        route_points = root.findall(".//gpx:rtept", ns) or root.findall(".//rtept")
        if len(route_points) < 2: return
    except Exception as e:
        print(f"GPX Fehler: {e}")
        return

    results = []

    # Hole VMG Winkel für diesen Wind
    beat_angle, gybe_angle = engine.get_vmg_angles(tws)
    print(f"VMG Strategie bei {tws} kn Wind: Beat < {beat_angle:.1f}°, Gybe > {gybe_angle:.1f}°")

    for i in range(len(route_points) - 1):
        p1, p2 = route_points[i], route_points[i+1]
        lat1, lon1 = float(p1.get("lat")), float(p1.get("lon"))
        lat2, lon2 = float(p2.get("lat")), float(p2.get("lon"))

        dist = GeoMath.haversine_distance(lat1, lon1, lat2, lon2)
        hdg = GeoMath.calculate_bearing(lat1, lon1, lat2, lon2)

        diff = (twd - hdg) % 360
        geo_twa = 360 - diff if diff > 180 else diff # Geometrischer TWA
        side = "BB" if diff > 180 else "SB"

        # --- VMG KORREKTUR ---
        # Kann ich den direkten Kurs segeln?
        strategy = "Direct"
        sailed_twa = geo_twa

        if abs(geo_twa) < beat_angle:
            sailed_twa = beat_angle
            strategy = "VMG UP"
        elif abs(geo_twa) > gybe_angle:
            sailed_twa = gybe_angle
            strategy = "VMG DOWN"

        # Nutze den sailed_twa für die Segelwahl
        targets = engine.get_targets(tws, sailed_twa)
        comp_speeds = engine.compare_configurations(tws, sailed_twa)

        if targets:
            rec = strategist.determine_best_config(sailed_twa, tws, comp_speeds, targets['reef'])
            m_sail = rec['main']
            h_sail = rec['head']

            m_name = m_sail['name'].replace("MAIN (", "").replace(")", "") if m_sail and m_sail.get("is_virtual") else "Full" if m_sail else "None"
            f_name = h_sail['name'].split(" ")[0] if h_sail else "None"
            if h_sail and h_sail.get("is_virtual"): f_name += " (Reff)"

            act_area = (m_sail.get('area',0) if m_sail else 0) + (h_sail.get('area',0) if h_sail else 0)
            base = strategist.max_main_area + (strategist.max_jib_area if rec['mode']=="UPWIND" else strategist.max_spi_area)
            tgt_area = base * targets['reef']
            delta = act_area - tgt_area

            results.append({
                "Leg": i+1,
                "Dist": round(dist, 2),
                "HDG": round(hdg, 0),
                "Geo TWA": round(geo_twa, 0),
                "Sail TWA": round(sailed_twa, 0),
                "Strat": strategy,
                "Side": side,
                "AWS": round(targets['aws'], 1),
                "BSP": round(targets['bsp'], 2),
                "Main": m_name,
                "Front": f_name,
                "Area": round(act_area, 1),
                "Soll": round(tgt_area, 1),
                "Delta": round(delta, 1),
                "Trim": "FLAT" if targets['flat'] < 0.95 else "PWR"
            })

    df = pd.DataFrame(results)
    print("\n" + "="*80)
    print(f" ROUTEN-ANALYSE: {data['meta']['boat_name']}")
    print(f" Wetter: TWD {twd}° | TWS {tws} kn")
    print("="*80)
    try:
        from IPython.display import display
        display(df)
    except:
        print(df.to_string())

# --- 6. USER INPUT ---

# @markdown ### Wetter (Statisch)
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 18 # @param {type:"number"}

# @markdown ### Reff Konfiguration
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### Dateien
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}
GPX_FILENAME = "Kursdaten.gpx" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_route_optimization(WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME, GPX_FILENAME)

VMG Strategie bei 18 kn Wind: Beat < 38.4°, Gybe > 180.0°

================================================================================
 ROUTEN-ANALYSE: TRUE GRIT
 Wetter: TWD 345° | TWS 18 kn
================================================================================

,Leg,Dist,HDG,Geo TWA,Sail TWA,Strat,Side,AWS,BSP,Main,Front,Area,Soll,Delta,Trim
0,1,3.47,330.0,15.0,38.0,VMG UP,SB,23.2,6.70,Reff 2: -4.11m,25.03.2020 (Reff),41.4,38.3,3.0,FLAT
1,2,5.24,90.0,105.0,105.0,Direct,BB,16.5,8.71,Reff 1: -1.66m,A3 (Reff),105.1,129.7,-24.5,FLAT
2,3,4.61,229.0,116.0,116.0,Direct,SB,15.1,9.07,Reff 1: -1.66m,A3 (Reff),105.1,132.4,-27.2,FLAT

In [ ]:
# @title Modul 5: Der Routen-Optimierer (Version 15 - Race Tuned)
"""
================================================================================
MODUL 5: ROUTEN-OPTIMIERER (Route Optimizer) - RACE TUNED
================================================================================

BESCHREIBUNG:
Dieses Modul importiert eine GPX-Route und berechnet die optimale Strategie.
Version 15 beinhaltet eine "aggressive" Solver-Logik, die typisches Regatta-
verhalten abbildet: Lieber etwas zu viel Tuch und trimmen, als untermotorisiert
zu reffen.

ÄNDERUNGEN IN V15:
1. GPX: Route erweitert auf 5 Wegpunkte (inkl. Deep Reach & Run).
2. Solver: Bestraft "Underpowered" stärker als "Overpowered".
3. Thresholds: A3-Reff erst ab 24kn, Groß-Reff erst wenn VPP < 88% Fläche fordert.

INPUT:
- Statisches Wetter & GPX-Route.

OUTPUT:
- Tabelle mit realistischen Segelentscheidungen.
================================================================================
"""

import sys
import os
import json
import copy
import math
import pandas as pd
import xml.etree.ElementTree as ET
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR ---

class DriveHandler:
    """Verwaltet den Dateizugriff."""
    COLAB_ROOT = '/content/drive'
    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename: self.set_full_path(directory, filename)
    def _is_colab(self) -> bool: return 'google.colab' in sys.modules
    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True
    def set_full_path(self, directory: str, filename: str) -> str:
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath
    def exists(self) -> bool: return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

def create_dummy_gpx(directory: str, filename: str):
    """Erzeugt eine erweiterte Test-Route (Kreuz -> Reach -> Deep -> Run)."""
    gpx_content = """<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GeminiAI">
  <rte>
    <name>Race Course Extended</name>
    <rtept lat="54.4000" lon="10.4000"><name>START</name></rtept>
    <rtept lat="54.4500" lon="10.3500"><name>WP1 (Upwind)</name></rtept>
    <rtept lat="54.4500" lon="10.5000"><name>WP2 (Reach)</name></rtept>
    <rtept lat="54.4200" lon="10.5500"><name>WP3 (Deep Reach)</name></rtept>
    <rtept lat="54.3800" lon="10.5500"><name>ZIEL (Run)</name></rtept>
  </rte>
</gpx>"""
    if 'google.colab' in sys.modules:
        root = '/content/drive/MyDrive'
        path = os.path.join(root, directory, filename)
        if not os.path.exists(root):
             from google.colab import drive
             drive.mount('/content/drive')
    else:
        path = os.path.join(directory, filename)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f: f.write(gpx_content)
        print(f"INFO: Erweiterte Dummy-GPX erzeugt unter: {path}")
    except Exception as e: print(f"WARNUNG: Konnte Dummy-GPX nicht schreiben: {e}")

# --- 2. GEO MATH ---

class GeoMath:
    @staticmethod
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 3440.065 # nm
        phi1, phi2 = math.radians(lat1), math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)
        a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        return R * c

    @staticmethod
    def calculate_bearing(lat1, lon1, lat2, lon2):
        y = math.sin(math.radians(lon2-lon1)) * math.cos(math.radians(lat2))
        x = math.cos(math.radians(lat1))*math.sin(math.radians(lat2)) - \
            math.sin(math.radians(lat1))*math.cos(math.radians(lat2))*math.cos(math.radians(lon2-lon1))
        theta = math.atan2(y, x)
        return (math.degrees(theta) + 360) % 360

# --- 3. VPP ENGINE ---

class VppTacticalEngine:
    def __init__(self, polars_data):
        self.polars = polars_data

    def _interpolate_curve(self, curve_data, tws, twa):
        if not curve_data: return None
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]
        lower = lower_candidates[-1] if lower_candidates else sorted_curves[0]
        upper = upper_candidates[0] if upper_candidates else sorted_curves[-1]
        tws_fac = 0.0 if lower["tws"] == upper["tws"] else (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        def get_vals_at_twa(curve_points, t_twa):
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))
        final = {}
        for k in vals_low: final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac
        return final

    def get_vmg_angles(self, tws):
        data = self.polars.get("optimal", {}).get("data", [])
        if not data: return (45.0, 150.0)
        sorted_curves = sorted(data, key=lambda x: abs(x["tws"] - tws))
        best_fit = sorted_curves[0]["curve"]
        twas = [p["twa"] for p in best_fit]
        return min(twas), max(twas)

    def get_targets(self, tws, twa):
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws, twa):
        speeds = {}
        h_res = self._interpolate_curve(self.polars.get("headsail", {}).get("data", []), tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0
        a_data = self.polars.get("asymmetric", {}).get("data", []) or self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0
        s_res = self._interpolate_curve(self.polars.get("symmetric", {}).get("data", []), tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0
        return speeds

# --- 4. LOGIK (SailStrategist - RACE TUNED) ---

class SailStrategist:
    def __init__(self, sail_inventory, rig_config, main_reef_drops):
        self.inventory = copy.deepcopy(sail_inventory)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._generate_virtual_spi_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        for s in self.inventory:
            area = s.get("area", 0)
            if s.get("type") == "HEAD": self.max_jib_area = max(self.max_jib_area, area)
            if s.get("type") in ["SYM", "ASYM"]: self.max_spi_area = max(self.max_spi_area, area)
            if s.get("type") == "MAIN":
                if area > self.max_main_area: self.max_main_area = area
                if s.get("attributes", {}).get("Active") == "1": self.active_main = s
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)
                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    new_area = s.get("area", 0) - removed_area
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = new_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        if not self.active_main or self.rig_p == 0: return
        m_area = self.active_main.get("area", 0)
        new_sails = []
        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0
            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_spi_reefs(self):
        target_orc_id = "#62037"
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") == target_orc_id:
                orig_area = s.get("area", 0)
                m = s.get("measurements", {})
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 7.62)
                avg_drop = 1.40
                removed_strip_area = sfl * avg_drop
                new_area = orig_area - removed_strip_area
                v = copy.deepcopy(s)
                v["internal_id"] += "_REEF"
                v["name"] = "A3 (Reff: SLU-1.2m/SLE-1.6m)"
                v["area"] = new_area
                v["is_virtual"] = True
                v["strategy_type"] = "REACHER"
                v["parent_area"] = orig_area
                new_sails.append(v)
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa, tws, comparison_speeds, reef_factor):
        """
        RACE TUNED: Bestraft Underpowered stärker als Overpowered.
        """
        abs_twa = abs(twa)

        # Modus
        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False
        if abs_twa > 60 and max_spi_speed > (speed_head + 0.2):
            mode = "DOWNWIND"
            use_spi = True

        # --- MAIN SELECTION (Aggressiv) ---
        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]
        target_main = self.max_main_area * reef_factor

        # Heuristic: Wenn VPP > 88% Fläche will, nimm IMMER Voll-Groß
        if reef_factor > 0.88:
            best_main = self.active_main
        else:
            # Sonst suche das beste Match, aber strafe Underpowered ab
            def score_main(m):
                diff = m.get("area", 0) - target_main
                if diff < 0: return abs(diff) * 2.5 # Strafe für zu wenig Segel
                return diff # Strafe für zu viel Segel (linear)
            best_main = min(mains, key=score_main)

        # --- FRONT SELECTION ---
        best_front = None
        if not use_spi:
            # HEADSAIL
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor

            def score_jib(j):
                diff = j.get("area", 0) - target_jib
                if diff < 0: return abs(diff) * 2.0
                return diff

            best_front = min(jibs, key=score_jib)

            # Anti-Jib-Reff Check (außer bei Sturm)
            if reef_factor > 0.90 and best_front.get("is_virtual"):
                 pid = best_front["internal_id"].split("_REEF")[0]
                 best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)

        else:
            # SPI
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"

            candidates = []
            if needed_type == "SYM": candidates = [s for s in self.inventory if s.get("type") == "SYM"]
            else: candidates = [s for s in self.inventory if s.get("strategy_type") == needed_type]
            if not candidates: candidates = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"]]

            if candidates:
                # Filter A3-Reff (Nur zulassen wenn TWS > 24 kn)
                filtered_candidates = []
                for c in candidates:
                    if c.get("is_virtual") and "A3" in c.get("name", ""):
                        if tws >= 24: filtered_candidates.append(c)
                    else:
                        filtered_candidates.append(c)

                if not filtered_candidates: filtered_candidates = candidates # Fallback

                # Heavy Weather Sortierung
                filtered_candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                if tws > 22 and len(filtered_candidates) > 1:
                    best_front = filtered_candidates[-1]
                else:
                    best_front = filtered_candidates[0]

        return {'main': best_main, 'head': best_front, 'mode': mode, 'speed_potential': max_spi_speed if use_spi else speed_head}


# --- 5. EXECUTION ---

def run_route_optimization(twd, tws, main_drops, data_dir, json_filename, gpx_filename):
    h_json = DriveHandler(data_dir, json_filename)
    h_gpx = DriveHandler(data_dir, gpx_filename)

    if not h_gpx.exists():
        print("GPX nicht gefunden. Erzeuge Dummy-Route...")
        create_dummy_gpx(data_dir, gpx_filename)
        h_gpx.set_full_path(data_dir, gpx_filename)

    if not h_json.exists():
        print(f"CRITICAL: ORC Datei {json_filename} fehlt!")
        return

    with h_json as handler:
        with handler.open_read() as f: data = json.load(f)

    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    try:
        with h_gpx as handler: tree = ET.parse(handler.filepath)
        root = tree.getroot()
        ns = {'gpx': 'http://www.topografix.com/GPX/1/1'}
        route_points = root.findall(".//gpx:rtept", ns) or root.findall(".//rtept")
        if len(route_points) < 2: return
    except Exception as e:
        print(f"GPX Fehler: {e}")
        return

    results = []
    beat_angle, gybe_angle = engine.get_vmg_angles(tws)
    print(f"VMG Strategie ({tws} kn): Beat < {beat_angle:.1f}°, Gybe > {gybe_angle:.1f}°")

    for i in range(len(route_points) - 1):
        p1, p2 = route_points[i], route_points[i+1]
        lat1, lon1 = float(p1.get("lat")), float(p1.get("lon"))
        lat2, lon2 = float(p2.get("lat")), float(p2.get("lon"))

        dist = GeoMath.haversine_distance(lat1, lon1, lat2, lon2)
        hdg = GeoMath.calculate_bearing(lat1, lon1, lat2, lon2)

        diff = (twd - hdg) % 360
        geo_twa = 360 - diff if diff > 180 else diff
        side = "BB" if diff > 180 else "SB"

        strategy = "Direct"
        sailed_twa = geo_twa

        if abs(geo_twa) < beat_angle:
            sailed_twa = beat_angle
            strategy = "VMG UP"
        elif abs(geo_twa) > gybe_angle:
            sailed_twa = gybe_angle
            strategy = "VMG DOWN"

        targets = engine.get_targets(tws, sailed_twa)
        comp_speeds = engine.compare_configurations(tws, sailed_twa)

        if targets:
            rec = strategist.determine_best_config(sailed_twa, tws, comp_speeds, targets['reef'])
            m_sail = rec['main']
            h_sail = rec['head']

            m_name = m_sail['name'].replace("MAIN (", "").replace(")", "") if m_sail and m_sail.get("is_virtual") else "Full" if m_sail else "None"
            f_name = h_sail['name'].split(" ")[0] if h_sail else "None"
            if h_sail and h_sail.get("is_virtual"): f_name += " (Reff)"

            act_area = (m_sail.get('area',0) if m_sail else 0) + (h_sail.get('area',0) if h_sail else 0)
            base = strategist.max_main_area + (strategist.max_jib_area if rec['mode']=="UPWIND" else strategist.max_spi_area)
            tgt_area = base * targets['reef']
            delta = act_area - tgt_area

            results.append({
                "Leg": i+1,
                "Dist": round(dist, 2),
                "HDG": round(hdg, 0),
                "Geo TWA": round(geo_twa, 0),
                "Sail TWA": round(sailed_twa, 0),
                "Strat": strategy,
                "Side": side,
                "AWS": round(targets['aws'], 1),
                "BSP": round(targets['bsp'], 2),
                "Main": m_name,
                "Front": f_name,
                "Area": round(act_area, 1),
                "Soll": round(tgt_area, 1),
                "Delta": round(delta, 1),
                "Trim": "FLAT" if targets['flat'] < 0.95 else "PWR"
            })

    df = pd.DataFrame(results)
    print("\n" + "="*80)
    print(f" ROUTEN-ANALYSE: {data['meta']['boat_name']}")
    print(f" Wetter: TWD {twd}° | TWS {tws} kn")
    print("="*80)
    try:
        from IPython.display import display
        display(df)
    except:
        print(df.to_string())

# --- 6. USER INPUT ---

# @markdown ### Wetter (Statisch)
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 18 # @param {type:"number"}

# @markdown ### Reff Konfiguration
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### Dateien
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}
GPX_FILENAME = "Kursdaten.gpx" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_route_optimization(WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME, GPX_FILENAME)

VMG Strategie (18 kn): Beat < 38.4°, Gybe > 180.0°

================================================================================
 ROUTEN-ANALYSE: TRUE GRIT
 Wetter: TWD 345° | TWS 18 kn
================================================================================

,Leg,Dist,HDG,Geo TWA,Sail TWA,Strat,Side,AWS,BSP,Main,Front,Area,Soll,Delta,Trim
0,1,3.47,330.0,15.0,38.0,VMG UP,SB,23.2,6.70,Reff 2: -4.11m,25.03.2020 (Reff),41.4,38.3,3.0,FLAT
1,2,5.24,90.0,105.0,105.0,Direct,BB,16.5,8.71,Full,A3 (Reff),113.6,129.7,-16.1,FLAT
2,3,4.61,229.0,116.0,116.0,Direct,SB,15.1,9.07,Full,A3 (Reff),113.6,132.4,-18.8,FLAT

In [ ]:
# @title Modul 5: Der Routen-Optimierer (Version 16 - A3 Logic Fix)
"""
================================================================================
MODUL 5: ROUTEN-OPTIMIERER (Route Optimizer) - V16
================================================================================

BESCHREIBUNG:
Dieses Modul importiert eine GPX-Route und berechnet die optimale Strategie.
Es nutzt VMG-Logik (Kreuzen/Halsen) und eine aggressive Segelwahl.

ÄNDERUNGEN IN V16:
- SPI-LOGIK FIX: Unter 20 kn Wind wird die Unterscheidung REACHER/RUNNER
  aufgehoben. Das ermöglicht die Wahl des vollen A3 (Runner-Schnitt) auf
  Reach-Kursen, statt auf das (zu kleine) A3-Reff (Reacher-Schnitt) zu wechseln.
- A3-REFF SPERRE: Das A3-Reff ist strikt gesperrt unter 24 kn TWS.

INPUT:
- Statisches Wetter & GPX-Route.

OUTPUT:
- Tabelle mit korrigierten Segeln (Full Main, Full A3 bei 18kn).
================================================================================
"""

import sys
import os
import json
import copy
import math
import pandas as pd
import xml.etree.ElementTree as ET
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR ---

class DriveHandler:
    """Verwaltet den Dateizugriff."""
    COLAB_ROOT = '/content/drive'
    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename: self.set_full_path(directory, filename)
    def _is_colab(self) -> bool: return 'google.colab' in sys.modules
    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True
    def set_full_path(self, directory: str, filename: str) -> str:
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath
    def exists(self) -> bool: return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

def create_dummy_gpx(directory: str, filename: str):
    """Erzeugt eine erweiterte Test-Route (Kreuz -> Reach -> Deep -> Run)."""
    gpx_content = """<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GeminiAI">
  <rte>
    <name>Race Course Extended</name>
    <rtept lat="54.4000" lon="10.4000"><name>START</name></rtept>
    <rtept lat="54.4500" lon="10.3500"><name>WP1 (Upwind)</name></rtept>
    <rtept lat="54.4500" lon="10.5000"><name>WP2 (Reach)</name></rtept>
    <rtept lat="54.4200" lon="10.5500"><name>WP3 (Deep Reach)</name></rtept>
    <rtept lat="54.3800" lon="10.5500"><name>ZIEL (Run)</name></rtept>
  </rte>
</gpx>"""
    if 'google.colab' in sys.modules:
        root = '/content/drive/MyDrive'
        path = os.path.join(root, directory, filename)
        if not os.path.exists(root):
             from google.colab import drive
             drive.mount('/content/drive')
    else:
        path = os.path.join(directory, filename)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f: f.write(gpx_content)
        print(f"INFO: Erweiterte Dummy-GPX erzeugt unter: {path}")
    except Exception as e: print(f"WARNUNG: Konnte Dummy-GPX nicht schreiben: {e}")

# --- 2. GEO MATH ---

class GeoMath:
    @staticmethod
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 3440.065 # nm
        phi1, phi2 = math.radians(lat1), math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)
        a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        return R * c

    @staticmethod
    def calculate_bearing(lat1, lon1, lat2, lon2):
        y = math.sin(math.radians(lon2-lon1)) * math.cos(math.radians(lat2))
        x = math.cos(math.radians(lat1))*math.sin(math.radians(lat2)) - \
            math.sin(math.radians(lat1))*math.cos(math.radians(lat2))*math.cos(math.radians(lon2-lon1))
        theta = math.atan2(y, x)
        return (math.degrees(theta) + 360) % 360

# --- 3. VPP ENGINE ---

class VppTacticalEngine:
    def __init__(self, polars_data):
        self.polars = polars_data

    def _interpolate_curve(self, curve_data, tws, twa):
        if not curve_data: return None
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]
        lower = lower_candidates[-1] if lower_candidates else sorted_curves[0]
        upper = upper_candidates[0] if upper_candidates else sorted_curves[-1]
        tws_fac = 0.0 if lower["tws"] == upper["tws"] else (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        def get_vals_at_twa(curve_points, t_twa):
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))
        final = {}
        for k in vals_low: final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac
        return final

    def get_vmg_angles(self, tws):
        data = self.polars.get("optimal", {}).get("data", [])
        if not data: return (45.0, 150.0)
        sorted_curves = sorted(data, key=lambda x: abs(x["tws"] - tws))
        best_fit = sorted_curves[0]["curve"]
        twas = [p["twa"] for p in best_fit]
        return min(twas), max(twas)

    def get_targets(self, tws, twa):
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws, twa):
        speeds = {}
        h_res = self._interpolate_curve(self.polars.get("headsail", {}).get("data", []), tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0
        a_data = self.polars.get("asymmetric", {}).get("data", []) or self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0
        s_res = self._interpolate_curve(self.polars.get("symmetric", {}).get("data", []), tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0
        return speeds

# --- 4. LOGIK (SailStrategist - V16 FIX) ---

class SailStrategist:
    def __init__(self, sail_inventory, rig_config, main_reef_drops):
        self.inventory = copy.deepcopy(sail_inventory)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._generate_virtual_spi_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        for s in self.inventory:
            area = s.get("area", 0)
            if s.get("type") == "HEAD": self.max_jib_area = max(self.max_jib_area, area)
            if s.get("type") in ["SYM", "ASYM"]: self.max_spi_area = max(self.max_spi_area, area)
            if s.get("type") == "MAIN":
                if area > self.max_main_area: self.max_main_area = area
                if s.get("attributes", {}).get("Active") == "1": self.active_main = s
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)
                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    new_area = s.get("area", 0) - removed_area
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = new_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        if not self.active_main or self.rig_p == 0: return
        m_area = self.active_main.get("area", 0)
        new_sails = []
        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0
            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_spi_reefs(self):
        target_orc_id = "#62037"
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") == target_orc_id:
                orig_area = s.get("area", 0)
                m = s.get("measurements", {})
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 7.62)
                avg_drop = 1.40
                removed_strip_area = sfl * avg_drop
                new_area = orig_area - removed_strip_area
                v = copy.deepcopy(s)
                v["internal_id"] += "_REEF"
                v["name"] = "A3 (Reff: SLU-1.2m/SLE-1.6m)"
                v["area"] = new_area
                v["is_virtual"] = True
                v["strategy_type"] = "REACHER"
                v["parent_area"] = orig_area
                new_sails.append(v)
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa, tws, comparison_speeds, reef_factor):
        abs_twa = abs(twa)

        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False
        if abs_twa > 60 and max_spi_speed > (speed_head + 0.2):
            mode = "DOWNWIND"
            use_spi = True

        # --- MAIN SELECTION (Aggressiv) ---
        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]
        target_main = self.max_main_area * reef_factor

        if reef_factor > 0.88:
            best_main = self.active_main
        else:
            def score_main(m):
                diff = m.get("area", 0) - target_main
                if diff < 0: return abs(diff) * 2.5
                return diff
            best_main = min(mains, key=score_main)

        # --- FRONT SELECTION ---
        best_front = None
        if not use_spi:
            # HEADSAIL
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor

            def score_jib(j):
                diff = j.get("area", 0) - target_jib
                if diff < 0: return abs(diff) * 2.0
                return diff
            best_front = min(jibs, key=score_jib)

            if reef_factor > 0.90 and best_front.get("is_virtual"):
                 pid = best_front["internal_id"].split("_REEF")[0]
                 best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)

        else:
            # SPI MODE FIX
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"

            # Sammle ALLE Spis
            all_spis = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"] or "SPI" in s.get("strategy_type", "")]

            candidates = []
            for s in all_spis:
                # FILTER 1: Form / Typ
                # Wenn Wind < 20kn, ignorieren wir Reacher/Runner Unterscheidung
                # um Fläche zu priorisieren. (A3 Full = Runner darf bei Reach fahren)
                if tws < 20:
                     is_shape_ok = True
                else:
                     # Strict
                     if needed_type == "SYM": is_shape_ok = (s.get("type") == "SYM")
                     else: is_shape_ok = (s.get("strategy_type") == needed_type)

                # FILTER 2: Reff Sperre
                # A3 Reff nur wenn TWS >= 24
                is_reff_ok = True
                if s.get("is_virtual") and "A3" in s.get("name", ""):
                     if tws < 24: is_reff_ok = False

                if is_shape_ok and is_reff_ok:
                    candidates.append(s)

            # Fallback
            if not candidates:
                 # Nimm alles was nicht das verbotene Reff ist
                 candidates = [s for s in all_spis if not (s.get("is_virtual") and tws < 24)]

            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                if tws > 22 and len(candidates) > 1:
                    best_front = candidates[-1]
                else:
                    best_front = candidates[0]

        return {'main': best_main, 'head': best_front, 'mode': mode, 'speed_potential': max_spi_speed if use_spi else speed_head}


# --- 5. EXECUTION ---

def run_route_optimization(twd, tws, main_drops, data_dir, json_filename, gpx_filename):
    h_json = DriveHandler(data_dir, json_filename)
    h_gpx = DriveHandler(data_dir, gpx_filename)

    if not h_gpx.exists():
        print("GPX nicht gefunden. Erzeuge Dummy-Route...")
        create_dummy_gpx(data_dir, gpx_filename)
        h_gpx.set_full_path(data_dir, gpx_filename)

    if not h_json.exists():
        print(f"CRITICAL: ORC Datei {json_filename} fehlt!")
        return

    with h_json as handler:
        with handler.open_read() as f: data = json.load(f)

    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    try:
        with h_gpx as handler: tree = ET.parse(handler.filepath)
        root = tree.getroot()
        ns = {'gpx': 'http://www.topografix.com/GPX/1/1'}
        route_points = root.findall(".//gpx:rtept", ns) or root.findall(".//rtept")
        if len(route_points) < 2: return
    except Exception as e:
        print(f"GPX Fehler: {e}")
        return

    results = []
    beat_angle, gybe_angle = engine.get_vmg_angles(tws)
    print(f"VMG Strategie ({tws} kn): Beat < {beat_angle:.1f}°, Gybe > {gybe_angle:.1f}°")

    for i in range(len(route_points) - 1):
        p1, p2 = route_points[i], route_points[i+1]
        lat1, lon1 = float(p1.get("lat")), float(p1.get("lon"))
        lat2, lon2 = float(p2.get("lat")), float(p2.get("lon"))

        dist = GeoMath.haversine_distance(lat1, lon1, lat2, lon2)
        hdg = GeoMath.calculate_bearing(lat1, lon1, lat2, lon2)

        diff = (twd - hdg) % 360
        geo_twa = 360 - diff if diff > 180 else diff
        side = "BB" if diff > 180 else "SB"

        strategy = "Direct"
        sailed_twa = geo_twa

        if abs(geo_twa) < beat_angle:
            sailed_twa = beat_angle
            strategy = "VMG UP"
        elif abs(geo_twa) > gybe_angle:
            sailed_twa = gybe_angle
            strategy = "VMG DOWN"

        targets = engine.get_targets(tws, sailed_twa)
        comp_speeds = engine.compare_configurations(tws, sailed_twa)

        if targets:
            rec = strategist.determine_best_config(sailed_twa, tws, comp_speeds, targets['reef'])
            m_sail = rec['main']
            h_sail = rec['head']

            m_name = m_sail['name'].replace("MAIN (", "").replace(")", "") if m_sail and m_sail.get("is_virtual") else "Full" if m_sail else "None"
            f_name = h_sail['name'].split(" ")[0] if h_sail else "None"
            if h_sail and h_sail.get("is_virtual"): f_name += " (Reff)"

            act_area = (m_sail.get('area',0) if m_sail else 0) + (h_sail.get('area',0) if h_sail else 0)
            base = strategist.max_main_area + (strategist.max_jib_area if rec['mode']=="UPWIND" else strategist.max_spi_area)
            tgt_area = base * targets['reef']
            delta = act_area - tgt_area

            results.append({
                "Leg": i+1,
                "Dist": round(dist, 2),
                "HDG": round(hdg, 0),
                "Geo TWA": round(geo_twa, 0),
                "Sail TWA": round(sailed_twa, 0),
                "Strat": strategy,
                "Side": side,
                "AWS": round(targets['aws'], 1),
                "BSP": round(targets['bsp'], 2),
                "Main": m_name,
                "Front": f_name,
                "Area": round(act_area, 1),
                "Soll": round(tgt_area, 1),
                "Delta": round(delta, 1),
                "Trim": "FLAT" if targets['flat'] < 0.95 else "PWR"
            })

    df = pd.DataFrame(results)
    print("\n" + "="*80)
    print(f" ROUTEN-ANALYSE: {data['meta']['boat_name']}")
    print(f" Wetter: TWD {twd}° | TWS {tws} kn")
    print("="*80)
    try:
        from IPython.display import display
        display(df)
    except:
        print(df.to_string())

# --- 6. USER INPUT ---

# @markdown ### Wetter (Statisch)
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 18 # @param {type:"number"}

# @markdown ### Reff Konfiguration
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### Dateien
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}
GPX_FILENAME = "Kursdaten.gpx" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_route_optimization(WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME, GPX_FILENAME)

VMG Strategie (18 kn): Beat < 38.4°, Gybe > 180.0°

================================================================================
 ROUTEN-ANALYSE: TRUE GRIT
 Wetter: TWD 345° | TWS 18 kn
================================================================================

,Leg,Dist,HDG,Geo TWA,Sail TWA,Strat,Side,AWS,BSP,Main,Front,Area,Soll,Delta,Trim
0,1,3.47,330.0,15.0,38.0,VMG UP,SB,23.2,6.70,Reff 2: -4.11m,25.03.2020 (Reff),41.4,38.3,3.0,FLAT
1,2,5.24,90.0,105.0,105.0,Direct,BB,16.5,8.71,Full,20.11.2025,153.0,129.7,23.3,FLAT
2,3,2.51,136.0,151.0,151.0,Direct,BB,11.1,8.87,Full,20.11.2025,153.0,154.1,-1.0,PWR
3,4,2.40,180.0,165.0,165.0,Direct,SB,10.2,8.28,Full,20.11.2025,153.0,154.1,-1.0,PWR

In [ ]:
# @title Modul 5: Der Routen-Optimierer (Version 17 - Full Names)
"""
================================================================================
MODUL 5: ROUTEN-OPTIMIERER (Route Optimizer) - V17
================================================================================

BESCHREIBUNG:
Dieses Modul importiert eine GPX-Route und berechnet die optimale Strategie.
Basierend auf V16 (VMG Logic + A3 Fix).

ÄNDERUNGEN IN V17:
- OUTPUT FORMAT: Die Spalten "Main" und "Front" zeigen nun den vollständigen
  Segelnamen (Attribut 'name') an, ohne Abkürzungen oder Formatierungen.

INPUT:
- Statisches Wetter & GPX-Route.

OUTPUT:
- Tabelle mit vollständigen Segelbezeichnungen.
================================================================================
"""

import sys
import os
import json
import copy
import math
import pandas as pd
import xml.etree.ElementTree as ET
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR ---

class DriveHandler:
    """Verwaltet den Dateizugriff."""
    COLAB_ROOT = '/content/drive'
    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename: self.set_full_path(directory, filename)
    def _is_colab(self) -> bool: return 'google.colab' in sys.modules
    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True
    def set_full_path(self, directory: str, filename: str) -> str:
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath
    def exists(self) -> bool: return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

def create_dummy_gpx(directory: str, filename: str):
    """Erzeugt eine erweiterte Test-Route (Kreuz -> Reach -> Deep -> Run)."""
    gpx_content = """<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GeminiAI">
  <rte>
    <name>Race Course Extended</name>
    <rtept lat="54.4000" lon="10.4000"><name>START</name></rtept>
    <rtept lat="54.4500" lon="10.3500"><name>WP1 (Upwind)</name></rtept>
    <rtept lat="54.4500" lon="10.5000"><name>WP2 (Reach)</name></rtept>
    <rtept lat="54.4200" lon="10.5500"><name>WP3 (Deep Reach)</name></rtept>
    <rtept lat="54.3800" lon="10.5500"><name>ZIEL (Run)</name></rtept>
  </rte>
</gpx>"""
    if 'google.colab' in sys.modules:
        root = '/content/drive/MyDrive'
        path = os.path.join(root, directory, filename)
        if not os.path.exists(root):
             from google.colab import drive
             drive.mount('/content/drive')
    else:
        path = os.path.join(directory, filename)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f: f.write(gpx_content)
        print(f"INFO: Erweiterte Dummy-GPX erzeugt unter: {path}")
    except Exception as e: print(f"WARNUNG: Konnte Dummy-GPX nicht schreiben: {e}")

# --- 2. GEO MATH ---

class GeoMath:
    @staticmethod
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 3440.065 # nm
        phi1, phi2 = math.radians(lat1), math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)
        a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        return R * c

    @staticmethod
    def calculate_bearing(lat1, lon1, lat2, lon2):
        y = math.sin(math.radians(lon2-lon1)) * math.cos(math.radians(lat2))
        x = math.cos(math.radians(lat1))*math.sin(math.radians(lat2)) - \
            math.sin(math.radians(lat1))*math.cos(math.radians(lat2))*math.cos(math.radians(lon2-lon1))
        theta = math.atan2(y, x)
        return (math.degrees(theta) + 360) % 360

# --- 3. VPP ENGINE ---

class VppTacticalEngine:
    def __init__(self, polars_data):
        self.polars = polars_data

    def _interpolate_curve(self, curve_data, tws, twa):
        if not curve_data: return None
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]
        lower = lower_candidates[-1] if lower_candidates else sorted_curves[0]
        upper = upper_candidates[0] if upper_candidates else sorted_curves[-1]
        tws_fac = 0.0 if lower["tws"] == upper["tws"] else (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        def get_vals_at_twa(curve_points, t_twa):
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))
        final = {}
        for k in vals_low: final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac
        return final

    def get_vmg_angles(self, tws):
        data = self.polars.get("optimal", {}).get("data", [])
        if not data: return (45.0, 150.0)
        sorted_curves = sorted(data, key=lambda x: abs(x["tws"] - tws))
        best_fit = sorted_curves[0]["curve"]
        twas = [p["twa"] for p in best_fit]
        return min(twas), max(twas)

    def get_targets(self, tws, twa):
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws, twa):
        speeds = {}
        h_res = self._interpolate_curve(self.polars.get("headsail", {}).get("data", []), tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0
        a_data = self.polars.get("asymmetric", {}).get("data", []) or self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0
        s_res = self._interpolate_curve(self.polars.get("symmetric", {}).get("data", []), tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0
        return speeds

# --- 4. LOGIK (SailStrategist - V16 FIX) ---

class SailStrategist:
    def __init__(self, sail_inventory, rig_config, main_reef_drops):
        self.inventory = copy.deepcopy(sail_inventory)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._generate_virtual_spi_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        for s in self.inventory:
            area = s.get("area", 0)
            if s.get("type") == "HEAD": self.max_jib_area = max(self.max_jib_area, area)
            if s.get("type") in ["SYM", "ASYM"]: self.max_spi_area = max(self.max_spi_area, area)
            if s.get("type") == "MAIN":
                if area > self.max_main_area: self.max_main_area = area
                if s.get("attributes", {}).get("Active") == "1": self.active_main = s
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)
                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    new_area = s.get("area", 0) - removed_area
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = new_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        if not self.active_main or self.rig_p == 0: return
        m_area = self.active_main.get("area", 0)
        new_sails = []
        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0
            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_spi_reefs(self):
        target_orc_id = "#62037"
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") == target_orc_id:
                orig_area = s.get("area", 0)
                m = s.get("measurements", {})
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 7.62)
                avg_drop = 1.40
                removed_strip_area = sfl * avg_drop
                new_area = orig_area - removed_strip_area
                v = copy.deepcopy(s)
                v["internal_id"] += "_REEF"
                v["name"] = "A3 (Reff: SLU-1.2m/SLE-1.6m)"
                v["area"] = new_area
                v["is_virtual"] = True
                v["strategy_type"] = "REACHER"
                v["parent_area"] = orig_area
                new_sails.append(v)
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa, tws, comparison_speeds, reef_factor):
        abs_twa = abs(twa)

        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False
        if abs_twa > 60 and max_spi_speed > (speed_head + 0.2):
            mode = "DOWNWIND"
            use_spi = True

        # --- MAIN SELECTION ---
        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]
        target_main = self.max_main_area * reef_factor

        if reef_factor > 0.88:
            best_main = self.active_main
        else:
            def score_main(m):
                diff = m.get("area", 0) - target_main
                if diff < 0: return abs(diff) * 2.5
                return diff
            best_main = min(mains, key=score_main)

        # --- FRONT SELECTION ---
        best_front = None
        if not use_spi:
            # HEADSAIL
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor

            def score_jib(j):
                diff = j.get("area", 0) - target_jib
                if diff < 0: return abs(diff) * 2.0
                return diff
            best_front = min(jibs, key=score_jib)

            if reef_factor > 0.90 and best_front.get("is_virtual"):
                 pid = best_front["internal_id"].split("_REEF")[0]
                 best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)

        else:
            # SPI MODE
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"

            all_spis = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"] or "SPI" in s.get("strategy_type", "")]
            candidates = []

            for s in all_spis:
                # FILTER 1: Form (Unter 20kn egal)
                if tws < 20: is_shape_ok = True
                else:
                     if needed_type == "SYM": is_shape_ok = (s.get("type") == "SYM")
                     else: is_shape_ok = (s.get("strategy_type") == needed_type)

                # FILTER 2: Reff Sperre (Unter 24kn verboten)
                is_reff_ok = True
                if s.get("is_virtual") and "A3" in s.get("name", ""):
                     if tws < 24: is_reff_ok = False

                if is_shape_ok and is_reff_ok: candidates.append(s)

            if not candidates:
                 candidates = [s for s in all_spis if not (s.get("is_virtual") and tws < 24)]

            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                if tws > 22 and len(candidates) > 1: best_front = candidates[-1]
                else: best_front = candidates[0]

        return {'main': best_main, 'head': best_front, 'mode': mode, 'speed_potential': max_spi_speed if use_spi else speed_head}


# --- 5. EXECUTION ---

def run_route_optimization(twd, tws, main_drops, data_dir, json_filename, gpx_filename):
    h_json = DriveHandler(data_dir, json_filename)
    h_gpx = DriveHandler(data_dir, gpx_filename)

    if not h_gpx.exists():
        print("GPX nicht gefunden. Erzeuge Dummy-Route...")
        create_dummy_gpx(data_dir, gpx_filename)
        h_gpx.set_full_path(data_dir, gpx_filename)

    if not h_json.exists():
        print(f"CRITICAL: ORC Datei {json_filename} fehlt!")
        return

    with h_json as handler:
        with handler.open_read() as f: data = json.load(f)

    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    try:
        with h_gpx as handler: tree = ET.parse(handler.filepath)
        root = tree.getroot()
        ns = {'gpx': 'http://www.topografix.com/GPX/1/1'}
        route_points = root.findall(".//gpx:rtept", ns) or root.findall(".//rtept")
        if len(route_points) < 2: return
    except Exception as e:
        print(f"GPX Fehler: {e}")
        return

    results = []
    beat_angle, gybe_angle = engine.get_vmg_angles(tws)
    print(f"VMG Strategie ({tws} kn): Beat < {beat_angle:.1f}°, Gybe > {gybe_angle:.1f}°")

    for i in range(len(route_points) - 1):
        p1, p2 = route_points[i], route_points[i+1]
        lat1, lon1 = float(p1.get("lat")), float(p1.get("lon"))
        lat2, lon2 = float(p2.get("lat")), float(p2.get("lon"))

        dist = GeoMath.haversine_distance(lat1, lon1, lat2, lon2)
        hdg = GeoMath.calculate_bearing(lat1, lon1, lat2, lon2)

        diff = (twd - hdg) % 360
        geo_twa = 360 - diff if diff > 180 else diff
        side = "BB" if diff > 180 else "SB"

        strategy = "Direct"
        sailed_twa = geo_twa

        if abs(geo_twa) < beat_angle:
            sailed_twa = beat_angle
            strategy = "VMG UP"
        elif abs(geo_twa) > gybe_angle:
            sailed_twa = gybe_angle
            strategy = "VMG DOWN"

        targets = engine.get_targets(tws, sailed_twa)
        comp_speeds = engine.compare_configurations(tws, sailed_twa)

        if targets:
            rec = strategist.determine_best_config(sailed_twa, tws, comp_speeds, targets['reef'])
            m_sail = rec['main']
            h_sail = rec['head']

            # --- NAMENSGEBUNG (NEU V17: Full Names) ---
            m_name = m_sail['name'] if m_sail else "None"
            f_name = h_sail['name'] if h_sail else "None"

            act_area = (m_sail.get('area',0) if m_sail else 0) + (h_sail.get('area',0) if h_sail else 0)
            base = strategist.max_main_area + (strategist.max_jib_area if rec['mode']=="UPWIND" else strategist.max_spi_area)
            tgt_area = base * targets['reef']
            delta = act_area - tgt_area

            results.append({
                "Leg": i+1,
                "Dist": round(dist, 2),
                "HDG": round(hdg, 0),
                "Geo TWA": round(geo_twa, 0),
                "Sail TWA": round(sailed_twa, 0),
                "Strat": strategy,
                "Side": side,
                "AWS": round(targets['aws'], 1),
                "BSP": round(targets['bsp'], 2),
                "Main": m_name,
                "Front": f_name,
                "Area": round(act_area, 1),
                "Soll": round(tgt_area, 1),
                "Delta": round(delta, 1),
                "Trim": "FLAT" if targets['flat'] < 0.95 else "PWR"
            })

    df = pd.DataFrame(results)
    print("\n" + "="*80)
    print(f" ROUTEN-ANALYSE: {data['meta']['boat_name']}")
    print(f" Wetter: TWD {twd}° | TWS {tws} kn")
    print("="*80)
    try:
        from IPython.display import display
        display(df)
    except:
        print(df.to_string())

# --- 6. USER INPUT ---

# @markdown ### Wetter (Statisch)
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 18 # @param {type:"number"}

# @markdown ### Reff Konfiguration
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### Dateien
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}
GPX_FILENAME = "Kursdaten.gpx" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_route_optimization(WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME, GPX_FILENAME)

In [ ]:
# @title Modul 5: Der Routen-Optimierer (Version 18 - VMG Calculation Fix)
"""
================================================================================
MODUL 5: ROUTEN-OPTIMIERER (Route Optimizer) - V18
================================================================================

BESCHREIBUNG:
Dieses Modul importiert eine GPX-Route und berechnet die optimale Strategie.

ÄNDERUNGEN IN V18 (SPEED FIX):
- VMG-BERECHNUNG: Der Algorithmus sucht nicht mehr den kleinsten Winkel (Pinching),
  sondern berechnet mathematisch den Punkt mit der besten VMG (Velocity Made Good).
  Das führt dazu, dass das Boot an der Kreuz etwas tiefer, aber deutlich schneller
  gerechnet wird (Ziel: ~7.0kn statt 6.7kn bei 18kn Wind).

INPUT:
- Statisches Wetter & GPX-Route.

OUTPUT:
- Tabelle mit physikalisch korrekten VMG-Target-Speeds.
================================================================================
"""

import sys
import os
import json
import copy
import math
import pandas as pd
import xml.etree.ElementTree as ET
import numpy as np
from typing import List, Dict, Any, Tuple, Optional

# --- 1. INFRASTRUKTUR ---

class DriveHandler:
    """Verwaltet den Dateizugriff."""
    COLAB_ROOT = '/content/drive'
    def __init__(self, directory: Optional[str] = None, filename: Optional[str] = None):
        self.filepath: Optional[str] = None
        self._mounted = False
        if directory and filename: self.set_full_path(directory, filename)
    def _is_colab(self) -> bool: return 'google.colab' in sys.modules
    def _mount(self):
        if self._is_colab() and not self._mounted:
            if not os.path.exists(self.COLAB_ROOT):
                from google.colab import drive
                drive.mount(self.COLAB_ROOT)
            self._mounted = True
    def set_full_path(self, directory: str, filename: str) -> str:
        if self._is_colab():
            self._mount()
            self.filepath = os.path.join(self.COLAB_ROOT, 'MyDrive', directory, filename)
        else:
            self.filepath = os.path.abspath(os.path.join(directory, filename))
        return self.filepath
    def exists(self) -> bool: return self.filepath and os.path.exists(self.filepath)
    def open_read(self): return open(self.filepath, 'r', encoding='utf-8')
    def __enter__(self): return self
    def __exit__(self, exc_type, exc_val, exc_tb): pass

def create_dummy_gpx(directory: str, filename: str):
    """Erzeugt eine erweiterte Test-Route (Kreuz -> Reach -> Deep -> Run)."""
    gpx_content = """<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GeminiAI">
  <rte>
    <name>Race Course Extended</name>
    <rtept lat="54.4000" lon="10.4000"><name>START</name></rtept>
    <rtept lat="54.4500" lon="10.3500"><name>WP1 (Upwind)</name></rtept>
    <rtept lat="54.4500" lon="10.5000"><name>WP2 (Reach)</name></rtept>
    <rtept lat="54.4200" lon="10.5500"><name>WP3 (Deep Reach)</name></rtept>
    <rtept lat="54.3800" lon="10.5500"><name>ZIEL (Run)</name></rtept>
  </rte>
</gpx>"""
    if 'google.colab' in sys.modules:
        root = '/content/drive/MyDrive'
        path = os.path.join(root, directory, filename)
        if not os.path.exists(root):
             from google.colab import drive
             drive.mount('/content/drive')
    else:
        path = os.path.join(directory, filename)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f: f.write(gpx_content)
        print(f"INFO: Erweiterte Dummy-GPX erzeugt unter: {path}")
    except Exception as e: print(f"WARNUNG: Konnte Dummy-GPX nicht schreiben: {e}")

# --- 2. GEO MATH ---

class GeoMath:
    @staticmethod
    def haversine_distance(lat1, lon1, lat2, lon2):
        R = 3440.065 # nm
        phi1, phi2 = math.radians(lat1), math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)
        a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        return R * c

    @staticmethod
    def calculate_bearing(lat1, lon1, lat2, lon2):
        y = math.sin(math.radians(lon2-lon1)) * math.cos(math.radians(lat2))
        x = math.cos(math.radians(lat1))*math.sin(math.radians(lat2)) - \
            math.sin(math.radians(lat1))*math.cos(math.radians(lat2))*math.cos(math.radians(lon2-lon1))
        theta = math.atan2(y, x)
        return (math.degrees(theta) + 360) % 360

# --- 3. VPP ENGINE (VMG FIX) ---

class VppTacticalEngine:
    def __init__(self, polars_data):
        self.polars = polars_data

    def _interpolate_curve(self, curve_data, tws, twa):
        if not curve_data: return None
        sorted_curves = sorted(curve_data, key=lambda x: x["tws"])
        lower_candidates = [c for c in sorted_curves if c["tws"] <= tws]
        upper_candidates = [c for c in sorted_curves if c["tws"] >= tws]
        lower = lower_candidates[-1] if lower_candidates else sorted_curves[0]
        upper = upper_candidates[0] if upper_candidates else sorted_curves[-1]
        tws_fac = 0.0 if lower["tws"] == upper["tws"] else (tws - lower["tws"]) / (upper["tws"] - lower["tws"])

        def get_vals_at_twa(curve_points, t_twa):
            twas = np.array([p["twa"] for p in curve_points])
            keys = ["bsp", "heel", "reef", "flat", "awa", "aws"]
            res = {}
            for k in keys:
                vals = np.array([p.get(k, 0) for p in curve_points])
                res[k] = float(np.interp(t_twa, twas, vals))
            return res
        vals_low = get_vals_at_twa(lower["curve"], abs(twa))
        vals_high = get_vals_at_twa(upper["curve"], abs(twa))
        final = {}
        for k in vals_low: final[k] = vals_low[k] + (vals_high[k] - vals_low[k]) * tws_fac
        return final

    def get_vmg_angles(self, tws):
        """
        Berechnet echte VMG-Winkel durch Maximierung von Speed * cos(TWA).
        """
        data = self.polars.get("optimal", {}).get("data", [])
        if not data: return (45.0, 150.0)

        # Finde Kurve für diesen Wind
        sorted_curves = sorted(data, key=lambda x: abs(x["tws"] - tws))
        # Da wir interpolieren könnten, nehmen wir hier vereinfacht die nächste Kurve
        # für die Winkelbestimmung (Winkel ändern sich nicht drastisch zwischen 18 und 20kn)
        best_fit_points = sorted_curves[0]["curve"]

        best_upwind_vmg = -1.0
        best_upwind_angle = 45.0

        best_downwind_vmg = -1.0
        best_downwind_angle = 150.0

        for p in best_fit_points:
            twa = p["twa"]
            bsp = p["bsp"]

            # Upwind VMG (cos(twa))
            if twa < 90:
                vmg = bsp * math.cos(math.radians(twa))
                if vmg > best_upwind_vmg:
                    best_upwind_vmg = vmg
                    best_upwind_angle = twa

            # Downwind VMG (cos(twa) ist negativ, wir maximieren den Betrag oder Speed * -cos)
            if twa > 90:
                # VMG nach Lee
                vmg = bsp * math.cos(math.radians(twa)) * -1
                if vmg > best_downwind_vmg:
                    best_downwind_vmg = vmg
                    best_downwind_angle = twa

        return best_upwind_angle, best_downwind_angle

    def get_targets(self, tws, twa):
        data = self.polars.get("optimal", {}).get("data", [])
        return self._interpolate_curve(data, tws, twa)

    def compare_configurations(self, tws, twa):
        speeds = {}
        h_res = self._interpolate_curve(self.polars.get("headsail", {}).get("data", []), tws, twa)
        speeds['HEAD'] = h_res['bsp'] if h_res else 0.0
        a_data = self.polars.get("asymmetric", {}).get("data", []) or self.polars.get("asymmetric_1", {}).get("data", [])
        a_res = self._interpolate_curve(a_data, tws, twa)
        speeds['ASYM'] = a_res['bsp'] if a_res else 0.0
        s_res = self._interpolate_curve(self.polars.get("symmetric", {}).get("data", []), tws, twa)
        speeds['SYM'] = s_res['bsp'] if s_res else 0.0
        return speeds

# --- 4. LOGIK (SailStrategist - V17 Basis) ---

class SailStrategist:
    def __init__(self, sail_inventory, rig_config, main_reef_drops):
        self.inventory = copy.deepcopy(sail_inventory)
        self.rig_p = float(rig_config.get("p", {}).get("value", 0))
        self.reef_drops = main_reef_drops
        self.max_jib_area = 0.0
        self.max_main_area = 0.0
        self.max_spi_area = 0.0
        self.active_main = None
        self._analyze_inventory()
        self._generate_virtual_jib_reefs()
        self._generate_virtual_main_reefs()
        self._generate_virtual_spi_reefs()
        self._classify_spinnakers()

    def _analyze_inventory(self):
        for s in self.inventory:
            area = s.get("area", 0)
            if s.get("type") == "HEAD": self.max_jib_area = max(self.max_jib_area, area)
            if s.get("type") in ["SYM", "ASYM"]: self.max_spi_area = max(self.max_spi_area, area)
            if s.get("type") == "MAIN":
                if area > self.max_main_area: self.max_main_area = area
                if s.get("attributes", {}).get("Active") == "1": self.active_main = s
        if not self.active_main and self.max_main_area > 0:
            self.active_main = max([s for s in self.inventory if s.get("type")=="MAIN"], key=lambda x:x.get("area",0))

    def _generate_virtual_jib_reefs(self):
        reff_config = {"#60273": 1.25, "#62013": 1.06}
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") in reff_config:
                reduction = reff_config[s["orc_sail_id"]]
                m = s.get("measurements", {})
                attr = s.get("attributes", {})
                jl = float(m.get("jl", 0) or attr.get("JIBLUFF", 0) or attr.get("HLU", 0) or 0)
                lpg = float(m.get("lpg", 0) or attr.get("LPG", 0) or attr.get("HLP", 0) or 0)
                if jl > 0 and lpg > 0:
                    width_at_cut = lpg * (1 - (reduction / jl))
                    removed_area = reduction * (lpg + width_at_cut) / 2.0
                    new_area = s.get("area", 0) - removed_area
                    v = copy.deepcopy(s)
                    v["internal_id"] += "_REEF"
                    v["name"] = f"{s.get('name')} (Reff -{reduction}m)"
                    v["area"] = new_area
                    v["is_virtual"] = True
                    v["strategy_type"] = "HEAD_REEF"
                    v["parent_area"] = s.get("area", 0)
                    new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_main_reefs(self):
        if not self.active_main or self.rig_p == 0: return
        m_area = self.active_main.get("area", 0)
        new_sails = []
        for i, drop in enumerate(self.reef_drops, 1):
            if drop >= self.rig_p: continue
            e_approx = 2 * m_area / self.rig_p
            width_at_cut = e_approx * (1 - (drop / self.rig_p))
            removed = drop * (e_approx + width_at_cut) / 2.0
            v = copy.deepcopy(self.active_main)
            v["internal_id"] += f"_R{i}"
            v["name"] = f"MAIN (Reff {i}: -{drop}m)"
            v["area"] = m_area - removed
            v["is_virtual"] = True
            v["strategy_type"] = "MAIN_REEF"
            v["parent_area"] = m_area
            new_sails.append(v)
        self.inventory.extend(new_sails)

    def _generate_virtual_spi_reefs(self):
        target_orc_id = "#62037"
        new_sails = []
        for s in self.inventory:
            if s.get("orc_sail_id") == target_orc_id:
                orig_area = s.get("area", 0)
                m = s.get("measurements", {})
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 7.62)
                avg_drop = 1.40
                removed_strip_area = sfl * avg_drop
                new_area = orig_area - removed_strip_area
                v = copy.deepcopy(s)
                v["internal_id"] += "_REEF"
                v["name"] = "A3 (Reff: SLU-1.2m/SLE-1.6m)"
                v["area"] = new_area
                v["is_virtual"] = True
                v["strategy_type"] = "REACHER"
                v["parent_area"] = orig_area
                new_sails.append(v)
        self.inventory.extend(new_sails)

    def _classify_spinnakers(self):
        for s in self.inventory:
            if s.get("type") in ["SYM", "ASYM"]:
                m = s.get("measurements", {})
                shw = float(m.get("shw", 0) or m.get("amg", 0) or 0)
                sfl = float(m.get("sfl", 0) or m.get("asf", 0) or 0)
                if sfl > 0:
                    s["strategy_type"] = "REACHER" if (shw/sfl) < 0.75 else "RUNNER"

    def determine_best_config(self, twa, tws, comparison_speeds, reef_factor):
        abs_twa = abs(twa)

        speed_head = comparison_speeds.get("HEAD", 0)
        speed_asym = comparison_speeds.get("ASYM", 0)
        speed_sym = comparison_speeds.get("SYM", 0)
        max_spi_speed = max(speed_asym, speed_sym)

        mode = "UPWIND"
        use_spi = False
        if abs_twa > 60 and max_spi_speed > (speed_head + 0.2):
            mode = "DOWNWIND"
            use_spi = True

        # --- MAIN SELECTION ---
        mains = [self.active_main] + [s for s in self.inventory if s.get("strategy_type") == "MAIN_REEF"]
        mains = [m for m in mains if m is not None]
        target_main = self.max_main_area * reef_factor

        if reef_factor > 0.88:
            best_main = self.active_main
        else:
            def score_main(m):
                diff = m.get("area", 0) - target_main
                if diff < 0: return abs(diff) * 2.5
                return diff
            best_main = min(mains, key=score_main)

        # --- FRONT SELECTION ---
        best_front = None
        if not use_spi:
            # HEADSAIL
            jibs = [s for s in self.inventory if s.get("type") == "HEAD" or s.get("strategy_type") == "HEAD_REEF"]
            target_jib = self.max_jib_area * reef_factor

            def score_jib(j):
                diff = j.get("area", 0) - target_jib
                if diff < 0: return abs(diff) * 2.0
                return diff
            best_front = min(jibs, key=score_jib)

            if reef_factor > 0.90 and best_front.get("is_virtual"):
                 pid = best_front["internal_id"].split("_REEF")[0]
                 best_front = next((x for x in jibs if x["internal_id"]==pid), best_front)

        else:
            # SPI MODE FIX V16
            needed_type = "RUNNER" if abs_twa > 130 else "REACHER"
            if speed_sym > speed_asym + 0.2: needed_type = "SYM"

            all_spis = [s for s in self.inventory if s.get("type") in ["SYM", "ASYM"] or "SPI" in s.get("strategy_type", "")]
            candidates = []

            for s in all_spis:
                # FILTER 1: Form
                if tws < 20: is_shape_ok = True
                else:
                     if needed_type == "SYM": is_shape_ok = (s.get("type") == "SYM")
                     else: is_shape_ok = (s.get("strategy_type") == needed_type)

                # FILTER 2: Reff Sperre
                is_reff_ok = True
                if s.get("is_virtual") and "A3" in s.get("name", ""):
                     if tws < 24: is_reff_ok = False

                if is_shape_ok and is_reff_ok: candidates.append(s)

            if not candidates:
                 candidates = [s for s in all_spis if not (s.get("is_virtual") and tws < 24)]

            if candidates:
                candidates.sort(key=lambda x: x.get("area", 0), reverse=True)
                if tws > 22 and len(candidates) > 1: best_front = candidates[-1]
                else: best_front = candidates[0]

        return {'main': best_main, 'head': best_front, 'mode': mode, 'speed_potential': max_spi_speed if use_spi else speed_head}


# --- 5. EXECUTION ---

def run_route_optimization(twd, tws, main_drops, data_dir, json_filename, gpx_filename):
    h_json = DriveHandler(data_dir, json_filename)
    h_gpx = DriveHandler(data_dir, gpx_filename)

    if not h_gpx.exists():
        print("GPX nicht gefunden. Erzeuge Dummy-Route...")
        create_dummy_gpx(data_dir, gpx_filename)
        h_gpx.set_full_path(data_dir, gpx_filename)

    if not h_json.exists():
        print(f"CRITICAL: ORC Datei {json_filename} fehlt!")
        return

    with h_json as handler:
        with handler.open_read() as f: data = json.load(f)

    inventory = data.get("sail_inventory", [])
    rig = data.get("rig_configuration", {})
    polars = data.get("polars", {}).get("configurations", {})

    strategist = SailStrategist(inventory, rig, main_drops)
    engine = VppTacticalEngine(polars)

    try:
        with h_gpx as handler: tree = ET.parse(handler.filepath)
        root = tree.getroot()
        ns = {'gpx': 'http://www.topografix.com/GPX/1/1'}
        route_points = root.findall(".//gpx:rtept", ns) or root.findall(".//rtept")
        if len(route_points) < 2: return
    except Exception as e:
        print(f"GPX Fehler: {e}")
        return

    results = []
    beat_angle, gybe_angle = engine.get_vmg_angles(tws)
    print(f"VMG Strategie ({tws} kn): Beat @ {beat_angle:.1f}°, Gybe @ {gybe_angle:.1f}°")

    for i in range(len(route_points) - 1):
        p1, p2 = route_points[i], route_points[i+1]
        lat1, lon1 = float(p1.get("lat")), float(p1.get("lon"))
        lat2, lon2 = float(p2.get("lat")), float(p2.get("lon"))

        dist = GeoMath.haversine_distance(lat1, lon1, lat2, lon2)
        hdg = GeoMath.calculate_bearing(lat1, lon1, lat2, lon2)

        diff = (twd - hdg) % 360
        geo_twa = 360 - diff if diff > 180 else diff
        side = "BB" if diff > 180 else "SB"

        strategy = "Direct"
        sailed_twa = geo_twa

        if abs(geo_twa) < beat_angle:
            sailed_twa = beat_angle
            strategy = "VMG UP"
        elif abs(geo_twa) > gybe_angle:
            sailed_twa = gybe_angle
            strategy = "VMG DOWN"

        targets = engine.get_targets(tws, sailed_twa)
        comp_speeds = engine.compare_configurations(tws, sailed_twa)

        if targets:
            rec = strategist.determine_best_config(sailed_twa, tws, comp_speeds, targets['reef'])
            m_sail = rec['main']
            h_sail = rec['head']

            m_name = m_sail['name'] if m_sail else "None"
            f_name = h_sail['name'] if h_sail else "None"

            act_area = (m_sail.get('area',0) if m_sail else 0) + (h_sail.get('area',0) if h_sail else 0)
            base = strategist.max_main_area + (strategist.max_jib_area if rec['mode']=="UPWIND" else strategist.max_spi_area)
            tgt_area = base * targets['reef']
            delta = act_area - tgt_area

            results.append({
                "Leg": i+1,
                "Dist": round(dist, 2),
                "HDG": round(hdg, 0),
                "Geo TWA": round(geo_twa, 0),
                "Sail TWA": round(sailed_twa, 0),
                "Strat": strategy,
                "Side": side,
                "AWS": round(targets['aws'], 1),
                "BSP": round(targets['bsp'], 2),
                "Main": m_name,
                "Front": f_name,
                "Area": round(act_area, 1),
                "Soll": round(tgt_area, 1),
                "Delta": round(delta, 1),
                "Trim": "FLAT" if targets['flat'] < 0.95 else "PWR"
            })

    df = pd.DataFrame(results)
    print("\n" + "="*80)
    print(f" ROUTEN-ANALYSE: {data['meta']['boat_name']}")
    print(f" Wetter: TWD {twd}° | TWS {tws} kn")
    print("="*80)
    try:
        from IPython.display import display
        display(df)
    except:
        print(df.to_string())

# --- 6. USER INPUT ---

# @markdown ### Wetter (Statisch)
WIND_TWD = 345 # @param {type:"number"}
WIND_TWS = 18 # @param {type:"number"}

# @markdown ### Reff Konfiguration
MAIN_REEF_1_M = 1.66 # @param {type:"number"}
MAIN_REEF_2_M = 4.11 # @param {type:"number"}

# @markdown ### Dateien
DATA_DIR = "Segeln/ORC_Vermessung" # @param {type:"string"}
JSON_FILENAME = "ORC_SpeedGuide_TRUE_GRIT_27.12.2025.json" # @param {type:"string"}
GPX_FILENAME = "Kursdaten.gpx" # @param {type:"string"}

if __name__ == "__main__":
    drops = (MAIN_REEF_1_M, MAIN_REEF_2_M)
    run_route_optimization(WIND_TWD, WIND_TWS, drops, DATA_DIR, JSON_FILENAME, GPX_FILENAME)

Mounted at /content/drive
VMG Strategie (18 kn): Beat @ 38.4°, Gybe @ 168.2°

================================================================================
 ROUTEN-ANALYSE: TRUE GRIT
 Wetter: TWD 345° | TWS 18 kn
================================================================================

,Leg,Dist,HDG,Geo TWA,Sail TWA,Strat,Side,AWS,BSP,Main,Front,Area,Soll,Delta,Trim
0,1,3.47,330.0,15.0,38.0,VMG UP,SB,23.2,6.70,MAIN (Reff 2: -4.11m),J3 HvyZip 27.6sqm (Reff -1.06m),41.4,38.3,3.0,FLAT
1,2,5.24,90.0,105.0,105.0,Direct,BB,16.5,8.71,WhtHvy 37sqm,A2 Bl/Wt 166sqm,153.0,129.7,23.3,FLAT
2,3,2.51,136.0,151.0,151.0,Direct,BB,11.1,8.87,WhtHvy 37sqm,A2 Bl/Wt 166sqm,153.0,154.1,-1.0,PWR
3,4,2.40,180.0,165.0,165.0,Direct,SB,10.2,8.28,WhtHvy 37sqm,A2 Bl/Wt 166sqm,153.0,154.1,-1.0,PWR